(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap10 = function() {
	this.initialize(img.Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Bitmap11 = function() {
	this.initialize(img.Bitmap11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,272,177);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtTitle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHsB8IgDgBIAAgCIAAjLQAAgZgBgPIAbABQAFABAAACIgCAGQgCAEAAAZIABDMIgBACIgCABgADHB3QgJgLgIgFQAPgXAEgeQAFgYAAgkIgBgmIABgCIACAAIA4AAQgFgMgHgMIgsAAIgDAAIAAgDIAAgSIABgCIACAAIBaAAIAAgDQAAgOgCgJIAcABQABABABAAQABAAAAAAQABABAAAAQAAABAAAAIgCAGQgBADAAAKIAAADIBaAAIADAAIAAACIAAASIAAADIgDAAIgpAAIgNAYIA/AAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAASQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIi/gBIAAARQAAAYgDAZQATgRAMgdIADgOIAYAGQABAAABAAQAAAAABABQAAAAAAABQAAAAAAAAIgCAEQgBACgEAHIgBADIAgAAIAAgCQAAgMgCgLIAcABQABABABAAQABAAAAAAQABABAAAAQAAABAAAAIgBAFIgBAOIAAACIA/AAIACAAIABADIAAASIgBADIgCABIg/gBIAAAVIA1gBIADABIAAABIAAASIAAADIgDAAIg1AAIAAAXIBQAAIACAAIABACIAAATIgBADIgCAAIi+AAIgDAAIAAgDIAAgTIAAgCIADAAIBSAAIAAgXIgxAAIgDAAIAAgDIAAgSIAAgCIADAAIAxABIAAgVIgsAAQgHANgLAOQgEAEgCAAIgDgDQgGgIgIgGIgDARQgEAfgOAcQgEAGgCgBQgBABgDgEgAEkgyIApAAIALgYIg/AAgAlxBVQg7AKhaAKIgHgcIAUgCQAdhRAZhlIAeAIQgYBVgfBXQA1gFAtgGQgOghgTghIAagKQAeAyAZBCIgdANgAt8BeQAogQAOgWQAMgUABgkIhSAAIAAgZIBSAAIAAgpQgXAEgkADIgMgYQBQgGA8gUIAOAYQgWAIgfAGIAAAuIBEAAIAAAZIhEAAQAAAvgVAcQgRAYgmAQgAIYBzIgDgBIAAgCIAAgVIAAgDIADAAIBHAAIAAg0IgyAAIgDAAIgBgDIAAgVIABgCIADgBIAyABIAAgvIghAAQgFAQgIAQQgDAFgCAAIgFgDQgJgGgKgDQAGgLAGgNIgLAEIgDABQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgDgTgHgQIgBgDQAAAAABgBQAAAAAAAAQABAAAAAAQABgBABAAIALgEIACAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABQAJAVACAMQAJgXADgVIACgTQAOADAMAEQAFABAAACIgCAEQgCAEgBAEIgEAVIAYAAIAAgUQAAgWgCgSIAdABQAFABAAACIgBAGQgCAGgBAXIAAAVIA5AAIACAAIABADIAAAUIgBACIgCABIg5gBIAAAvIAygBIACABIAAACIAAAVIAAADIgCAAIgyAAIAAA0IBBAAIADAAIAAADIAAAVIgBACIgCABgAL+BmQgLgJAAgUQAAgTANgPQAQgPAjgRQAAgMgFgFQgCgDgIAAQgMAAgRAOQgMAKgSAVIgVgSQAlgjASgmIgwAAIAAgYIA7ABQAGgPAGgVIAbAFIgKAeQAmgBAfgDIABAXIhTAFQgJARgMANIgGAGIABABIAHgEQALgIAMAAQAOAAAIAJQAIAHAEAOIA2gYIAKAaQgkALgbAMIAAA1IgZAAIAAgpQgZANgJAJQgGAHgBAIQAAAMALAEQAKAFAcAAQAeAAAogFIABAaQgkACgnAAQgqAAgQgMgAjUBbQApgJASgXQAOgTgBghQAAgpgRgVQgNgPgWgBQgEBXgWAxQgJATgLAJQgJAFgNABQgWgBgNgVQgLgVAAghQAAg2AeghQAPgPAUgHQASgHAVgBQBcAAAABqQAABShYAUgAkDgsQgVAaABAqQgBAZAHAMQAFAKAIgBQAGABAEgFQAFgEADgKQAJgZAHgiQAFghABgdQgVABgSAYgAhMBwIgDgBIAAgCIAAgXIAAgCIADgBIBlABIAAgyIhCABIgCgBIgBgCIAAgWQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAIBCABIAAgtIg4AAQgKAUgNARQgEAEgCAAIgGgEQgIgGgIgFQAbghAQguQADgJABgIIAaAFQAFACgBADIgCAEQgDADgCAIIgGASIArAAIAAgOQAAgagCgQIAfACQADABAAADIgBAFQgBAFAAAZIAAAPIBTgBIACABIABACIAAAWIgBADIgCAAIhTAAIAAAtIBHgBQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAWIAAACIgCABIhHgBIAAAyIBigBIACABIAAACIAAAXIAAACIgCABgAq8AOIAAgcICZAAIAAAcgAHVABIgNgFQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIABgCQAHgXABggQAAAAABgBQAAAAAAAAQAAgBAAAAQAAAAAAAAIAEAAIANADQADABAAADIAAAAQgCAngGAUIgCACIgDgBg");
	this.shape.setTransform(26.4,1.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txtTitle, new cjs.Rectangle(-64.4,-10.5,181.60000000000002,24.8), null);


(lib.txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANZAzQgFgFAAgHQAAgIAGgFQAFgEAHAAQAIAAAFAFQAEAFAAAHQAAAIgFAFQgFAEgHAAQgIAAgFgFgANeAgQgCADAAAEQAAAFADACQADADAEAAQAEAAADgDQADgDAAgEQAAgFgDgCQgDgDgEAAQgFAAgDADgACuAzQgFgFAAgHQAAgIAGgFQAFgEAHAAQAIAAAFAFQAEAFAAAHQAAAIgFAFQgFAEgHAAQgIAAgFgFgACzAgQgCADAAAEQAAAFADACQADADAEAAQAEAAADgDQADgDAAgEQAAgFgDgCQgDgDgEAAQgFAAgDADgAj6A2IgDgLIANgBIADAAIAAgJQgLAGgNADIgDAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBQgCgEgDgCQAYgEAPgJIgjAAIgBAAIAAgBIAAgIIAAgBIABAAIAxAAIAAgGIgEAAIgBAAIgBgCQAAgCgCgDIAFAAQAAAAABAAQAAAAAAAAQAAgBABAAQAAgBAAAAIAAgEIgLAAIAAAOQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgJAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgOIgKAAIAAALIAAACIgBAAIgIAAIgCgBIAAgTQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIATAAIAAgFIgZAAIgBAAIgBgCIAAgGIABgBIABAAIAZAAIAAgFIgNAAIgCADIgDACIgDgCIgFgCQAFgGADgGIACgGIAJACIACABIgBABIgCADIAAABIAIAAIgBgKIALABQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIgBACIAAAFIAUAAIABAAIAAABIAAAHIAAABIgBAAIgUAAIAAAFIAXAAIACAAIAAABIAAAGIAAACIgCAAIgXAAIAAAFIAUAAIABABIAAANQAAADgBABIADAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIgBACQAAABAAAAQAAAAgBABQAAAAAAABQAAABAAABIAtAAIABAAIAAABIAAAIIAAABIgBAAIgRAAIAHAFIABACIgBACIgMAGQALAFAOADQgDADgCAFQAAAAAAABQgBABAAAAQAAAAgBABQAAAAAAAAIgDgBQghgJgMgYIgBAAIgKAHIAAANIAWgEIAAAHIgBADIgDABIgjAGIgEACIgCAAIgCgBgAjAAeIAIgGIAEgEIgWAAQAEAGAGAEgAGNA3IgJAAIgBAAIgBgCIABgvIgLAAIgEABIgCABQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIgCgJIAJAAIAHgJIgPgRIgBgBIABgCIAEgGIABgBIABABIADADIAHgNIADgHIAKAEIACACIgCACIgCADIgKAQIAEAGIAJgNIADgIIAKAFIACACIgCACQgBAAgDAEIgSAbIAOgBIgDgHIAAgBIABgBIAFgCIABgBIABABQAEAJAEAMIAAgyIAAgBIACAAIA1AAIABAAIAAABIAABeIAAABIgBAAIgJAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgGIggAAIAAAGIAAABIgBABIgJAAIgCgBIAAgBIAAgrIgBABIgGADIgBAAIgBgBIgCgGIgHABIAAAwIAAACIgBAAgAHBAiIALAAIAAgeIgLAAgAGsAiIAKAAIAAgeIgKAAgAHBgFIALAAIAAgeIgLAAgAGsgFIAKAAIAAgeIgKAAgAE+A3IgBgBIAAgBIAAgaIgWABIgBgBIgBgBIAAgJIABgBIABAAIAWAAIAAgOIgSABIgBgBIAAgBIAAgHIAAgCIABAAIASABIAAgNIgUAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgJQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAcAAQAFgIADgJIABgGIALAEIACABIgBACQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIgGAMIAQAAIABAAIAAABIAAAJIAAABIgBAAIgZAAIAAANIAVgBIABABIAAABIAAAHIAAABIgBABIgVgBIAAAOIAbAAIABAAIAAABIAAAJIAAABIgBABIgbgBIAAAaIAAABIgBABgAEHA3IgJAAIgBAAIAAgBIAAgmIAAgBIABAAIAiAAIABAAIAAABIAAAjIAAACIgBAAIgJAAIgBgBIAAgBIAAgDIgOAAIAAAGIAAABIgBAAgAEIAmIAOAAIAAgNIgOAAgAnVA3IgJAAIgBAAIgBgBIAAhHQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAoAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAA6QAAAIgDACQgCADgLAAIgEgBIgBgDIgCgHIAIAAIADgBIABgCIAAgKIgUAAIABAYIgBABIgBAAgAnUAUIAUAAIAAgJIgUAAgAnUABIAUAAIAAgIIgUAAgAhPA2IgKAAIgBgBIAAgxIAAgCIABAAIArAAIABABIABABIAAAwIgBACIgBAAIgJAAIgBAAIgBgCIAAgFIgVAAIAAAGIAAABIgBAAgAhOAkIAVAAIAAgWIgVAAgAiGA2IgKAAIgBAAIAAgBIAAgxIAAgCIABAAIAqAAIABABIAAABIAAAwIAAABIgBAAIgKAAIgBgBIAAgFIgUAAIAAAGIAAABIgBAAgAiFAkIAUAAIAAgWIgUAAgAmfA1IgBgDQgBgFgCgEIAMABQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIABgEIAAgoIgBgQIANABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAACQgBACAAAKIAAArQAAAIgEADQgDACgDAAIgLABIgEgBgABSAoQAVgCAJgIQAGgFABgHQgFAGgJAAQgKAAgFgFQgFgGAAgIQAAgJAHgGQAFgEAJAAQAFAAAFACIAAgNIguACIAAgLIAugBIAAgPIAMAAIAAAPIAcgBIAAALIgcAAIAAAZQADAFAAAJQAAARgMAJQgKAIgUAEgABigCQgCACAAAEQAAAFADADQACACAFAAQAFAAADgDQACgCAAgFQAAgJgKAAQgFAAgDADgArcApQAOgDAIgFQAIgEAEgJQADgIAAgOIAAgtIAOAAIAAAuQAAAZgMANQgKAKgXAEgAsyApQAOgDAIgFQAIgEAEgJQADgIAAgOIAAgtIAOAAIAAAuQAAAZgMANQgKAKgXAEgAMMAnIABAAQAXAAAMgGQAKgFAAgMQAAgHgEgEQgFgDgHAAQgOAAgKALQgGAGgBAEIgLgCIAEg0IAMACIgEAgIgCAHIAEgGQAMgMAQAAQAPAAAHAIQAHAGAAAMQAAAKgEAGQgEAGgIAEQgNAGgaABgAKzAoQAegBAIgEQAJgFAAgKQAAgPgPAAQgJAAgIAEQgHAFgIAJIgMgFQAJgSAGgXIgTAAIAAgLIAVAAIADgRIANABIgDAQIAlgDIAAAMIgoACQgFASgHANQANgMARAAQAOAAAHAHQAGAHAAAKQAAARgPAIQgLAFgfABgAHtALQAAgXAHgkIANABQgIAjAAAXQAAARADAVIgMABQgDgVAAgSgAgFALQAAgNAGgLQAGgKAMgGIAFgCIAAgBIgHACIgsAFIgBgMIBOgFIAAALQgMABgIAEQgYANAAAXQAAAYAkAEIgDAMQgsgEAAgjgAlGAoQASgEAIgKQAGgJAAgOQAAgSgIgJQgGgHgJgBQgCAngKAVQgEAJgFAEQgEACgGAAQgJAAgGgJQgFgJAAgPQAAgYAOgOQAGgHAJgDQAIgDAJAAQApAAAAAuQAAAkgnAJgAlcgTQgIALAAASQAAALADAGQACAEADAAQABAAABAAQAAgBABAAQAAAAABAAQAAgBABAAIADgGQAEgLADgPQADgPAAgNQgJABgJALgAoVAOQgQAWgbAOIgIgKQAYgMAQgVQAMgQAFgWIgxAAIAAgLIA+AAIADAEQgFAYgKARQAOAQANAXIgMAIQgKgTgMgRgAJSAbQAAgKAGgKIALAEQgFAHAAAIQAAAGAGACQAFADAMAAQAUAAAMgCIAAANIggABQgjAAAAgWgAIGAgQAAgIAGgFQAGgEAJAAIALABIgBghIggAAIAAgKIAgAAIAAgVIAMAAIAAAUIATgCIAAALIgTACIABAkQALAFAKALIgIAKQgHgJgGgEIAAAAQAAAJgHAEQgFAEgKAAQgWAAAAgRgAITAbQgDACAAADQAAAHAMAAQAKAAAAgKIAAgCQgEgCgIAAQgEAAgDACgAF1AtQgCgCgEgBQAEgMABgLIAAgEIAAgCIAJABQABAAAAABQABAAAAAAQAAAAAAAAQAAAAAAABIgBAFQgCANgCAKIgCACgAGWAnIgBgBQgBgJgDgNIAAAAIABgCIAFgBIACgBIABACIAEAUIAAABIgBABIgGADgAmfAdIgJAAIgCAAIAAgBIABgbIgBgQIAMABQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAACIgBALIAAAbIAAABIgBAAgAriAMIAAg6IANAAIAAA6gAs4AMIAAg6IANAAIAAA6gAEAAJIgBAAIgBgBIAAgIIABAAIABAAIAeAAIACAAIAAAAIAAAIIgBABIgBAAgAqVAGIAAgMIBEAAIAAAMgAi9AFIgBgDQgBgEgCgDIAKAAIAEgBIABgCIAAgfIgBgPIAMABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBADQgBACAAAIIABAiQAAAFgEACQgEADgMAAIgDAAgAAegPIAIgCQAFAIAEALIgIADQgEgLgFgJgAthgKIgIAOIgJgFIAMgNIgQgDIADgJIAPAGIgCgSIALAAIgCASIAPgGIADAJIgQADIALANIgIAFgAAtgSIAIgDQAFAJADAKIgIACQgEgKgEgIgAEAgGIgBAAIgBgBIAAgIIABgBIABAAIAeAAIACAAIAAABIAAAIIgBABIgBAAgAh/gHIgBgBIAAgBIAAgoIAAgBIABAAIBBAAIABAAIAAABIAAAoIAAABIgBABgAh0gTIArAAIAAgTIgrAAgAJqgTIAUgNIgRACIgUgBIAAgLIAXABIAfgCIACAMIgMAGIgTAOgAi+gLIgKAAIgBAAIAAgCIAAgXIgBgMIAMABQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIgBACIAAAIIAAAXIAAACIgBAAgAEigWIgpAAIgBAAIAAgBIAAgJQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIApAAIABAAIAAABIAAAJIAAABIgBAAgAl/gaIhoAAIgBAAIAAgBIAAgJIAAgBIABAAIAeAAIgHgMIgBgBIACgBIAIgDIABgBIABABIAHAMIABABIgCABIgIADIAbAAIAIgMIACgGIAMADIACACIgBACIgEAEIgEAHIAeAAIACAAIAAABIAAAJIAAABIgCAAgAMiglIgTgFIAEgJQAKABAMAEIASAGIgGALQgHgEgMgEgAE0ghQgDgIgFgHIAAgBIABgBIAHgDIACAAIABAAQAFAHADAIIAAABIgBABIgIAEIgBAAgAEggnIghAAIgBAAIgBgBIAAgIIABgCIABAAIAhAAIABABIAAABIAAAIIAAABIgBAAg");
	this.shape.setTransform(-122.325,283.225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt5, new cjs.Rectangle(-211,277.6,177.4,11.299999999999955), null);


(lib.txt4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AQqBYQgJgJAAgLQAAgMAKgJQAJgHAKAAQANAAAJAJQAIAIgBALQABANgKAJQgIAHgMAAQgMAAgIgJgAQzA5QgFAFAAAGQAAAIAFAFQAFAEAGAAQAJAAAEgFQAEgFAAgHQAAgHgFgFQgEgEgIAAQgHAAgEAFgAJwBdQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhsIAAgCIACAAIBDAAIACAAIABACIAABZQAAALgFAEQgDADgFABIgOABQgFAAgBgBIgBgFQgCgHgDgFIANABQAGAAAAgGIAAgPIghAAIABAlQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAKBAmIAhAAIAAgNIghAAgAKBAKIAhAAIAAgNIghAAgAIGBbIgBgFQgCgKgEgGQALACANAAQAGAAACgCQABgCAAgEIAAh5IiCAAIgCAAIAAgCIAAgQIAAgCIACgBICuAAIABABIAAACIAAAQIAAACIgBAAIgHAAIgPAAIABB9QAAAOgHAFQgHAFgdAAQgFAAgBgBgALMBXQgHgDAAgLIAAgzIgBgTIAUABQABAAABABQAAAAABAAQAAAAAAABQABAAAAABIgCADQgBACAAAJIAAAKQAQgHAPgIQAGgEAEgEQAFADAIAKIACADQAAABAAAAQAAABgBAAQAAAAgBAAQgBABgBAAIgJADQgdAOgOAFIAAAPQAAAFAEACQADACANAAQAQAAADgEQACgCABgFIAAgMQAIAEAHACIAEABIAAACIAAAEQgBAKgCAEQgCAFgEADQgJAGgYAAQgZAAgHgEgAuzBPIAAiYIAXAAIAACHQAagKATgVQASgTALgZIARAPQgSAkgaAVQgWASghAMgAnbBIQAdgLALgUQAFgKACgKQACgKAAgUIg9AAIAAgSICFAAIAAASIgxAAQgBAagEAOQgCAMgGAJQgIANgLAIQgKAIgPAHgAxUBHQAugQAUgdQASgaABgvIhbAAIAAgTIBjAAIgCgHQAAgKAIgHQAGgGAJAAQALAAAGAHQAGAHAAAJQAAAKgHAHQgHAGgJAAIgGgBQgCA/gaAgQgVAbguARgAvrhSQgEAEAAAFQAAAGAEADQAEAEAFAAQAGAAAEgEQADgEAAgFQAAgGgEgEQgDgDgGAAQgGAAgDAEgABZBDQA3gMAbglQAVgcAFgvIAWALQgKA3gcAgQgdAhg0ANgAp9BDQA3gMAbglQAUgcAGgvIAVALQgJA3gcAgQgdAhg1ANgAMyAUQABgUAEgfQACgYAFgUIAUACQgEAXgEAdQgDAYABASQgBAkAFAbIgVACQgFgeAAgkgAEhBUIgFgUIASACQAJAAADgCQADgBACgFQAFgSABgrQAAgPgEgFQgDgEgFAAIgRABQgQA/gWAwIgUgHQAYgxANg2IgjAEIgBgTIApgCQAEgVADgTIAVADIgHAkIAQgBQANAAAHAJQAIAJAAAUQAAAygHAUQgCALgIAFQgHAFgLAAQgMAAgJgBgAjABBQAzgJAbgcQANgNAKgVQAIgUAFgWIAUALQgGAZgLAVQgKAUgMANQgfAgg2ALgAgfBUIAAgSIBEAAIAAgnIhBAAIAAgSIBBAAIAAgfIhEAAIAAgSIBZAAIAAB8gAsABKQgIgHAAgSIAAhAIghAHIgFgSIAmgIIAAguIAWAAIAAApIBCgPQgFgQgJgPIAOgDQAHANAHAUIgGACIAKAMQgKAZgKARQgKAPgOARIgSgMQAcgdAHgaIg5ANIAABFQAAAGACADQACADAGABIAUABQAbAAAVgCIAAAVQgZACgbAAQgfAAgJgJgANmBHQgKgJAAgQQAAgKACgKIAUACQgCAIgBAHQABAJAGAEQAGAEAMAAQAVAAAWgDIAAAVQgSACgYAAQgYAAgLgJgAG1A3IgBAAIAAgCIAAhUIAAgCIABAAIBNAAIACAAIAAACIAABPIAAACIgCAAIgQAAIgCAAIAAgCIAAgIIgpAAIAAANIAAACIgBAAgAHHAVIApAAIAAgkIgpAAgAFPg0IASgJQAWAeAQAoIgTAKQgOgpgXgegAlOANIAAgVIByAAIAAAVgAPsgPIgPAZIgOgKIATgVIgbgFIAGgPIAZAKIgEgdIASAAIgCAdIAYgKIAGAPIgbAFIATAVIgOAKgAjKgMIAKgRQAhAMARAJIgLASQgRgLgggLgALLgGQgGgDAAgKIAAgwQAAgNgCgGIAUABQABAAABAAQABAAAAABQABAAAAAAQAAABAAAAIgBAEQgBACAAAJIAAAJQAQgFAOgHIAKgJIAMANQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBABgBAAIgJAEQgQAIgaAJIAAAMQAAAEAEACQADABAMAAQAQAAAEgEQABgCAAgEIABgLQAGADAJADIADABIABADIAAACQgBAKgCAFQgDAEgEADQgGAFgbAAQgXAAgIgDgABXgwIAOgRQAcAOAVARIgOAUQgXgUgagOgAqAgwIAOgRQAcAOAWARIgOAUQgXgUgbgOgAKwgaIgDgJQgZAEgjADQgGAAgDACIgCAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIgDgRIARAAQAHgNAEgPIAFgOIATAEQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgCACgCAEIgMAYIAggDIgIgMIgBgCIACgCIAJgFIACgBIACACQAKANAMAXIABABQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAIgOAHIgCgCgAi4g3IAKgQQAeAKASAMIgLATQgSgOgdgLgANjg1QAZgCAbAAIAaABIAAAUIgcgBQgYAAgaACgAFehWIANgEQAIAOAGATIgNAFQgFgTgJgPgAnag1IAAgSIBtAAIAAASgAqmhbIANgDQAIAPAGAQIgNAFQgGgTgIgOgAF1hcIANgEQAJAPAFARIgMAFQgGgTgJgOg");
	this.shape.setTransform(-97.65,268.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt4, new cjs.Rectangle(-209.2,259,223.1,19.5), null);


(lib.txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AM0A0IASgNQAYASASAaIgUAOQgPgZgZgUgAEgA0IARgNQAZASASAaIgVAOQgPgZgYgUgAKbBeIgCgBIAAgBIAAhVQgNAPgOALIgEADQgBgBgDgEQgFgGgFgFQAlgXASgmIgyAAIgCAAIAAgCIAAgPIAAgCIACAAIA7AAIACgJQAEgLAAgIIAUADQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIgCAEQgDADgBAGIgDAJIBdAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAPQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAIhkAAIgJARIBSgBIACABIAAACIAABcQAAAMgGAFQgEADgHACIgTABIgGgBIgBgGQgDgIgCgFIATAAQAEAAACgBQACgCAAgEIAAgNIhCAAIAAAnIAAABIgCABgAKuAlIBCAAIAAgOIhCAAgAKuAGIBCAAIAAgMIhCAAgAJDBbQgggRgUgZIgCgCIADgCIAOgIIACACQAWAYAgAMQgFAFgFAIQgDAFgBAAgAGwBYQgEgHgGgFQAdgLAQgRQAGgGADgFIARAIQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAACgCACIgHAFQgQATgdAPIgEACQgCgBgDgEgAmhBPIAAiYIAWAAIAACHQAagKATgVQASgTALgZIARAPQgRAkgbAVQgVASgiAMgArXBJQAqgLATgXQAQgTACggIhfAAIAAgTIB3AAQgDA8gaAcQgUAWgsAKgAocBYIAAh1Ig+AAIAAgTIA+AAIAAggIAWAAIAAAgIA/AAIAAATIg/AAIAAB1gACKBDQA3gMAbglQAVgcAFgvIAWALQgKA3gcAgQgdAhg0ANgAiPBCQAzgKAbgbQANgOAKgUQAIgVAFgWIAUALQgGAagLAVQgKATgMANQgfAgg2ALgAARBUIAAgRIBFAAIAAgoIhCAAIAAgSIBCAAIAAgfIhFAAIAAgSIBaAAIAAB8gAtvBOIAAgTIBSAAIAAhnIhSAAIAAgUIBpAAIAACOgApeBAQAVghAIgqIAUAHQgGAagHATQgGARgKARgAn1gDIAUgHQANAtAQAcIgVALQgPgegNgvgAJWAfIivAAQAAgBAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgQQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAsAAIAAglIghAAIgCgBIgBgCIAAgPQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAhAAIAAgKIAAgdIAVACQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIgCAFQgBACAAASIAAAKIArAAIAAgKQAAgSgBgLIAVACQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIgCAFIAAAUIAAAKIAkAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAPIgBADIgCAAIgkAAIAAAlIAuAAIACAAIABACIAAAQIgBACIgCAAgAHoALIArAAIAAglIgrAAgAkdANIAAgUIByAAIAAAUgAiZgMIAKgRQAhAMARAKIgLARQgRgKgggMgACIgwIAOgRQAcAOAVASIgOAUQgXgVgagOgAiHg3IAKgQQAeAKASAMIgLATQgSgOgdgLgAnvhYIANgEQAIAOAHAUIgNAEQgGgTgJgPgArag2IAAgSIBfAAIAAASgAnVhcIAMgEQAJAPAGARIgOAFQgFgTgIgOg");
	this.shape.setTransform(-117.85,255.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-205.8,246,176,19.399999999999977), null);


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhRA0IARgNQAZASARAaIgUAOQgPgZgYgUgADpBJQAfgGAOgSQAIgJADgOQACgNAAgVQAAgagCgqIAVgBQACAfAAAnQAAAbgEAPQgDANgHALQgJAMgMAGQgMAIgUAFgAPuBRQgJgIAAgNQAAgPAOgJQALgGAQAAQAIgBAHACQgCgQAAggIAUAAQAAAhACATQAVAJARAPIgLATQgPgQgMgHIAAAFQAAAPgLAHQgKAHgRAAQgUAAgJgIgAP3A8QAAAMAUAAQATAAAAgQIAAgBIAAgGQgHgDgIABQgYAAAAANgAlfBRQgIgIAAgNQAAgPANgJQALgGAQAAQAJgBAGACQgBgQAAggIATAAQAAAhACATQAVAJARAPIgLATQgPgQgMgHIAAAFQAAAPgLAHQgKAHgRAAQgTAAgKgIgAlVA8QAAAMAUAAQASAAAAgQIAAgBIAAgGQgGgDgJABQgXAAAAANgAjKBFIADAAQAmAAAUgKQARgIAAgUQAAgMgIgHQgHgGgMAAQgXAAgRATQgJALgCAGIgUgDIAIhXIAUACIgHA2IgCAMIAGgJQAUgVAbAAQAYAAANAMQALAMAAAUQAAAQgIALQgGAJgNAGQgVALgtABgAu0BIQAvgRAWggQgOgNgYgLIAMgPQAXALAOAJQAKgTAFgcIg0AAQgQAigYAVIgSgMQASgOANgYQALgVAFgYIAXAGIgFAQIA1AAQgGgQgGgLIANgEQAGALAIAWIgIACIAIAJQgMA9gZAeQgWAbgtASgAJmBCQgsAHhCAIIgFgVIAOgBQAWg9AShKIAWAGQgRA/gXBAIBIgIQgKgZgOgYIATgHQAWAlATAwIgWAKgAsYBDQA3gMAbglQAUgcAGgvIAVALQgJA3gcAgQgdAhg1ANgANoAcQgZAigvAZIgNgSQApgSAZgkQAVgbAHglIhRAAIAAgTIBdAAQAFALADAKIAFgBQgJAhgOAYQAXAZAXAoIgVANQgPgggVgbgAGqAbQgaAlgtAXIgNgSQAogSAZgkQAVgbAIglIhRAAIAAgTIBnAAIAFAIQgJAogQAdQAXAaAXAnIgVANQgQghgVgbgAA+BNQgIgHAAgOQAAgQANgJQALgHAQAAIARABQgDgdgChOIAWAAIAAApQAfgBAVgCIAAASQgZACgaABQABAeACAVQAeAJAbAYIgOASQgVgYgUgIIAAAHQAAAhgrgBQgTABgKgKgABNAuQgFAEAAAFQAAAOAUAAQAWAAAAgRIgBgJQgJgCgKAAQgLAAgGAFgAwiBQQgKgGAAgSIAAg0IgrAAIAAgRIArAAIAAgmIglAAIAAgSIB2AAIAAASIg7AAIAAAmIBBAAIAAARIhBAAIAAAyQAAAGAEADQAEACAOAAQAWAAARgCIAAAVQgTACgUgBQgZAAgJgFgAn8A+QgTgTAAgfQAAghAVgUQAUgWAgABQAUAAAOAFIAAAYQgOgJgSAAQgWAAgOAOQgPAPAAAYQAAAWAOAPQANANAVAAQAUAAAPgKIAAAWQgQAJgYAAQgegBgSgTgAp6BPIAAiLIAqAAQAYAAANALQAOALAAAVQAAATgOANQgOANgYAAIgSAAIAAAzgApjAKIAPAAQAPgBAHgGQAIgHAAgMQAAgZgcAAIgRAAgAO9AyQAXgpALgoIgfAAIAAgRIAjgBQAEgNACgUIAWAEIgHAcIAbgCIAAASIgfACQgNAtgXAugAmQAyQAXgpAMgoIggAAIAAgRIAkgBQADgNADgUIAVAEIgGAcIAagCIAAASIgfACQgNAtgWAugADagHQAAgYAFguIAVACQgHAqAAAdIAAAOQAFgMAIgRIAMAKQgKAPgFAOIgDANIgWABQgEgUAAgVgAKTANIAAgUIBxAAIAAAUgAsagwIANgRQAcAOAWASIgOAUQgXgVgagOgAQegoIAJgQQAeAKATANIgKASQgUgPgcgKgAkvgoIAJgQQAfAKATANIgLASQgUgPgcgKgAikg6QgRgFgQgEIAJgQQAQADAUAFQARAFAMAGIgKASQgMgGgTgGgAN+hXIANgEQAHAOAHATIgNAFQgFgTgJgPgAOWhbIAMgEQAJAPAGARIgOAFQgGgTgHgOgAtAhcIAMgEQAJAPAGARIgNAFQgHgTgHgOg");
	this.shape.setTransform(-91.475,242.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-202.7,232.5,222.5,19.400000000000006), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOQBUQgIgJAAgLQAAgMAKgJQAIgHALAAQANAAAJAJQAHAIAAALQAAANgJAJQgIAHgMAAQgMAAgJgJgAOZA1QgEAFAAAGQAAAIAFAFQAFAEAGAAQAIAAAFgFQAEgFAAgHQAAgHgFgFQgFgEgHAAQgHAAgFAFgAofBaIgDgEQgDgHgGgGQAbgDASgJQAGgDAEgDIghAAIgCAAIAAgCIAAhTIAAgCIACAAICFAAIACAAIAAACIAABTIAAACIgCAAIhjAAQAHADAIAGIADADQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgIADQgTAMgaAGIgEAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAgAoCAnIBfAAIAAgKIhfAAgAoCAQIBfAAIAAgKIhfAAgAoCgHIBfAAIAAgJIhfAAgAmNBaQgfgHgWgPIgBgCIACgCIAMgIIADgBIABABQAXANAgAEQgFAFgFAIQgDAFgCAAIgEgBgAJKBaIgRAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhkIgLAPQgBABAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBQgDgKgEgGQAWgaANgmQADgIAAgGIATAFQABAAAAABQABAAAAAAQABABAAAAQAAAAAAABIgCAEQgCABgCAHIgKAYIABCIIgBACIgBAAgAGwBaIgCAAIAAgCIABhSIgIAJIgDACQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAQgCgHgEgGIAABBIAAACIgCABIgNAAQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBIAAgHIgPAAIAAAQIgBACIgCAAIgNAAIgCAAIAAgCIAAg/IgIALQAAABgBABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgCgMgDgGQAWgYAHgqIgVABIgCgBIgBgCIAAgOIABgCIACAAIA+AAIACAAIABACIAAAHIAlABQADgNABgKIASADQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIgCAEIgEALIgBACIA1gBIACABIAAABIAAAeIAAACIgCAAIgOAAIgCAAIAAgCIAAgPIgqAAQgGAPgIANIAUAAIAEgJQACgHABgGIAQAEQABAAABABQAAAAABAAQAAABABAAQAAAAAAABIgCADIgEAGIgDAGIAdgBIACABIAAACIAAAMIAAABIgCABIgggBIAAAPIAdgBIACABIAAABIAAALIAAACIgCABIgdgBIAAAPIAdAAIACAAIAAACIAAALIAAACIgCAAIgdAAIAAAPIAmAAIABAAIABACIAAANIgBACIgBAAIhPAAIAAAHIAAACIgCAAgAHABAIAYAAIAAgPIgYAAgAF8AqIAPAAIAAgsIgPAAgAHAAiIAYAAIAAgPIgYAAgAHAAFIAYAAIAAgPIgYAAgAGcgTIAAACIAAARQAYgWAMgfIgQAAIAAAQIgBACIgBAAIgOAAIgCAAIAAgCIAAgXIgWgBQgEAWgJAUIAfAAIACAAgAqTBaIgRAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIABgnQgYAXgpANIgEABQgCAAgDgFQgEgIgEgEQApgKAXgSIg5ABIgDgBIAAgBIAAgMIABgCIACgBIBKABIAAgLIg4AAIgBAAIgBgCIAAgLIABgCIABAAIA4AAIAAgKIhAABIgCgBIgBgBIAAgMIABgCIACAAIAnAAIgHgNIAAgBIACgCIANgEIg5ABIgDgBIAAgBIAAgNIABgCIACAAIAaAAQgEgHgHgKIgBgBIACgCIAMgGIACAAIACABQAJAKAEAJIABACIgCACIgFACIASAAIAAgNIgBgRIATABQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIgBAEQgBADAAAIIAAANIAQAAIAAgNQAAgMgBgFIATABQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIgBADQgBADAAAIIAAANIAMAAIAJgQIAEgLIATAFQABABAAAAQABAAAAAAQAAABABAAQAAAAAAABIgCADIgEAEIgIAMIAcAAIACAAIAAACIAAANIAAABIgCABIg8gBIAQAEQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgDAFIgDAGIAoAAIABAAIABACIAAAMQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIhEgBIAAAKIA8AAIACAAIAAACIAAALIAAACIgCAAIg8AAIAAALIBOgBIACABIAAACIAAAMIAAABIgCABIg9gBQAYARArAJQgFAGgDAHQgCAFgCAAIgFgBQgogLgbgYIABAnIAAACIgCAAgAq0grQAGAJADAJIAhAAIAFgMIADgIIgzAAIABACgAunBaQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIABhLIgMAKIgEADQgCAAgBgEQgCgKgEgEQAWgRAQgZIAGgLIAOAKQABAAAAABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAQgDADgDAEIgIANIAABhQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAgAJkBaIgCgBIAAgBIAAg6QAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIBkAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA5QAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgRAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgGIg/AAIAAAHIAAABIgCABgAJ2BAIA/AAIAAgTIg/AAgAgpBZQgegUgZgLQgcAWg2AIIgEAAIgDgBIgCgEQgDgIgEgGQAygEAagQIgdgJIgFAGIgDACIgDgBIgMgFIgCgCIABgCIAJgMIAPgYIgtAAIgCAAIgBgCIAAgOIABgCIACgBIA2ABIAFgKQAFgLACgJIAVAFQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAQgCACgDAGIgFALIBggBIACABIAAACIAAAOIAAACIgCAAIgmAAQgJAZgOARQAXAJAeAQIABACIgBADIgKAOIgCABgAiKAYQAVAFARAHQANgOAHgUIgtAAgAuHBVQgGgHgGgEQAMgOAGgVQAFgPACgVIAAgNIASACQAFABAAACIgCADIgFAgQAIARAPAIIAAhUIgtABQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgQQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIA7AAQAHgMAHgRIADgMIAUAFQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAIgCAEQgCABgCAFIgMAXIAhAAIACAAIAAACIAAAQQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAIgwgBIAAAfIAmAAIACAAIABACIAAAPIgBACIgCABIgmgBIAAAqQAOADAUAAIAXgBQgEAHgBAIQAAAFgCABIgFABIgPgBQg+gBgRgjQgGAUgLAPQAAABgBABQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAgDgEgABABRQgJgFAAgPIAAhMIgBgXIAVACQAFABAAACIgBAEQgCADAAALIAABFQAAAGAEACQAEACANAAQAPAAAEgEQAEgDABgHIABgWQAGADALADIAEACIABACIAAADQgBARgDAIQgCAHgFAEQgGAFgJACQgJACgNAAQgaAAgHgFgAMKBKQgJgHAAgPQAAgOALgLQALgLAagMQgBgJgCgDQgDgDgFAAQgJAAgNALQgJAHgNAPIgPgNQAbgaAOgcIgkAAIAAgRIAsAAIAIgaIAUADIgIAWQAdgBAXgCIABARIg9AEQgHANgJAKIgEAEIAAABIAFgEQAIgFAJAAQAKAAAHAGQAGAGACAKIAogSIAIATQgbAIgUAJIAAAnIgTAAIAAgeQgSAJgGAHQgFAFAAAHQAAAIAHADQAIADAUAAQAXAAAdgCIABASQgbACgcAAQggAAgLgJgAlcAQQAAgUAEgfQADgYAEgUIAVACQgFAXgEAdQgCAZAAARQAAAkAEAbIgVACQgEgeAAgkgADfBHQgOgLAAgWQAAgdAkgWQgIgcgHgqIAVgCQAFAjAHAaIAugYIALASQgsASgXAPQgMAJgGAKQgFAIAAAJQAAAMAKAGQAJAFAUAAQAaAAAZgCIAAAUIgwACQgjAAgOgLgAkpBDQgKgJAAgQQAAgKADgKIATACQgCAIAAAHQAAAJAGAEQAGAEAMAAQAVAAAWgDIAAAVQgSACgXAAQgZAAgLgJgAATA5IgOgHIgDgCIAAgCQAOgcAFgjQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIADABIAOADQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABIAAABQgFAhgOAiQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgACjAwQgIghgSgdIAAgBQAAAAAAgBQAAAAAAAAQABAAAAgBQABAAAAAAIAPgGIACgBIACACQARAbAKAhIAAABIgDADIgPAHIgCABQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAgBgALDARIhbAAIgCAAIAAgCIAAgNIABgCIABAAIBbAAIACAAIAAACIAAANIAAACIgCAAgAJogJQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgNIABgCIABgBIBbAAIACABIAAACIAAANQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgrgaIgCAAIAAgCIAAgXIh7AAIAAAXIgBACIgCAAIgQAAIgCAAIAAgCIAAgoQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIBEAAIAAgCQAAgNgBgGIAVABQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABIgBAEQgCACAAAKIAAACIBIAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAoIAAACIgCAAgAu3gmQgDgGgGgGQAUgMAQgUIAGgJIAPAJQABABAAAAQABABAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQgDABgDAEQgQATgTAPIgEADQgCAAgCgFgALXglIh/AAIgBAAIgBgCIAAgOIABgCIABAAIB/AAIACAAIABACIAAAOIgBACIgCAAgAksg5QAZgCAbAAIAaABIAAAUIgbgBQgZAAgaACgAoKgpIgCgBIAAgCIAAgnIABgCIABAAIBvAAIACAAIAAACIAAAnIAAACIgCABgAn3g5IBJAAIAAgMIhJAAgABygrQgbgSgbgKIgCgBIABgDIAIgMIADgCIABAAQAfAKAYAQIABACIgJAQIgCADIgCgBgAtlg0QgGgPgJgLIgBgCIACgCIANgGIACgBIACACQAJALAHAOIAAACIgCACIgNAGIgDABgALFhCIhdAAIgCAAIAAgCIAAgNIAAgCIACAAIBdAAIACAAIAAACIAAANIAAACIgCAAg");
	this.shape.setTransform(-106.675,229.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-202.9,220.4,192.5,18.599999999999994), null);


(lib.title2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArbB7IgCAAIgBgCIAAhwIABgDIACAAIDVAAIACAAIABADIAABXQAAAOgHAFQgEAEgGACIgUAAQgHAAgBgBIgCgHQgCgLgEgHIARABQAHABAAgJIAAg6IihAAIAABbIAAACIgDAAgAjcBOQAAgPANgLQAMgJARAAQAVAAAOANQANALAHAUQAWgIAAgjQAAgVgOgLQgMgKgTAAQghAAgeAaQgNALgLANIgVgTQBJhJArgnQguAEgpAAIgBgZQAwABBEgEIANAUIhOBGIgKAIIABABIANgIQAOgFAOgBQAjABATASQARAQAAAcQAAAmgbATQgXAQgqAAQg4AAAAgogAjABEQgFAEAAAGQAAATAgAAIAQgCQgDgRgJgIQgHgHgKABQgJgBgFAFgAGJBeQA4gOAZgfQAWgaADgrIiAAAIAAgaICgAAQgDBQgjAnQgcAdg7AOgAl8BcQBIgJAAg+QAAgcgMgRQgJgQgQgCQgPBJgXAkQgWAigeAAQgSAAgLgPQgKgPAAgeQAAgtAgggQgGgXgFgkIAagEIAHAvQAYgOAcgBIAGgoIAdAEIgHAlQAfAHAPAYQAOAXAAAhQAAAugbAYQgVARgoAIgAnCAnQAAAlAPAAQAPgBAOgSQgSgfgLgjQgPAWAAAagAmfgeQAIAhAPAbQALgdAKguQgYABgUAOgAgZBfQAngRAOgWQAMgTABglIhRAAIAAgZIBRAAIAAgpQgXAEgjADIgMgYQBPgGA7gUIAPAZQgXAHgeAGIAAAuIBEAAIAAAZIhEAAQAAAvgVAcQgSAYglAQgAI7AYQAAgbAFgqQAEghAGgbIAdACQgIAggEAoQgEAgAAAXQAAAyAHAlIgdACQgGgpAAgwgAChBdQAlgaAOgjQAMgbACguIg6AAIAAgZIA6AAIAAgtIAfAAIgBAtIBQAAQAABdgGAuQgDAXgLAIQgGADgMACQgLACgYAAIgJgdIAlAAQAFgCACgDQACgEABgJQAFglAAhEIgyAAQgEA9gTAkQgQAggkAZgAqjBpIgDAAIAAgCIAAg7IAAgCIADgBIBkAAIADABIAAACIAAA5IAAADIgDAAIgUAAIgDAAIAAgDIAAgGIg3AAIAAAIIAAACIgDAAgAqNBNIA3AAIAAgRIg3AAgAKABcQgNgLAAgWQAAgNADgOIAbACQgDALAAAKQAAAMAJAGQAHAEARAAQAcAAAdgDIAAAcQgXACghAAQghAAgPgMgAq0gGIgCAAIgBgDIAAgzIABgDIACAAICHAAIADAAIAAADIAAAzIAAADIgDAAgAqcgZIBXAAIAAgSIhXAAgAJ8hLQAigDAlABIAjABIAAAaQgOgBgXAAQgiAAgjACgArkhLIgDgBIAAgCIAAgTIABgDIACAAIBkAAIAAAAQAAgPgCgHIAdABQABAAABAAQAAAAABABQAAAAAAAAQABABAAAAIgCAGQgBAEAAAJIAAAAIBnAAIADAAIAAADIAAATIAAACIgDABgAGEhMIAAgaICBAAIAAAag");
	this.shape.setTransform(33.675,9.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title2, new cjs.Rectangle(-40.7,-2.4,148.8,24.7), null);


(lib.logomc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmyPUQjHhPiWiRQiYiRhSi/QhVjGAAjeQAAjbBWjFQBTi/CXiSQCYiRDIhQQDOhSDkAAQDkAADMBRQDGBPCWCRQCYCRBSC/QBVDGAADdQAADbhVDGQhUC/iXCSQiYCRjIBQQjNBSjkAAQjkAAjMhRgAmJmfQiZCiAAD9QAADzCgCoQCgCnDmAAQDrAACbikQCZikAAj6QAAjyifioQiginjmAAQjtAAiaCig");
	this.shape.setTransform(134.9368,5.4025,0.0598,0.0598,-89.9562);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmzPUQjGhPiXiRQiXiRhSi/QhVjGAAjeQAAjbBVjFQBTi/CZiSQCYiRDHhQQDOhSDkAAQDjAADNBRQDGBPCXCRQCXCRBSC/QBVDGAADdQAADbhVDGQhTC/iZCSQiYCRjHBQQjOBSjkAAQjjAAjNhRgAmJmfQiZCiAAD9QAADzCfCoQCgCnDnAAQDsAACaikQCZikAAj6QAAjyifioQiginjnAAQjtAAiZCig");
	this.shape_1.setTransform(134.9566,-20.5555,0.0598,0.0598,-89.9562);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AudU1MAAAgppII7AAMAAAAhkIUAAAIAAIFg");
	this.shape_2.setTransform(133.0712,45.5904,0.0598,0.0598,-89.9562);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AmFPXQjQhNiaiPQiaiPhSjBQhUjFAAjmQAAjeBSjFQBRjACUiRQCUiRDFhOQDLhRDjAAQD/AADPBWQDPBVCOClQBhByA/CSQA+CSAYCnI2gJVQCpCnEdAAQCmAAB5grQCAguCtiBIFlESQiOCkkFBvQkRB1kWAAQj6AAjYhOgAjgouQhvA1hJBiQhFBegeB1QgiCDATCUIPYmXQg9iFhvhLQh1hQiUAAQiIAAhxA2g");
	this.shape_3.setTransform(134.9169,33.3179,0.0598,0.0598,-89.9562);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ak0QCMgNNggDIKEAAIH9V1IH911IKFAAMgNNAgDg");
	this.shape_4.setTransform(134.9467,-7.5802,0.0598,0.0598,-89.9562);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AHWQTIAAyPQAAjCiWh8QiLh0i5AAQjWAAiECKQh3B+AACqIAASPIozAAMAAAggEIIzAAIAAEnQB3ieC9hZQCvhSC6AAQFxAADpDnQDnDkAAFkIAAT3g");
	this.shape_5.setTransform(134.8243,19.5141,0.0598,0.0598,-89.9562);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E1140A").s().p("Eh8/AprMAAAhTVMD5/AAAMAAABTVg");
	this.shape_6.setTransform(133.835,12.0548,0.06,0.06,-89.9417);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgRAMgXALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_7.setTransform(-24.336,513.5403,0.2765,0.2756);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgQAMgYALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_8.setTransform(-30.3506,513.5403,0.2765,0.2756);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag/CeQgXgFgQgHIAAhIQAUAOAXAIQAWAIATAAQAZAAALgHQALgHAAgQQAAgPgMgKQgNgLgggNQgogRgRgUQgRgVAAghQAAgqAhgbQAhgbA0AAQAPAAAWAEQAQADASAGIAABGQgQgKgSgHQgUgHgSAAQgVAAgLAIQgLAIAAAPQAAAPAJAJQALAJAgAOQAtARARAVQARAWAAAfQAAArghAbQgiAbg4AAQgRAAgagFg");
	this.shape_9.setTransform(-38.7642,515.3592,0.2765,0.2756);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA/CbIg+jfIAAAAIhADfIhNAAIhak1IBMAAIA6DtIABAAIBFjtIBEAAIA9DuIACAAIA4juIBGAAIhbE1g");
	this.shape_10.setTransform(-48.5051,515.3592,0.2765,0.2756);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhzB4QgrgrAAhJQAAhMAsgtQArgsBMAAQBJAAApArQAoArAABKQAABLgrArQgrAthLAAQhHAAgqgqgAg8hJQgWAaAAAxQAAAwAWAaQAWAZAoAAQAnAAAWgZQAUgaABgyQAAgxgWgaQgWgZgmAAQgoAAgWAbg");
	this.shape_11.setTransform(-59.6633,515.373,0.2765,0.2756);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhzC+QgjgoAAhHQAAhMAmguQAnguBAAAQAcAAAXAKQAXAKAMASIACAAIAAizIBIAAIAAHIIhIAAIAAgpIgCAAQgQAXgZALQgaAMggAAQg7AAgigpgAg1gCQgVAcAAAzQAAAvAUAZQAVAZAiAAQAiAAAWgaQAWgaAAgqIAAghQAAghgVgVQgVgXggAAQgmAAgUAcg");
	this.shape_12.setTransform(-69.6393,513.4025,0.2765,0.2756);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("ABCCeIAAisQAAgqgPgVQgOgVggABQgeAAgTAXQgVAXAAAjIAACuIhIAAIAAk1IBIAAIAAAqIACAAQARgZAZgLQAYgMAhAAQAxAAAbAgQAaAfAAA/IAAC9g");
	this.shape_13.setTransform(-79.0692,515.2696,0.2765,0.2756);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgkDdIAAk1IBIAAIAAE1gAgfiUQgNgLABgSQgBgSANgMQAOgNARAAQATAAAMANQANANABARQgBASgNAMQgMAMgTAAQgSAAgNgNg");
	this.shape_14.setTransform(-85.865,513.5403,0.2765,0.2756);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABaDYIhXlFIgCAAIhVFFIhaAAIh4mvIBRAAIBVFVIABAAIBelVIBPAAIBYFUIACAAIBRlUIBOAAIh1Gvg");
	this.shape_15.setTransform(-95.9378,513.6712,0.2765,0.2756);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_16.setTransform(-114.8182,518.8798,0.2765,0.2756);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_17.setTransform(-125.2643,518.8798,0.2765,0.2756);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_18.setTransform(-114.8182,508.4695,0.2765,0.2756);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_19.setTransform(-125.2643,508.4695,0.2765,0.2756);

	this.instance = new lib.Bitmap8();
	this.instance.setTransform(-130,433);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logomc, new cjs.Rectangle(-130,-35.9,279.9,559.5), null);


(lib.CTAmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAGBJQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgvIABgBIAqAAIABABIAAAtQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgHAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgGIgaAAIAAAIQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAgAAOA3IAaAAIAAgYIgaAAgABcBIQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgnIghABQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgHQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAhABIAAgZIgbAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAIAAgIQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAIAbAAIAAgVIgeAAIgBgBIAAgHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAoAAIALgYIACgIIAJAEQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIgCABIgNAZIAbAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABAAAAIgkAAIAAAVIAeAAQABAAAAABQAAAAAAAAQABAAAAAAQAAAAAAAAIAAAIQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgeAAIAAAZIAngBQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAIgngBIAAAnQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAEaAJQgFgFAAgEQAAgFAEgEQAbgbAZgeIAKAHQgYAcgaAaQgEACAAADQAAACAFADQAcAWAdAhIgLAIQgZgeghgdgAjeA6QAhgBAOgIQAJgEADgGQAEgGAAgJQAAgKgHgGQgHgGgKAAQgTAAgPAQQgGAHgDAIIgMgCQABgYAEgwIAMACIgFAwIgCAIIAEgFQAIgKAMgEQAJgFALAAQASAAAKAJQAJAJAAAOQAAAOgGAHQgEAHgJAGQgIADgRAEQgNABgOABgACwA8QgHgIAAgSIAChjIAMAAIgDBiQAAAOAGAFQAFAFAMAAQASAAALgLQAJgKAFgVIALAGQgLAugqABQgUgBgIgHgAlPA8QgOgIAAgQQAAgQAPgJQALgGAQAAQAVAAAKAHQgQgQgLgZQgUACgaAAIgBgKQAWABAUgDQgFgNgEgPIAMgBQAEAQAFAMQARgCARgEIABAKIgfAGQAMAZATAUIgHAKQgSgLgVABQgPgBgJAIQgHAGAAAHQAAAWApAAQAMgBAKgCIAAAMQgKABgMABQgZAAgNgIgAh6AOQAAgbAJgyIAMABQgJAwAAAcQAAAdAEAWIgMABQgEgYAAgcgAhRA3QgIgGAAgMQAAgJACgJIALACQgCAHAAAHQAAAIAGADQAFAEAMAAQARgBAPgBIABAMIgfAAQgVAAgHgFgAAHAJQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBAAAAIAnAAQABAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAgAAHgLQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgHQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAnAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAHQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAgAAAghQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgGQAAAAAAgBQAAAAABAAQAAAAAAAAQAAgBABAAIA0AAQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAgAhUgtQAVgBAUAAIAUAAIAAALIgVAAQgUAAgUABgAjag7IAFgJQAfAFATAJIgGAKQgUgJgdgGgABPguQgEgKgHgKIAAgBIACgBIAEgDIABAAIABABQAHAJAFALIAAABIgCABIgEACIgCAAgAAGg4QAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAIAAgHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIArAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHIgBAAg");
	this.shape.setTransform(-26.325,341.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgPgeIAeAeIgeAf");
	this.shape_1.setTransform(21.5824,340.4703,1.3499,1.3499);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0075D4").s().p("AmPB/QgeAAAAgdIAAjDQAAgdAeAAIMfAAQAeAAAAAdIAADDQAAAdgeAAg");
	this.shape_2.setTransform(-19.6295,340.5178,1.3499,1.3499);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTAmc, new cjs.Rectangle(-77.6,323.3,116,34.5), null);


(lib.commc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap11();
	this.instance.setTransform(-76,-36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.commc, new cjs.Rectangle(-76,-36,272,177), null);


(lib.bgmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap10();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bgmc, new cjs.Rectangle(-150,-300,300,600), null);


// stage content:
(lib._300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(270));

	// CTA
	this.instance = new lib.CTAmc();
	this.instance.setTransform(381.5,222.75);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(111).to({_off:false},0).to({x:242.5},12,cjs.Ease.get(1)).wait(147));

	// txt
	this.instance_1 = new lib.txt5();
	this.instance_1.setTransform(218.5,178.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(99).to({_off:false},0).to({x:233.5,alpha:1},12,cjs.Ease.get(1)).wait(159));

	// txt
	this.instance_2 = new lib.txt4();
	this.instance_2.setTransform(217.4,161.65);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(95).to({_off:false},0).to({x:232.4,alpha:1},12,cjs.Ease.get(1)).wait(163));

	// txt
	this.instance_3 = new lib.txt3();
	this.instance_3.setTransform(214.55,149.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(91).to({_off:false},0).to({x:229.55,alpha:1},12,cjs.Ease.get(1)).wait(167));

	// txt
	this.instance_4 = new lib.txt2();
	this.instance_4.setTransform(210.8,136.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(87).to({_off:false},0).to({x:225.8,alpha:1},12,cjs.Ease.get(1)).wait(171));

	// txt
	this.instance_5 = new lib.txt1();
	this.instance_5.setTransform(210.4,124.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(83).to({_off:false},0).to({x:225.4,alpha:1},12,cjs.Ease.get(1)).wait(175));

	// title
	this.instance_6 = new lib.title2();
	this.instance_6.setTransform(44.9,82.35);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(71).to({_off:false},0).to({x:59.9,alpha:1},12,cjs.Ease.get(1)).wait(187));

	// title
	this.instance_7 = new lib.txtTitle();
	this.instance_7.setTransform(70.25,58.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(67).to({_off:false},0).to({x:85.25,alpha:1},12,cjs.Ease.get(1)).wait(191));

	// logo
	this.instance_8 = new lib.logomc();
	this.instance_8.setTransform(150.05,58.75);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(46).to({_off:false},0).to({alpha:1},24,cjs.Ease.get(1)).wait(200));

	// com
	this.instance_9 = new lib.commc();
	this.instance_9.setTransform(91.5,620.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(19).to({_off:false},0).to({y:170.5},33,cjs.Ease.get(1)).wait(218));

	// bg
	this.instance_10 = new lib.bgmc();
	this.instance_10.setTransform(150,300);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({_off:false},0).to({alpha:1},33,cjs.Ease.get(1)).wait(218));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#05132A").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(270));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,299.5,270.4,462);
// library properties:
lib.properties = {
	id: '542CFFE83C13439EB4A04353E49F32EB',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap10.png?1632215820176", id:"Bitmap10"},
		{src:"images/Bitmap11.png?1632215820176", id:"Bitmap11"},
		{src:"images/Bitmap8.png?1632215820176", id:"Bitmap8"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['542CFFE83C13439EB4A04353E49F32EB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;