(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap10 = function() {
	this.initialize(img.Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,324,250);


(lib.Bitmap17 = function() {
	this.initialize(img.Bitmap17);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,312,206);


(lib.Bitmap18 = function() {
	this.initialize(img.Bitmap18);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,168,196);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtTitle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AreBfQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBAAAAAAIgBgGQgCgJgDgHIASACQAHAAADgDQAGgHACgrIgUAAIgCAIQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgJgBQgJgBAAgCIAAgCQAGgZABgWIABgLIAAgEQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAgAAIAAgaIgmAAIgCAAIgBgCIAAgPIABgCIACgBIA4AAIACABIAAACIAAA7IgBACIgBABIghgBIgDAXIAkAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAAABIgBAOQgCAugHAQQgDAIgHADQgGADgLAAgAoQBaQgHgIgGgEQAygWAPgoQAHgTACgXIg9AAIgCAAIgBgCIAAgRIABgCIACAAIA+ABIAAgTQAAgQgCgMIAZACQAEABAAACIgCAGQgBADAAAPIgBASIBJgBQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIgBATQAAA9gGAeQgDARgJAGQgIAFgPAAIgEABIgQgCQgGAAAAgCIgCgFQgCgLgEgFQAQACAPAAQANAAACgOQAGgfAAg0Ig1AAQgDAdgIAVQgJAZgRARQgPAPgWALIgFADQgCAAgDgFgApBBcIgGgOQglAGgtAGQgFABgEABIgDACQgDAAgBgEIgEgUIAygDIAAgaIgnAAIgCAAIAAgCIAAg3IAAgCIACgBIAnABIAAgSIgdACQgEAAgDACIgEABQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgDgSIAIAAIAIAAQAIgNAFgOQADgHABgHIAVADQABABAAAAQABAAAAABQAAAAABABQAAAAAAAAQAAABAAABQgBAAAAABQAAAAAAABQgBAAAAABIgEAFIgNAYIAsgCIgNgQIgBgBIACgBIALgHIACgBIACABQATATAOAWIABACIgCACIgMAIIgDABIgCgCIgGgLIgdADIAAATIApgBIACABIABACIAAA3IgBACIgCAAIgpAAIAAAXIAXgDIgGgJIAAgBQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIALgFIACgBIACACQANASAJAWIAAABIgCACIgMAGIgCAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBgApnAYIAXAAIAAgZIgXAAgAqQAYIAVAAIAAgZIgVAAgAFlBJQAZgFANgHQAPgJAGgPQAHgPAAgZIAAhOIAXAAIAABQQAAAtgVAWQgSASgnAHgAkWBSQgIgHAAgOQAAgQAOgJQALgHARAAQAJAAAHACQgCgRAAghIAUAAQAAAhADAUQAWAKASAQIgMAUQgQgRgMgHIAAAFQAAAQgMAIQgKAGgSAAQgVAAgKgJgAkMA9QAAANAVAAQAUAAAAgRIAAgBIAAgGQgHgDgJAAQgZAAAAAOgAK2BbIAAhSQgUAOgYAMIgNgSQA/gcAggsIATANQgQATgTAQIAABigAHuBKQAfgMAMgVQAFgKACgLQACgKAAgVIhAAAIAAgTICMAAIAAATIg1AAQAAAbgEAQQgCALgHAKQgHANgMAKQgKAHgRAIgABcAWIg/AJIgDgUIA+gJIgFgeIg0AGIgDgTIA0gHIgGgkIAXgDIAGAkIA1gGIACATIg0AHIAFAfIA3gIIADATIg3AIIAMBFIgXADgAhjBNQgJgIAAgTIAAhEIgiAIIgFgSIAngJIAAgwIAXAAIAAAqIBMgSIALAPQgIAcgLASQgKAQgPARIgTgNQAdgeAIgbIg9ANIAABJQAAAHACACQADADAGABQAGACAPAAQAcAAAXgDIAAAXIg3ABQggAAgKgIgAC8BRIAAgTIBHAAIAHhTIg+AAIAAgTIBWAAIgJBmIAeAAIAAATgAlJAzQAYgsAMgqIghAAIAAgSIAlAAQAEgOADgVIAWAEIgHAeIAcgDIAAATIghACQgNAwgYAwgAFaAYIAAhoIAXAAIAABogAjjgsIAJgRQAgALAUANIgLATQgVgQgdgKgAHvg5IAAgTIBzAAIAAATg");
	this.shape.setTransform(4.475,0.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txtTitle, new cjs.Rectangle(-70.6,-8.9,150.2,19), null);


(lib.txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHzAdQgCgDAAgDQAAgFADgDQADgCAEAAQAFAAACADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgEgEgAH3ATIgBAEQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAABIAEABQABAAAAAAQABAAAAAAQABAAAAgBQABAAABAAIABgEQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABgABlAdQgCgDAAgDQAAgFADgDQADgCAEAAQAFAAADADQACADAAAEQAAAEgDADQgDADgEAAQgFAAgDgEgABoATIgBAEQAAAAABABQAAABAAAAQAAABAAAAQABAAAAABIAEABQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIACgEQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBABgAiRAfIgCgGIAIAAIACgBIAAgFIgOAFIgCAAIgBgBIgDgEQAOgCAJgGIgVABIgBgBIAAAAIAAgFIAAAAIABgBIAdABIAAgEIgEAAIAAgBIgBgCIACAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBIAAgCIgGAAIAAAIIgBABIgFAAIgBgBIAAgIIgGAAIAAAEIABACIgBABIgBAAIgEAAIgBAAIAAgLIABgBIALAAIAAgDIgOAAIgCAAIAAgEIABgBIAFAAIgCgBIgDgBIAFgHIABgEIAFABIABABIAAABIgBACIAAAAIAEAAIAAgGIAGABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABIAAABIAAADIALAAIAAAAIABABIAAADIgBABIgLAAIAAADIAOAAIAAAFIgOAAIAAADIALAAIABABIAAAHIgBADIACAAIABABIgBABIAAADIAagBIAAABIABAAIAAAFIgBAAIAAABIgKgBIAFAEIAAABIAAABIgDABIgEADIAPAEIgEAEIgCACIgBAAQgTgGgHgOIgBAAIgGAFIAAAHIAOgCIgBAEIAAABIgCABIgVAEIgCABIgBAAIgBgBgAhwARIAGgDIABgDIgMAAQACAEADACgADnAgIgFAAIgBAAIAAgdIgGABIgCAAIgBAAIgBgBIgBgFIAFABIAFgGIgKgKIAAAAIAAgBIADgEIAAgBIABABIACACIAEgIIABgEIAGADIABABIAAABIgCABIgGAKIADADIAFgHIACgFIAFADIACABIgCABIgCADIgKAPIAIAAIgCgEIAAgBIABAAIACgCIABAAIABABIAFALIAAgcIAAgBIAgAAIAAABIAAA2IAAABIgGAAIAAgBIAAgDIgTAAIAAADIgBABIgGAAIAAgaIgBABIgEABIgBAAIAAgBIgBgDIgEABIAAAdIgBAAgAEGATIAHAAIAAgRIgHAAgAD6ATIAFAAIAAgRIgFAAgAEGgDIAHAAIAAgRIgHAAgAD6gDIAFAAIAAgRIgFAAgAC5AgIgBAAIAAgBIAAgPIgNAAIAAgHIANAAIAAgIIgLAAIAAAAIAAgEIAAgBIALAAIAAgHIgMAAIAAgBIAAgFIAAgBIASAAIAEgKIABgDIAGACIABABIgBABIgBACIgDAHIAKAAIAAABIAAAFIAAABIgQAAIAAAHIAMAAIACAAIAAABIAAAEIgCAAIgMAAIAAAIIAQAAIABAAIAAAHIgBAAIgQAAIABAPIgBABgACZAgIgGAAIAAgBIAAgWIAAAAIAUAAIACAAIAAAVIgBAAIgBABIgEAAIgBgBIAAAAIAAgCIgIAAIAAAEIgBAAgACaAWIAIAAIAAgIIgIAAgAgzAgIgBgBIAAgdIAAgBIAbAAIAAABIAAAcIAAABIgHAAIAAgBIAAgDIgMAAIAAAEIgBAAIAAABgAgsAVIAMAAIAAgNIgMAAgAhTAgIgBgBIAAAAIAAgdIAAgBIAZAAIABAAIAAAdIgBABIAAAAIgFAAIgBgBIAAgDIgMAAIAAAEIAAAAIgBABgAhNAVIAMAAIAAgNIgMAAgAkRAgIgGAAIAAgpIABgBIAXAAIABABIAAAhQAAAEgCACQgBABgHAAIgCAAIgBgCIgBgEIAFAAIACgBIAAgBIAAgGIgLAAIAAAPIgBAAgAkQAMIALAAIAAgGIgLAAgAkQABIALAAIAAgFIgLAAgAjxAfIgBgCQAAgBAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBIAHAAIADAAIAAgCIAAgXIAAgKIAHABIABAAIAAACIgBAHIAAAYQAAAFgDACIgDABIgHAAIgBAAgAHGAXIABAAQAOAAAGgEQAHgDgBgHQAAgEgDgCQgCgCgEAAQgIAAgGAGQgDAEgBADIgHgCIADgeIAHABIgDASIgBAFIADgEQAGgGAKAAQAIAAAFAEQAEADAAAIQAAAFgCAEQgDADgFACQgHAEgPABgAAwAXQAMgBAGgFQADgCABgEQgDADgFAAQgGAAgDgDQgDgDAAgFQAAgFAEgDQADgDAGAAQADAAACABIAAgHIgbABIAAgGIAbgBIAAgJIAHAAIAAAJIAQAAIAAAGIgQAAIAAAOQABADAAAFQAAAKgGAFQgGAFgMACgAA6gBQAAAAgBABQAAAAAAAAQgBAAAAABQAAABAAAAQAAABAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQADAAACgCIABgEQAAgFgGAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABgAmrAYQAJgCAFgDQAEgCADgFQACgFAAgIIAAgaIAIAAIAAAbQAAAOgIAHQgFAGgNADgAncAYQAIgCAEgDQAFgCACgFQACgFAAgIIAAgaIAIAAIAAAbQAAAOgHAHQgGAGgNADgAGTAXQARAAAEgDQAGgDAAgGQAAgIgJAAQgFAAgEACQgFADgEAGIgHgEQAFgKADgNIgLAAIAAgGIANAAIABgKIAIAAIgCAJIAVgBIAAAGIgXACQgCAKgFAHIABAAQAGgGALAAQAHAAAFAEQADADAAAHQABAJgJAFQgHADgSAAgAEfAGQAAgNAEgVIAHABQgEAUAAANQAAAKACAMIgHABQgCgMAAgLgAgDAGQAAgHAEgGQAEgGAGgEIADgBIAAgBIgDACIgaACIgBgHIAtgCIAAAGQgGABgFACQgPAIAAANQABAOAVACIgCAHQgagCAAgVgAi+AXQALgCAEgGQAEgFAAgIQAAgKgFgGQgDgEgGAAQgBAWgFAMQgCAFgDACQgDACgEAAQgFAAgDgGQgDgFAAgJQAAgNAIgIQAEgEAFgCQAEgCAGAAQAYAAAAAbQgBAVgWAFgAjKgLQgGAHABAKQAAAGACADQAAABAAAAQABABAAAAQABAAAAABQABAAAAAAIADgBIACgEQACgGABgJIACgQQgGABgEAGgAk3AIQgJANgQAIIgEgGQAOgHAJgMQAHgJADgNIgdAAIAAgGIAkAAIADACQgEAOgFAKQAHAJAIAOIgHAEQgFgLgIgKgAFaAPQAAgFADgGIAHACQgDAFAAAEQAAADADACQAEABAGAAIATgBIAAAIIgTABQgUAAAAgOgAEtATQAAgFAFgDQADgCAFAAIAGAAIAAgTIgTABIAAgHIASAAIAAgMIAIAAIAAAMIALgBIAAAGIgLABIAAAVQAHADAGAGIgFAGQgEgFgEgDIAAABQAAAFgDACQgDADgGAAQgOAAAAgKgAE1AQQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAEAIAAQAFAAAAgGIAAgBQgCgCgEAAQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBABgADZAaIgDgBQACgIABgGIAAgEIAFABIABABIAAABIAAACIgDANIgBACgADsAWIgCgNIAAAAIAAgBIADgBIABAAIAAABIAEAMIAAAAIgBABIgEABIgBABIAAgBgAj4ARIAAgQIAAgJIAHAAIABABIgBACIAAAGIAAAPIAAABgAmuAHIAAgiIAIAAIAAAigAngAHIAAgiIAHAAIAAAigACmAFIgLAAIgGAAIgBAAIAAgFIAAAAIASAAIABAAIAAAEIAAABIgBAAgAmBADIAAgGIAnAAIAAAGgAASgIIAEgCQAEAFACAGIgFACIgFgLgAhtADIgBgCIgCgEIAGABIACgBIABgCIAAgRIgBgJIAHAAIABABIAAACIgBAGIAAATQAAADgBABQgDACgGAAgAn3gGIgGAIIgEgCIAGgIIgJgCIACgFIAJADIgCgKIAHAAIgBAKIAIgDIACAFIgJACIAHAIIgFACgAAbgKIAEgCIAFALIgFABIgEgKgACmgDIgRAAIgBAAIAAgGIAAAAIASAAIABAAIAAAGIgBAAgAgjgEIgnAAIAAgZIAnAAIABAAIAAAZIgBAAgAhDgLIAZAAIAAgLIgZAAgAFogLIALgHIgJABIgMgBIAAgGIANAAIATgBIABAHIgHAEIgMAIgAhzgGIgBAAIAAgBIAAgOIgBgHIAHABIABABIAAABIAAAEIAAAOIAAABgACRgNIAAgFIAAgBIAZAAIAAABIAAAFgAkbgPIgBAAIAAgBIAAgFIABgBIARABIgEgHIAAgBIABgBIAEgBIABgBIAAABIAFAHIAAAAIgGADIAQAAIAFgHIABgEIAHACIABABIgBABIgCACIgDAFIASgBIABABIAAAFIAAABgAHTgVIgLgDIADgGIAMADIAKAEIgDAGIgLgEgAC0gTIgGgJIAAAAIABgBIAFgCIABAAIAAABIAFAIIAAABIgBAAIgFADIAAgBgACngXIgTAAIgBAAIAAgFIAAgBIABAAIATAAIACAAIAAABIAAAFIgCAAg");
	this.shape.setTransform(-1.05,-7.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt5, new cjs.Rectangle(-52.7,-11,103.4,6.6), null);


(lib.txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFaAsQgEgEAAgGQAAgHAFgEQAEgEAGAAQAHAAAEAFQAEAEAAAGQAAAHgFAEQgEAEgGAAQgHAAgEgFgAFeAcQgCACAAAEQAAAEADACQACACAEAAQAEAAACgCQADgDAAgDQAAgEgDgDQgDgCgDAAQgEAAgDADgAD3AwIgBgBIAAgBIAAgzIgGAHIgCACIgBgCQgCgFgCgDQAOgPAGgTIABgIIAKADIACACIgBACIgCAEIgGAOIAABFIAAABIgBABgAkDAwIgBgBIgBgBIAAggIABgBIABAAIAaAAIABAAIAAABIAAAfIAAABIgBAAIgIAAIgBgBIAAgDIgJAAIAAAEQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAgAj7AhIAJAAIAAgLIgJAAgAldAwIgJAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgzIgGAGIgBACIgBgCIgEgIQAMgOAHgTIACgIIAKADIABACIgBACIgCAEIgGAPIAABEIAAACIgBAAgAhxAtIgEgGQAMgDALgHIgDgJIgCgIIgQAAIgCALIAEgFIABAAIABAAIAKAGIAAABIAAABIgEAFIgBABIgBgBIgKgHQgDANgHAIIgCACIgCgCIgGgFQALgJABgTIgGAAIgBAAIAAgBIAAgHIAAgBIABAAIAeAAQgCgMgBgSIgEAEIgLAOIAIgBIgBgEIAAgBIAEgCIAAAAIABABIAEANIAAABIgBABIgDABIgBAAIAAAAIgBgDIgPACIgDABIgCAAIgBgBIgBgIIACAAIAIgIIgLgMIgBgBIABgBIAEgFIABAAIACACIAFgIIACgEIAHADIABABIgBABIgCACIgHALIAEAEIAFgJIAGADIAAgBIgBgRIAKABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBACIAAAGIAAAHIAEgFIABgBIABABIABABIAFgIIACgEIAHAEIABABIgBABIgCACIgHAKIADAEIAEgFIACgFIAHAEIABABIgBACIgDADIgMAOIAJgBIgCgEIAAAAIABgBIAEgCIABAAIABABIAFANIAAABIgBABIgEABIgBABIgBgBIgBgDIgIABIAGAEIAAAAIAAABIgDACIALAAIABAAIAAABIAAAHIAAABIgBAAIgNAAIAHAFIABABIgBACIgDACIgIAJQAEAFADAAQADAAABgLIAFADIADACIAAADQgCAIgCADQgDADgEAAQgIAAgHgKQgJAGgKADIgCABIgDgCgAhbADIAMAAIgGgDIAAgBIABgBIACgCIgDAAIgFACQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIgBgHIABAAIAHgHQgFgHgGgFQAAASAEAPgAiMAvIgIAAIgBgBIAAgtQgCALgFAJIgBACIgBgCIgEgIQAJgNAEgRIgBAAIgJAAIgBgBIAAgIIABgBIAKABIAAgIIgBgOIAKABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBACIAAAKIAAAIIAHgBIABABIAAAJIgBAAIgCAAIgFAAQADAIAGAJIgDAGQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgBgCIgEgKIABAvIAAADIAAABIgBAAgAjjAvIgBgDIgDgFQAOgBAIgDQgFgEgFgHIgFAAIgCABIgBgBIAAgBIAAgFIAAgBIABAAIAqAAIABgBIAEADIADAEIgBACIgDACIgJAIQAIACAOABIgDAGIgBACIgBABIgCAAQgPgCgKgEQgKAEgOACIgDAAIgBAAgAjHAfQAFgCAFgFIgTAAQAEAFAFACgAkxAvIgIAAIgBAAIAAgBIAAgfQgIAPgPAKIgDABIgCgCIgFgHQASgIAJgPIgWABIgBgBIAAgBIAAgHIAAgBIABAAIAcAAIAAgJIgUAAIgBAAIAAgBIAAggIAAgBIABAAIAyAAIABAAIABABIAAAgIgBABIgBAAIgUAAIAAAJIAdAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAABIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAIgXgBQAJAOARAIQgDADgBAFIgCACIgCgBQgQgKgIgPIAAAfIAAABIgBAAgAlEgSIAeAAIAAgPIgeAAgACgAtIgFgFQALgJAEgRIABgGIAIADQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIgBACIgBADIAAADIgBACQAEAHAGADIAAgbIgXABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgGIAAgBIABAAIA7AAIABAAIABABIAAAGIgBABIgBABIgZgBIAAAKIAUAAIABAAIAAABIAAAHIAAABIgBAAIgUAAIAAALIAPABIAOAAIgCAGIgBAEIgDAAIgHAAQgQAAgKgEQgJgDgFgIQgEAIgGAGIgCACIgDgCgACJAvIgCgBIgBgCIgCgIIAHAAIADgBIABgDIAAgUIgFABIgEACIgBABQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgCgKIAJgCIAEgBIAAgSIgMAAIgBAAIAAgBIAAgIIAAgBIABAAIAMAAIAAgGIgBgOIALAAIABABIAAADQgBABAAAJIAAAGIAJAAIABAAIAAABIAAAIIAAABIgBAAIgJAAIAAAQIAJgEIAAAGIgBADIgDACIgFACIAAAaQAAAIgDACQgDADgJAAIgBAAgAgvAvQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAg5IAAgBIABAAIAjAAIABAAIAAABIAAAuQAAAHgCACIgEACIgHAAIgDAAIgBgDIgCgGIAGAAQABAAAAAAQABAAAAgBQABAAAAAAQAAgBAAgBIAAgIIgRAAIAAAUIgBABgAgmASIARAAIAAgHIgRAAgAgmADIARAAIAAgGIgRAAgAFCAtQgLgIgJgNIAAgBIABgBIAGgEIABgBIABABQAJANAMAHIgFAGIgCACgAEJAsQgDgDgDgCQAKgGAHgJIADgHIAJAFIACABIgCACIgCADQgIAKgJAHIgCABIgCgCgAAAAsQgCgCAAgGIAAgaIgBgKIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAACIgBAGIAAAFQAJgDAHgFIAGgEIAHAHIABACQAAAAAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgFACIgXAKIAAAIQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAQACABAHAAQAIAAACgCIABgEIABgGIAHADIACABIABABIgBACIgBAIIgEADQgEAEgNAAQgNAAgEgCgABBAnQgEgEAAgIQAAgHAFgGQAGgFAOgHQAAgEgCgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgFAAgGAFQgFADgHAJIgIgHQAOgNAHgPIgSAAIAAgJIAXAAIAEgOIALACIgEAMIAbgCIAAAJIggACQgEAHgEAFIgDACIABAAIACgBQAFgDAEAAQAGAAADADQADADABAFIAVgJIAEAKIgYAIIAAAVIgKAAIAAgQQgKAFgDADQgDADAAAEQAAAEAEACQAFABAKAAIAbgBIABAKIgdABQgRAAgGgFgAEGAPIgBAAIAAgJIAAgBIABAAIAPAAIAAgUIgJAAIgCAAIgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgIIAAgBIABAAIAMAAIAAgFIgBgQIALABQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIgBACIAAAMIAAAFIAPAAIAAgFIgBgQIALABQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIgBACIAAAMIAAAFIANAAIABAAIAAABIAAAIIAAABIgBAAIgNAAIAAAUIARAAIABAAIAAABIAAAIIgBABgAEgAFIAPAAIAAgUIgPAAgAjeAOIgBgBIgBgBIABgTIgCACIgCABIgCgBIgEgFQAHgGAEgHIACgFIAIACIACABIgBABIgBACIALAAIACgGIAJACIABAAIgBACIgBABIAAABIASAAIABAAIAAAFIAAABIgBAAIgTAAIAAAEIAQAAIABAAIAAABIAAAEIAAABIgBAAIgQAAIAAAEIAQAAIABAAIAAABIAAADIAAABIgBAAIgQAAIAAAEIAVAAIABAAIAAABIAAAEIAAABIgBABgAjWAHIANAAIAAgEIgNAAgAjWgCIANAAIAAgEIgNAAgAjWgMIANAAIAAgEIgNAAgAkCAIIgBAAIAAgBIAAgHIAAAAIABAAIAXAAIABAAIAAAAIAAAHIAAABgAAAgFQgCgBAAgGIAAgZIgBgKIAKABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAACIgBAFIAAAGQAJgDAHgEIAFgEIAHAGIABACIgCABIgFACQgIAFgOAEIAAAGQAAABAAAAQAAABABAAQAAABAAAAQAAAAABABIAIAAQAJAAABgCIACgDIAAgGIAHADIACABIABACIAAABQgBAFgBACIgDAEQgEADgOAAQgMAAgEgCgAkCgFIgBgBIAAgHIAAgBIABAAIAXAAIABAAIAAABIAAAHIAAABgADYgIIguAAIgBAAIAAgBIAAgiIAAgBIABAAIAvAAIABABIAAAiIgBABIgBAAgAC0gQIAbAAIAAgHIgbAAgAC0geIAbAAIAAgGIgbAAgAgNgPIgCgFIggAEIgEABIgBAAIgCgCIgBgJIAJAAIAGgPIACgHIAKACIABACIgBACIgCADIgGAMIARgBIgFgHIAAgBIABgBIAFgDIABAAIABABQAGAHAFAMIABABIgBABIgHAEIgBgBgAkHgTIgBgBIAAgBIAAgHIAAgBIABAAIAgAAIABAAIAAABIAAAHIAAABIgBABgAjAgbIgBgBIgBgBIABgBIAAgDIgNAAIAAAEIAAABIgBABIgHAAIgBgBIAAgBIAAgBIAAgDIgNABIgBgBIAAAAIAAgGIAAgBIABgBIANABIAAgBIAAgHIAJABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAABIgBADIAAACIANAAIAAgBIgBgHIAJABQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIgBABIAAADIAAACIAOgBIABABIAAABIAAAGIAAABIgBAAIgOgBIAAAEIAAABIgBABgAjpgjIgaAAIgBAAIAAgBIAAgHIAAgBIABAAIAaAAIABAAIAAABIAAAHIAAABIgBAAg");
	this.shape.setTransform(-11.525,2.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-48.7,-1.9,74.4,9.8), null);


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjGAZIAJgHQANAKAJANIgKAIQgIgOgNgKgAkeAvIgBAAIgBgBIABg0IgJAKIgDACQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIgEgHQAQgPAIgVIACgHIAKADIACACIgBACQgBAAgCAEIgGAOIAABEIgBABgAnOAvIgIAAIgBAAIAAgBIAAgrIAAgBIABAAIArAAIABAAIAAABIAAArIAAABIgBAAIgIAAIgBAAIAAgBIAAgEIgZAAIAAAEIAAABIgBAAgAnNAiIAZAAIAAgIIgZAAgAnNASIAZAAIAAgHIgZAAgAlkAuIgDAAIgBgDIgDgIIAOABQAFAAACgEIACgMIgmAAIgEAFIgBABIgBAAIgIgCIgCgBIAAgBQAHgJAFgLIgYAAIgBAAIAAgBIAAgHIAAgBIABAAIBbAAIABAAIAAABIAAAHIAAABIgBAAIg3AAIgDAIIAsAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIgBALQgCAJgCAHQgCAFgEACQgDABgGAAgAj9ArQgDgBgBgDQgCgDAAgEIAAhCIAAgMIALABQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIgBACIAAAHIAAAbQAJgHAKgJIAGgHIAIAHIACACQAAAAAAABQAAAAgBAAQAAAAAAAAQgBABAAAAIgGAEQgNALgOAIIAAAZIAAAEIADACIAKABQAIAAADgDQACgCABgOQADADAFABIACABIAAADQAAAIgCAEQgBAEgDACQgFADgOAAQgOAAgEgCgAC/AkQAOgGAGgJQAFgJAAgOIAAgSIAMAAIAAAQQAAAUgJAMQgGAKgOAHgAA5AjQAOgEAHgGQAJgHAEgKQAEgKAAgSIgoAAIAAAXIgMAAIAAghIAaAAIAAgPIAMAAIAAAPIAbAAQAAAYgFAOQgEAPgKAIQgJAIgRAGgAFyAiIACAAQAUAAAKgFQAJgFAAgKQAAgGgEgEQgDgDgHAAQgMAAgJAKQgFAFgBAEIgKgCIAEgtIAKABIgDAcIgCAGIAEgFQAKgKAOAAQANAAAHAHQAGAFAAALQAAAIgEAGQgEAEgGAEQgMAGgXAAgAh4gCIAJgGQAKAIAIALQANgSAGgSIg2AAIAAgKIBCAAIADAFQgLAdgQAVIAMARIgLAHQgOgbgVgTgAHXAjQAQgEAHgJQAFgHAAgNQAAgPgGgIQgGgHgIAAQgCAigIASQgDAIgFADQgEADgFAAQgIAAgFgJQgEgIAAgNQAAgUALgNQAGgGAIgDQAHgDAIAAQAkAAAAApQAAAggiAHgAHFgRQgIAKAAAPQAAAKACAFQACAEADAAQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAQACgCABgEQAEgJADgNIACgYQgIABgHAJgAgJAnIAAhQIAKAAIAABDQAOgKAJgWIAIAJQgIAQgJAJQgHAIgMAHgAEoAqIgCgLIAJACIAGgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAEgJAAgWQAAgIgCgDQgBAAAAgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgJABQgIAggMAaIgLgEQANgaAHgcIgTACIAAgJIAVgCIAEgVIALACIgEATIAIgBQAIAAADAFQAEAFAAAKQAAAagDAKQgCAGgDADQgEADgGAAIgLgBgAgyAkQAKgIADgMQACgGABgMIAAgmIALAAIAAArQgBAKgCAHQgFANgKAKgAB5AoIAAgKIAVAAIAAgpIgSAAIAAgKIAwAAIAAAKIgTAAIAAApIAXAAIAAAKgAn9AnIAAAAIgBgBIAAhPIABgBIABgBIAbAAIABABIAAABIAABLIAAABIgBAAIgIAAIgBgBIAAgEIgKAAIAAAJIgBAAgAn0AUIAKAAIAAgWIgKAAgAn0gLIAKAAIAAgWIgKAAgAFEgfIAJgDQALARAGAVIgLAEQgFgWgKgRgADpgFQAGgFAEgHQADgGABgFIg6AAIAAgKIBFAAIADADQgCAOgFAIQgEAIgIAGgAmigDIg6AAIgBAAIAAgBIAAgHIAAgBIABAAIAhAAIAEgPIAJACIACABIgBACIgBADIgDAHIAPAAIABAAIAAABIAAAHIAAABIgBAAgAnPgNIgBgBIgDgJIgBgBIACgBIAGgCIABAAIABABIADAJIABABIgCABIgGACgAmHgOIgBgBIAAgcIAAgBIABAAIA8AAIABAAIAAABIAAAcIgBABgAl9gXIApAAIAAgMIgpAAgAGGggIgRgFIAEgIIATAEQAKADAGADIgGAJQgGgDgKgDgAnagbIgBgBIAAgBIAAgHIABgBIAUAAIAAgCIgBgJIALABIACABIgBACIAAAGIAAABIAWAAIABAAIAAABIAAAHIAAABIgBABg");
	this.shape.setTransform(6.625,1.475);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-44.4,-3.4,102.1,9.8), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHyAbIAJgHQANAKAIANIgKAHQgHgNgNgKgAHGAyIgHAAIgBgBIgBAAIABg6IgCADIgCACIgBgCIgEgDIAAAJIAAABIgBAAIgPAAIAAAGIASAAIABAAIAAABIAAAfQAAAGgDABQgDACgHAAIgCAAIgBgCIgDgHIAHAAQABAAABAAQAAAAAAAAQABAAAAgBQAAAAAAgBIAAgXIgNAAIgCAMIAFgBIgCgFIAAAAIABgBIAEgBIABAAIAAAAIAFANIAAABIgBACIgDABIgBABIAAgBIgBgEIgMAEIgEABIAAABIgBgCIgDgHIAEAAIACgOIgHAAIAAAhQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgnIAAgBIABAAIAQAAIABgGIgOAAIgBAAIAAgBIAAgRIgBgJIAJABIACAAIgBACQgBABAAAGIAAALIAYAAIAAgMIgBgJIAJABIABAAIgBACIAAAFIAAAFQAIgLAGgPIABgHIAJACIACABIgBACIgGANIAKAAIAFgRIAIACQAAABABAAQAAAAAAAAQABAAAAABQAAAAAAAAIgBABIgCAFIgDAHIAMAAIABABIAAAHIgBABIgNAAIAAAMIAKgBIABAAIAAABIAAAHIAAABIgBAAIgDAAIgHAAIAAALIAKAAIABAAIAAABIAAAHIAAABIgBAAIgDAAIgHAAIAAAOIAOAAIABABIAAAIIAAABIgBAAIghAAIAAAEIAAABIgBAAgAHHAjIAKAAIAAgOIgKAAgAHHAMIAKAAIAAgLIgKAAgAHHgHIAKAAIAAgMIgKAAgAEqAuQgCgDgEgDQAPgGAIgJQAGgJABgNIgOAAIgCAAIAAgBIAAgGIgKAHIgDACIgCgDQgCgDgEgCQAVgNAKgVIACgHIALADQAAABABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgBACIgCADQgHAQgMAMIA3AAQgPgPgIgSIAAgBIACgBIAHgDIABAAIABABQAGANAJALQAJAIAKAGQgDADgDAEIgCACIgDgBIgKgIIAAAKQAAAQgCAOQgBAHgFADQgDACgHAAIgHAAIgDgBIgBgCQgBgGgDgDIANABQADAAABgBQACgCABgEQACgKAAgQIgTAAQgDAhgdAMIgCABIgCgDgAiSAmQAPgGAFgKQAFgIAAgOIAAgSIAMAAIAAAQQAAAUgJAMQgGAJgOAHgAkYAlQAOgFAIgFQAIgHAEgKQAEgLAAgRIgoAAIAAAXIgMAAIAAghIAaAAIAAgPIAMAAIAAAPIAbAAQAAAYgEAOQgFAPgKAIQgJAIgRAFgAChAOQgNATgZAMIgGgJQAVgKANgSQAMgPADgSIgrAAIAAgKIA3AAIADADQgFAWgJAOQAMAOANAUIgLAIQgJgSgLgOgAloAuIAAhYIAMAAIAAAfQAWAGASAJIgGALQgPgKgTgFIAAAugADuAlQAQgEAGgJQAFgIAAgMQAAgPgGgIQgGgHgHAAQgCAigJASQgDAIgFADQgEADgEgBQgJAAgFgIQgEgIAAgNQAAgUALgNQAGgGAIgDQAHgDAIAAQAkAAAAAoQAAAhgiAHgADbgQQgIALAAAPQAAAJACAGQACADAEAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCACgEQADgJADgNIADgYQgJAAgHAJgAnbAEQgEgPgDgXIAMgBQAFAtARAbIgMAHQgJgTgGgVgAoPAmQARgcADgtIANABQgEAcgFATQgGARgIAOgAjYApIAAgJIAWAAIAAgpIgTAAIAAgKIAwAAIAAAKIgTAAIAAApIAXAAIAAAJgAgFgQIgCgBIgDABQgHASgMAVIgLgFQANgWAKgVQABgEADgCQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAQADABACABIADAFQAWAgATAZIgKAIIgkg3gAAxAHIAAgLIA8AAIAAALgAm6AHIAAgLIA8AAIAAALgAhogEQAHgEADgIQADgFABgFIg6AAIAAgKIBGAAIACADQgCANgFAJQgEAIgIAGgAGZgHIgDgDIAHgGIgFgEIgBgBIABgBIADgDIABAAIAGAEIABgCIACgEIAGADIABABIgBABIgBACIgCACIgBACIADADIABABIgBABIgCAEIgBAAIAAAAIgFgFIgFAFIgCABIgCgBgAAMgkIAGgDQAEAIAEAKIgHADQgDgLgEgHgAAYgoIAHgCQAFAIADAJIgIACQgDgKgEgHgAlLgsIAGgCQAFAHADALIgHACQgDgKgEgIgAGJgdIgBAAIgBgBIAAgGIABgBIABAAIATAAIAAgCIgBgHIALABIACABIgBABIAAAEIAAACIASAAIABAAIAAABIAAAGIAAABgAk/gwIAIgCIAHARIgHADQgEgKgEgIg");
	this.shape.setTransform(8.2,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-44.6,-4.7,105.7,10.100000000000001), null);


(lib.title2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGYBcQgFgFgGgEIALgIIgigBIAAAUQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgQAAQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIABgUIgwABQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgMQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIAwABIAAgJIgkAAIgCAAIgBgCIAAgwIABgBIACAAIAkAAIAAgIIgsAAIgCAAIAAgDIAAgLIAAgCIACAAIAsAAIgBgKIgyAAIgCAAIAAgCIAAgNIAAgCIACAAIAyAAIAAgLIgiAAIgCAAIAAgDIAAgKIAAgDIACAAIAiABIgCgSIAVACQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIgBADQgCADAAAHIAigBIACABIAAACIAAAKIAAADIgCAAIgiAAIAAALIAzAAIAAgMQgBgUgBgLIAVACQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIgBAEQgBADAAAIIAAAXIAtAAIACAAIAAACIAAANIAAACIgCAAIgsAAQABAjAEAUQAGgMAEgLQAEgLABgIQAJADAIAEQABAAAAABQABAAAAABQABAAAAABQAAAAAAAAIgDAFIgEAJQgKAZgMAUQAIAYAHAAQADgBACgGIADgSQAFAEAGADQAFACAAACIgBAGQgDASgFAIQgFAGgJAAQgQAAgNgeQgMAQgOAMQgEAEgBAAIgFgFgAGgA7IABACIAAAGQALgLAIgMQgIgdgCgyIg0AAIAAAKIApAAIACAAIAAACIAAALIAAADIgCAAIgpAAIAAAIIAkAAIACAAIAAABIAAAwIAAACIgCAAIgkAAIAAAJIAogBIACABgAF1AmIAWAAIAAgJIgWAAgAFNAmIAWAAIAAgJIgWAAgAF1ATIAWAAIAAgJIgWAAgAFNATIAWAAIAAgJIgWAAgACpBhIgCgBIAAgCIAAhAIAAgCIACAAIBdAAIACAAIABACIAAA/QAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgQAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgGIg3AAIAAAHIgBACIgCABgAC8BFIA3AAIAAgWIg3AAgAnTBgQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIABhaQgFAWgKASQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAABIgCgEQgDgKgEgFQARgaAIgkIgSAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgPQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAUAAIAAgPQAAgSgCgKIAUACQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIgBADQgCAEAAAQIAAAPIAPAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAPIgBACIgCAAIgEAAIgJAAQAFARAMARQgEAGgDAIQAAABAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAgBQgBAAAAAAQAAgBgBgBQAAgBAAgBQgFgKgDgLIABBfIAAAGIAAACIgCABgAkJBfQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAgBIAAhyIAAgCIACAAIBHAAIACAAIAAACIAABeQAAAMgEAFQgDACgFABIgQABQgFAAgBgBIgBgFQgCgIgDgFIANABQAHAAAAgGIAAgPIgjAAIABAmQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAj3AlIAjAAIAAgOIgjAAgAj3AHIAjAAIAAgNIgjAAgAmMBbQgDgHgFgEQAYgHAWgOIgHgSIgEgPIggAAIgDAVIAGgJIADgCIACABQAKAFAJAIIABACIAAACIgHAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAAAIgCgBQgKgKgLgFQgGAbgOAPIgEADQgBAAgEgDQgFgHgFgCQAVgTACglIgLAAIgCAAIgBgDIAAgNIABgCIACAAIA7AAQgFgbgBgiQgDABgEAGIgXAcIARgBIgDgIIAAgCIACgCIAGgCIABgBQABAAAAABQAAAAAAAAQAAAAAAABQABAAAAAAQAEAJAEARIAAACQAAAAAAABQAAAAAAAAQgBAAAAABQgBAAAAAAIgGACIgCABQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgBgHIgeAEQgFABgBACIgDAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAgBIgDgOIAGAAIAOgSQgJgNgMgLIgBgCIAIgJIACgCIACABIADADQAGgJAEgIIAEgIQAHACAHAFQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIgCADIgEADQgHANgGAIIAGAIIAHgJIAEgJIANAIIAAgEQAAgUgCgNIATACQABAAABAAQABABAAAAQABAAAAABQAAAAAAABIgBADIgBAMIAAAOIAIgKIACgBIABABIADACQAFgHAFgJIADgIIAOAHQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAIgBACIgEAEIgOAUIAHAIIAMgUIAOAIIACADQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgHAHIgXAcIARgBIgDgIIgBgCQAAAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAIAHgDIACgBIACACQAFAKAFARIAAABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAIgHADIgCABQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAgBIgBgGIgRADIALAIIACABIgCACIgFAFIAWAAIADAAIAAACIAAANIAAADIgDAAIgxAAIAHAVIAJgLQAEgFACgFIAPAIQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQgDACgDAEQgHAJgJAIQAIALAGgBQAHABACgYQAEADAGADQAFAEAAACIgBAEQgCAQgGAHQgEAFgIAAQgRAAgOgUQgSAMgUAHIgFACQgCAAgCgEgAliAIIAZAAIgLgIIgCgCIADgDIAEgDIgFABIgKACQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIgDgPIADAAIANgPQgKgNgMgLQABAkAGAhgABmBdIgCgFQgCgKgDgFIAOAAQAIABAAgJIAAgqIgQAHQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIgEgUQAJgBAKgEIAEgBIADgBIAAglIgXAAIgCAAIAAgCIAAgPIAAgCIACgBIAXABIAAgLQAAgQgCgOIAWABQABABAAAAQABAAAAAAQABAAAAABQAAAAAAABIgBAEQgCADAAASIAAAMIASgBIACABIAAACIAAAPIAAACIgCAAIgSAAIAAAfIAVgJIgBANIAAABQAZgNAQgWQAFgKACgFQAKABAKADQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQAYAcAmANQgFAGgDAJQgBAEgCAAIgFgBQgOgIgNgJIAAALIAAADIgCAAIg1AAIgCAAIAAgDIAAgKQgMAKgOAIIgFACQgBAAgCgFIgFgIIgLAGIABA1QAAAQgHAFQgGAEgRAAIgDAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAgADwAAQgOgMgLgOQgKAOgMAMIAvAAIAAAAgAioBZQgHgEAAgMIAAg1IgBgUIAUABQABABABAAQABAAAAAAQABABAAAAQAAABAAAAIgBAEQgBACAAAJIAAAKQARgHAPgJQAHgEAEgFIANAPIACADQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgJADQgfAQgPAEIAAAQQAAAGAEACQADABANAAQARAAAEgEQACgCABgFIAAgNQAIAFAHABIAEACIABACIAAAEQgBAKgDAFQgCAFgEADQgJAGgaAAQgZAAgIgDgAgmBPQgJgHAAgQQAAgPALgLQALgMAbgOQgBgIgCgDQgCgDgFAAQgKAAgNAKQgKAIgOAQIgQgNQAcgcAPgdIglAAIAAgSIAtAAIAJgbIAVADIgJAXQAegBAZgDIAAASIg/AFQgHANgJAKIgFAFIABABIAFgEQAIgGAKAAQAJAAAHAHQAHAGACAKIAqgSIAIAUQgcAJgVAJIAAAoIgUAAIAAgfQgSAKgGAHQgGAFAAAIQAAAIAIADQAIADAUABQAYgBAfgDIABAUQgcADgeAAQggAAgMgKgAiogKQgHgDAAgLIAAgxQAAgOgCgHIAVABQABABABAAQAAAAABAAQAAABABAAQAAAAAAABIgBADQgBACAAAKIAAAKQARgGANgHQAHgEAFgFQAHAGAGAIIACADQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgKAFQgRAIgbAKIAAAMQAAAFADABQAEABAMABQASAAADgFQACgBAAgEIABgNQAGAEAJACIAEACIABADIAAADQgCAKgCAFQgCAFgEACQgIAFgbAAQgZAAgHgDgAjFgfIgEgJQgaAEglADQgGABgCABIgDABQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAgBAAgBIgDgSIARAAQAHgOAGgPIAEgPIATAFQABAAABAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgCACgCAEIgMAaIAhgEIgJgNIAAgBIACgCIAMgHIACACQAKANAMAYIABACIgCADIgMAGIgCABIgCgCgADpglIgCgBIAAgCIAAgRIghAAIABARIgBACIgCAAIgPAAIgCgBIAAgBIAAgRIgXAAIgCAAIAAgCIAAgNIAAgDIACAAIAXABIgBgVIAUABQAAABABAAQAAAAABAAQAAAAAAABQAAAAAAABIgBADQgBABAAAIIAAAFIAhAAIAAgCIgBgTIAUACQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIgBADQgBABAAAIIAAAFIAcgBIACABIAAACIAAANIAAACIgCAAIgcAAIAAARIAAACIgCABgAHSg6QgGgMgIgKIgBgCIACgDIAJgEIADAAIACABQAIAJAGAMIABADIgCACIgKAFIgDABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBg");
	this.shape.setTransform(3.625,0.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title2, new cjs.Rectangle(-46,-8.9,99.3,19.3), null);


(lib.screen = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap18();
	this.instance.setTransform(-84,-98);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.screen, new cjs.Rectangle(-84,-98,168,196), null);


(lib.logomc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhrCkQgZgHgRgSQgRgSgGgZQgDgTACgTQAEgdAWgUQAQgNAVgIQAbgIAUgEIAigGQAUgDAXgHIAJgDQAHgCAGgHQAFgJgDgJQgEgPgPgFQgVgHgWAIQgPAGgFAPQgEAJABAKIhtgDIgCgGQgCgRAFgQQAOgtAsgSQAUgIAQgDQBCgMBEAPQAUAEAUALQAhATAJAjQAHAdAAAZIACBjQAAAiADAqQABAOAHALIh4AAQgEgEgCgHIgIgWQgSAWgXAJQgeAMgfAAQgXAAgXgHgAAAAfIgkAMQgIADgGAFQgKAJADANQABAIAGAFQAGAHAJADQALACALAAQAOgCALgFQAOgGAIgNQAHgLABgMQACgQgBgSQgXALgUAFg");
	this.shape.setTransform(-121.9139,-35.2317,0.2299,0.2299);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhrCkQgZgHgRgSQgRgSgGgZQgEgTADgTQADgdAXgUQAPgNAWgIQAcgIASgEIAjgGQASgDAZgHIAJgDQAIgDAEgGQAGgJgDgJQgEgPgQgFQgTgHgXAIQgPAGgGAPQgDAKAAAJIhtgDIgBgGQgCgQAFgRQANgtAsgSQAUgIARgDQBCgMBEAPQATAEAVALQAhATAJAjQAHAaAAAcIABBjQABAnADAlQABAOAHALIh4AAQgEgEgDgHIgHgWQgSAVgXAKQgfAMgeAAQgXAAgXgHgAAAAfIglAMQgIADgFAFQgKAJACANQACAHAFAGQAGAGAKAEQAKADAMgBQANgCAMgFQANgGAIgNQAHgJACgOQACgQgCgSQgXALgTAFg");
	this.shape_1.setTransform(-105.1949,-35.2317,0.2299,0.2299);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgxCmQgjgHgdgWQgtgjgOg1QgKgiADgjQAGg8ArgpQAngmA3gJQAUgDAQAAQASAAASADQA4AJAnAmQArAoAGA9QADAjgKAiQgOA1gtAjQgdAWgjAHQgYAGgaAAQgZAAgYgGgAgJhWQgSAEgLAQQgKAPgEAQQgFAiAEAfQADAOAGARQAIARARAHQATAJARgIQAUgHAHgSQAIgRABgOQAFgfgFgiQgEgQgJgPQgFgIgJgFQgMgIgOAAIgJABg");
	this.shape_2.setTransform(-89.1406,-35.2315,0.2299,0.2299);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjHDjIAAnFID6ABQAsADAkAXQAjAYATApQATApgFAtQgFAwggAjQggAjgwALQgfAGgeAAIhSAAIAACMgAg9gSIBSgBQAWgBAMgRQAHgJACgLQABgMgBgGQgCgSgNgMQgNgMgSAAIhPAAg");
	this.shape_3.setTransform(-130.3075,-36.7373,0.2299,0.2299);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOCgQgfgJgXgVQgTgSgHgVQgGgQAAgPIAAgHIB2AAQAAAIADAJQAEAKAHAHQAHAFAHADQAQAGAPgDQAMgCAKgJQAJgKgCgMQgDgMgMgEQgNgFgNgCIhGgNQgTgEgQgHQgkgOgOgjQgHgSAAgVQABgMAEgMQAJgaAWgRQAZgUAfgHQAWgFAYgCQAogCApAHQAUAEANAFQARAHAOALQAQAMAHAUQAHASAAAVIhyAAQAAgKgFgIQgGgIgKgDQgSgHgUAGQgLADgGAKIgBACQgCAFACAGQACAFAFADIAJADIAUADQAhAFAnALIANAEQAfAJAXAUQARANAHAXQAKAegIAdQgJAcgYAVQgLAJgLAGQgdAOgdAEQgXAEgXAAQgpAAgogMg");
	this.shape_4.setTransform(-97.2596,-35.2361,0.2299,0.2299);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAsCoIAAi7QAAgIgCgKQgFgQgQgHQgRgHgRAGQgRAFgJAQQgIANAAAPIAAC0Ih9AAIAAlDIB1AAIADAiQAXgUAbgMQAugWAxAOQA3AQARA3QAIAXAAAbIAADQg");
	this.shape_5.setTransform(-113.5606,-35.3754,0.2299,0.2299);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAsCoIAAi7QAAgKgDgIQgFgQgQgHQgQgHgRAGQgRAFgKAQQgHANAAAPIAAC0Ih9AAIAAlDIB1AAIADAiQAXgUAbgMQAugWAxAOQA3ARARA2QAIAZAAAZIAADQg");
	this.shape_6.setTransform(-80.6232,-35.3754,0.2299,0.2299);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag8CiIAAlDIB5AAIAAFDg");
	this.shape_7.setTransform(-74.6863,-35.2487,0.2299,0.2299);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag8ArIAAhVIB5AAIAABVg");
	this.shape_8.setTransform(-74.6863,-40.9672,0.2299,0.2299);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRCrQgugFglgcQgegWgTghQgOgYgFgdQgGgoAKgmQANguAggfQAhgfAvgKQAzgKAyANQAkAJAcAaQARAQALAUQANAagCAbIhvAAQgEgWgRgOQgMgJgOAAQgNgBgMAIQgRAKgGATQgOArANAtQAFASAOAOQARAQAWgDQAPgDAIgKQAKgLACgOIADgTIB1AAQADA1glAmQgkAmgzAKQgWAFgXAAIgWgBg");
	this.shape_9.setTransform(-68.9766,-35.226,0.2299,0.2299);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgRAMgXALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_10.setTransform(131.0374,-33.4075,0.2766,0.2757);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgQAMgYALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_11.setTransform(125.0214,-33.4075,0.2766,0.2757);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag/CeQgXgFgQgHIAAhIQAUAOAXAIQAWAIATAAQAZAAALgHQALgHAAgQQAAgPgMgKQgNgLgggNQgogRgRgUQgRgVAAghQAAgqAhgbQAhgbA0AAQAPAAAWAEQAQADASAGIAABGQgQgKgSgHQgUgHgSAAQgVAAgLAIQgLAIAAAPQAAAPAJAJQALAJAgAOQAtARARAVQARAWAAAfQAAArghAbQgiAbg4AAQgRAAgagFg");
	this.shape_12.setTransform(116.606,-31.5882,0.2766,0.2757);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AA/CbIg+jfIAAAAIhADfIhNAAIhak1IBMAAIA6DtIABAAIBFjtIBEAAIA9DuIACAAIA4juIBGAAIhbE1g");
	this.shape_13.setTransform(106.8629,-31.5882,0.2766,0.2757);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhzB4QgrgrAAhJQAAhMAsgtQArgsBMAAQBJAAApArQAoArAABKQAABLgrArQgrAthLAAQhHAAgqgqgAg8hJQgWAaAAAxQAAAwAWAaQAWAZAoAAQAnAAAWgZQAUgaABgyQAAgxgWgaQgWgZgmAAQgoAAgWAbg");
	this.shape_14.setTransform(95.7022,-31.5745,0.2766,0.2757);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhzC+QgjgoAAhHQAAhMAmguQAnguBAAAQAcAAAXAKQAXAKAMASIACAAIAAizIBIAAIAAHIIhIAAIAAgpIgCAAQgQAXgZALQgaAMggAAQg7AAgigpgAg1gCQgVAcAAAzQAAAvAUAZQAVAZAiAAQAiAAAWgaQAWgaAAgqIAAghQAAghgVgVQgVgXggAAQgmAAgUAcg");
	this.shape_15.setTransform(85.724,-33.5454,0.2766,0.2757);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("ABCCeIAAisQAAgqgPgVQgOgVggABQgeAAgTAXQgVAXAAAjIAACuIhIAAIAAk1IBIAAIAAAqIACAAQARgZAZgLQAYgMAhAAQAxAAAbAgQAaAfAAA/IAAC9g");
	this.shape_16.setTransform(76.2921,-31.6778,0.2766,0.2757);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgkDdIAAk1IBIAAIAAE1gAgfiUQgNgLABgSQgBgSANgMQAOgNARAAQATAAAMANQANANABARQgBASgNAMQgMAMgTAAQgSAAgNgNg");
	this.shape_17.setTransform(69.4947,-33.4075,0.2766,0.2757);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABaDYIhXlFIgCAAIhVFFIhaAAIh4mvIBRAAIBVFVIABAAIBelVIBPAAIBYFUIACAAIBRlUIBOAAIh1Gvg");
	this.shape_18.setTransform(59.4197,-33.2766,0.2766,0.2757);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_19.setTransform(40.5351,-28.0668,0.2766,0.2757);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_20.setTransform(30.0867,-28.0668,0.2766,0.2757);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_21.setTransform(40.5351,-38.4795,0.2766,0.2757);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_22.setTransform(30.0867,-38.4795,0.2766,0.2757);

	this.instance = new lib.Bitmap8();
	this.instance.setTransform(53.95,-7.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logomc, new cjs.Rectangle(-134.9,-43.2,269.9,86.5), null);


(lib.light2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#234F9C","rgba(1,11,25,0)"],[0,1],0,-0.1,0,0,-0.1,152.9).s().p("AwjQkQm4m2AApuQAApsG4m4QG3m3JsAAQJtAAG4G3QG3G4AAJsQAAJum3G2Qm4G4ptAAQpsAAm3m4g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.light2, new cjs.Rectangle(-150,-150,300,300), null);


(lib.light = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#234F9C","rgba(1,11,25,0)"],[0.298,1],0,0,0,0,0,114.2).s().p("AsXMYQlIlIAAnQQAAnPFIlIQFIlIHPAAQHQAAFIFIQFIFIAAHPQAAHQlIFIQlIFInQAAQnPAAlIlIg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#234F9C","rgba(1,11,25,0)"],[0.298,1],0,0,0,0,0,114.2).s().p("AsXMYQlIlIAAnQQAAnPFIlIQFIlIHPAAQHQAAFIFIQFIFIAAHPQAAHQlIFIQlIFInQAAQnPAAlIlIg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.light, new cjs.Rectangle(-112,-112,224,224), null);


(lib.flowermc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap10();
	this.instance.setTransform(-162,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.flowermc, new cjs.Rectangle(-162,-125,324,250), null);


(lib.CTAmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAFA2IgBgBIAAgjIABgBIAeAAIABABIAAAhIgBABIgEAAIgBgBIAAgFIgUAAIAAAHIgBABgAAKApIAUAAIAAgSIgUAAgABFA1IgBAAIAAgdIgaAAIAAgBIAAgFIAAgBIAaAAIAAgRIgUAAIgCgBIAAgFIACgBIAUAAIAAgRIgXABIgBgBIAAgFIABgBIAeABQAGgKACgIIACgGIAGACIACABIgCADIgCACIgHAQIAUgBIABABIAAAFIgBABIgbgBIAAARIAWAAIABABIAAAFIgBABIgWAAIAAARIAdAAIABABIAAAFIgBABIgdAAIAAAdIgBAAgAikAqQAYAAALgGQAGgDADgFQADgEgBgGQAAgIgFgEQgEgFgJAAQgOABgLAMQgEAEgCAGIgJgBQAAgSAEgjIAIABIgDAkIgCAGIAEgEQAFgIAJgCQAHgDAIgBQANABAIAFQAGAHAAAKQAAAKgDAHQgEAEgHAEQgFAEgNABIgVADgADRAHQgEgEAAgDQAAgEADgDQAUgTATgXIAHAFQgSAWgUASQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAABQAAABADACQAVASAVAXIgHAGQgTgXgYgUgACDAsQgGgGAAgMIABhKIAJAAIgCBJQAAAKAFADQADAEAJAAQAOAAAHgIQAIgIADgPIAIAEQgIAjgfAAQgPAAgFgGgAj4AsQgLgFAAgNQAAgMAMgGQAIgFAMAAQAPABAIAFQgMgMgJgSIgiACIAAgIQARAAAPgBIgIgWIAJgBIAHAWQANgCANgDIAAAHIgXAEQAIAUAPAOIgFAIQgOgJgPAAQgLABgHAFQgFAEAAAGQAAAQAfAAIAQgBIAAAHIgQACQgUgBgJgFgAhaAKQAAgUAHgkIAJABQgIAiAAAVQAAAWADAQIgIAAQgDgRAAgVgAg8ApQgFgFAAgJQgBgHACgFIAIAAIgBALQAAAGADADQAFABAJAAIAXgBIAAAJIgWABQgQAAgFgEgAAGAHIgBgBIAAgFIABgBIAcAAIABABIAAAFIgBABgAAGgIIgBgBIAAgFIABgBIAcAAIABABIAAAFIgBABgAAAgZIgBgBIAAgEIABgCIAnAAIABACIAAAEIgBABgAg+ghIAfgBIAOAAIAAAIIgPAAQgPAAgPABgAihgsIAEgHQAWAFAPAGIgFAHQgPgGgVgFgAA7giQgDgHgFgIIAAgBIABgBIADgBIABgBIABABQAFAHADAIIAAABIgCAAIgDACIgBAAgAAFgpIgBgBIAAgFIABAAIAfAAIABAAIAAAFIgBABg");
	this.shape.setTransform(-5.15,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgPgeIAeAeIgeAf");
	this.shape_1.setTransform(30.35,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0075D4").s().p("AmPB/QgeAAAAgdIAAjDQAAgdAeAAIMfAAQAeAAAAAdIAADDQAAAdgeAAg");
	this.shape_2.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTAmc, new cjs.Rectangle(-42.9,-12.7,85.9,25.5), null);


(lib.commc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap17();
	this.instance.setTransform(-156,-103);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.commc, new cjs.Rectangle(-156,-103,312,206), null);


// stage content:
(lib._300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(420));

	// CTA
	this.instance = new lib.CTAmc();
	this.instance.setTransform(343.5,222.75);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(257).to({_off:false},0).to({x:242.5},12,cjs.Ease.get(1)).wait(151));

	// txt
	this.instance_1 = new lib.txt5();
	this.instance_1.setTransform(218.5,186.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(245).to({_off:false},0).to({x:233.5,alpha:1},12,cjs.Ease.get(1)).wait(163));

	// txt
	this.instance_2 = new lib.txt3();
	this.instance_2.setTransform(214.55,156.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(237).to({_off:false},0).to({x:229.55,alpha:1},12,cjs.Ease.get(1)).wait(171));

	// txt
	this.instance_3 = new lib.txt2();
	this.instance_3.setTransform(210.8,144.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(233).to({_off:false},0).to({x:225.8,alpha:1},12,cjs.Ease.get(1)).wait(175));

	// txt
	this.instance_4 = new lib.txt1();
	this.instance_4.setTransform(210.4,131.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(229).to({_off:false},0).to({x:225.4,alpha:1},12,cjs.Ease.get(1)).wait(179));

	// title
	this.instance_5 = new lib.title2();
	this.instance_5.setTransform(44.9,82.35);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(217).to({_off:false},0).to({x:59.9,alpha:1},12,cjs.Ease.get(1)).wait(191));

	// title
	this.instance_6 = new lib.txtTitle();
	this.instance_6.setTransform(70.25,58.1);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(213).to({_off:false},0).to({x:85.25,alpha:1},12,cjs.Ease.get(1)).wait(195));

	// logo
	this.instance_7 = new lib.logomc();
	this.instance_7.setTransform(150.05,58.75);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(199).to({_off:false},0).to({alpha:1},24,cjs.Ease.get(1)).wait(197));

	// screen
	this.instance_8 = new lib.screen();
	this.instance_8.setTransform(150,342,0.9,0.9,0,0,0,0.2,0.4);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(64).to({_off:false},0).to({y:152.15},30,cjs.Ease.get(1)).wait(30).to({regX:0.9,regY:1.7,scaleX:0.5,scaleY:0.5,x:152.45,y:136.75},35,cjs.Ease.get(1)).wait(30).to({regX:2.8,regY:3.9,scaleX:0.348,scaleY:0.348,x:93.65,y:168.1},24,cjs.Ease.get(1)).wait(207));

	// flower
	this.instance_9 = new lib.flowermc();
	this.instance_9.setTransform(150,360.25,0.88,0.88,0,0,0,0.2,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({y:140.25},34,cjs.Ease.get(1)).wait(30).to({regX:0.4,regY:0.5,scaleX:0.95,scaleY:0.95,y:131.7},30,cjs.Ease.get(1)).wait(30).to({regX:1.4,regY:1.7,scaleX:0.56,scaleY:0.56,x:154.45,y:115.85},35,cjs.Ease.get(1)).wait(30).to({regX:1.9,regY:3.2,scaleX:0.3898,scaleY:0.3898,x:94.7,y:153.45},24,cjs.Ease.get(1)).wait(207));

	// light
	this.instance_10 = new lib.light2();
	this.instance_10.setTransform(150.05,325.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({y:128.1},34,cjs.Ease.get(1)).to({_off:true},90).wait(296));

	// com
	this.instance_11 = new lib.commc();
	this.instance_11.setTransform(235.35,205.35,1.6666,1.6667,0,0,0,51.2,33.8);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(124).to({_off:false},0).to({regX:51.9,regY:34.6,scaleX:0.78,scaleY:0.78,x:189.5,y:164.55},35,cjs.Ease.get(1)).wait(30).to({regX:52.4,regY:35.5,scaleX:0.543,scaleY:0.543,x:119.25,y:187.3},24,cjs.Ease.get(1)).wait(207));

	// light
	this.instance_12 = new lib.light();
	this.instance_12.setTransform(148,125.05,1.8482,1.8482);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(124).to({_off:false},0).wait(65).to({scaleX:1.5627,scaleY:1.5627,x:88,y:175.05},24,cjs.Ease.get(1)).wait(207));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#010B19").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(420));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(40,43.1,370,432);
// library properties:
lib.properties = {
	id: '542CFFE83C13439EB4A04353E49F32EB',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap10.png?1631788985413", id:"Bitmap10"},
		{src:"images/Bitmap17.png?1631788985413", id:"Bitmap17"},
		{src:"images/Bitmap18.png?1631788985413", id:"Bitmap18"},
		{src:"images/Bitmap8.png?1631788985413", id:"Bitmap8"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['542CFFE83C13439EB4A04353E49F32EB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;