(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap10 = function() {
	this.initialize(img.Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,324,250);


(lib.Bitmap17 = function() {
	this.initialize(img.Bitmap17);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,312,206);


(lib.Bitmap25 = function() {
	this.initialize(img.Bitmap25);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,209,236);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtTitle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap1BSIgDgCIgBgFQgCgHgDgGIAQACQAGgBACgCQAFgGACglIgRAAIgBAHQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgIgBQgIgBAAgCIAAgBQAFgWACgSIAAgNQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABgBIAbABIAAgXIggABIgCgBIgBgCIAAgMIABgCIACAAIAvAAIACAAIAAACIAAAzIAAABIgCABIgcgBIgCAUIAeAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAAOQgCAngGAOQgDAGgFADQgGACgJABgAnEBNQgGgHgGgDQAsgTAMgjQAGgPACgUIg0AAIgCAAIgBgCIAAgOIABgCIACAAIA1AAIAAgPQAAgOgCgKIAVABQABABABAAQAAAAABAAQAAABABAAQAAABAAAAIgCAFQgBADAAAMIAAAPIA+AAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAQQgBA0gFAaQgCAOgIAFQgHAFgNAAIgRAAIgFgCIgCgFQgBgJgEgGQAOADANAAQALAAACgMQAFgbAAgsIgtAAQgDAZgGARQgJAWgOAOQgNANgTALIgEABQgCAAgCgEgAnuBPIgFgNQggAHgnAEIgHADIgDAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAgBIgDgSIAHABIAkgDIAAgWIghABIgCgBIAAgBIAAgwIAAgCIACAAIAhABIAAgQIgYADQgFAAgCABIgDABQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIgDgPIAOAAQAHgMAEgMQADgGABgFIARADQABAAABAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBABIgDAEIgLAWIAmgDIgLgNIgBgBIACgCIALgGIABABQAQAQANATIABABIgCACIgLAHIgCABIgCgBIgFgKIgZACIAAARIAjgBIACABIAAABIAAAwIAAABIgCABIgjgBIAAAUIAUgCIgFgIIgBgBQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABgBIAJgDIABgBIACABQAMAQAHATIABABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgLAGIgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAgAoPAUIAUAAIAAgUIgUAAgAoyAUIASAAIAAgUIgSAAgAEyA/QAVgEAMgHQAMgHAGgOQAFgMAAgVIAAhDIAUAAIAABFQAAAmgSASQgPAPgiAIgAjuBHQgHgHAAgLQAAgPAMgHQAKgGAOAAIAOABQgCgOAAgcIASAAQAAAdABAQQATAJAQAOIgKAQQgNgOgMgGIAAAFQAAAMgJAIQgJAFgQABQgRgBgJgHgAjlA0QAAAMASAAQARAAAAgPIgBgBIAAgFQgFgDgIAAQgVAAAAAMgAJSBOIAAhGQgQALgVALIgLgPQA2gYAbgmIARAMQgOAPgRAOIAABUgAGnBAQAbgKAKgTQAEgJACgIQABgKABgRIg3AAIAAgRIB4AAIAAARIgtAAQgBAXgDANQgCAKgFAJQgHALgKAIQgJAHgOAGgABOATIg1AIIgDgRIA2gIIgFgaIgsAGIgDgRIAtgGIgFgeIATgDIAFAfIAtgGIADAQIgtAGIAEAbIAvgGIADAQIgvAGIAKA7IgUADgAhUBBQgIgGAAgQIAAg6IgdAHIgFgQIAigIIAAgpIAUAAIAAAlIBBgQIAJANQgHAXgKAQQgIANgMAPIgRgKQAZgbAHgXIg0AMIAAA+QAAAFACADQACACAFACIASABQAYAAAUgCIAAATIgwABQgbAAgIgIgAChBGIAAgQIA9AAIAGhHIg1AAIAAgRIBJAAIgHBYIAaAAIAAAQgAkaAsQAVgmAKgkIgcAAIAAgPIAgAAIAFgeIATADIgFAaIAXgDIABAQIgcACQgMApgUAqgAEoAUIAAhYIAUAAIAABYgAjDglIAJgPQAbAJARAMIgJAQQgSgNgagJgAGogxIAAgQIBiAAIAAAQg");
	this.shape.setTransform(-1.425,39);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txtTitle, new cjs.Rectangle(-65.8,30.9,128.8,16.300000000000004), null);


(lib.txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AI6AhQgCgDAAgEQAAgGADgDQADgDAFAAQAGABACADQADAEAAAEQABAFgEADQgEAEgEAAQgFAAgEgFgAI+AWQAAAAgBAAQAAABAAAAQAAABAAABQgBAAAAABQAAADADACQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAQADAAACgBQAAgBABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAgDgCgCQgBgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgCADgAB0AhQgEgDAAgEQAAgGAFgDQADgDAEAAQAFABADADQAEAEAAAEQgBAFgDADQgEAEgEAAQgFAAgDgFgAB3AWQAAAAgBAAQAAABAAAAQAAABAAABQAAAAAAABQAAADABACQABAAABABQAAAAABAAQAAAAABAAQAAAAABAAQADAAACgBQAAgBABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgDgCgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgCADgAinAjIgBgGIAJgBIABAAIAAgGQgHADgJADIgCAAIgBgCQgBgDgCgBQAQgDAJgGIgXAAIgBAAIAAgGIABgBIAAAAIAgAAIAAgDIgDAAIAAgBIgBgEIACAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAIAAgCIgHAAIAAAJIgBAAIgFAAIgBAAIAAgJIgIAAIAAADIABAEIgBAAIAAABIgGAAIAAgBIgBAAIABgIIgBgFIABgBIAOABIAAgDIgRAAIgBgBIAAAAIAAgFIAAgBIAFAAIgBgBIgEgBQAEgEABgEIACgEIAGABIABABIgBABIgBACIAAAAIAGAAIgBgGIAIAAIABABIgBACIAAADIANAAIAAAAIABABIAAAFIgBAAIgNAAIAAADIAQAAIAAABIAAAFIAAABIgQAAIAAADIANgBIABABIAAAJIgBADIACAAIABABIAAACIgBACIAeAAIABAAIAAABIAAAGIAAAAIgNAAIAGADIAAACIAAABIgDACIgFACQAHAEAKACIgEAEIgCACIgCAAQgVgGgJgQIAAAAIgHAFIAAAJIAPgDIAAAFIgBABIgCABIgXAEIgDACIgCAAIgBgCgAiAAUIAFgEIADgDIgOAAQACAEAEADgAECAlIgBgBIAAggIgGAAIgEAAIgBABIgBgBIgBgGIAHAAIAEgGIgKgMIgBAAIABgBIACgEIABgBIABABIACACIAEgIIACgGIAHAEIABABIgBABIgBABIgHAMIADAEIAFgJIADgGIAGAEIABABIgBABIgCADIgMASIAJgBIgCgEIAAgBIAEgCIABgBIABABQADAGACAIIAAgiIABAAIAkAAIAAA/IAAABIgGAAIgBgBIAAgDIgWAAIAAADIgBABIAAAAIgGAAIgBAAIAAgeIgBABIgEACIAAAAIgBgBIgBgDIgFAAIAAAhIgBABgAErAXIAIAAIAAgUIgIAAgAEdAXIAGAAIAAgUIgGAAgAErgDIAIAAIAAgUIgIAAgAEdgDIAGAAIAAgUIgGAAgADTAlIAAgBIAAgSIgQAAIAAgBIAAgFIAAgBIAQAAIAAgJIgNAAIAAgBIAAgFIAAgBIANAAIAAgIIgOAAIAAgBIAAgGIAAgBIAUAAIAEgKIABgFIAIADIAAABIAAABIgCACIgDAIIALAAIAAABIAAAGIAAABIgRAAIAAAIIAOAAIABAAIAAABIAAAFIAAABIgBAAIgOAAIAAAJIARAAIABAAIAAABIAAAGIgBAAIgRAAIAAASIgBABgACpAlIgBgBIAAgZIAAgBIAYAAIAAABIAAAXIAAABIgHAAIgBgBIAAgCIgIAAIAAADIgBACgACwAZIAIAAIAAgJIgIAAgAk/AlIgBgCIAAguIABgBIAbAAIABABIAAAnQAAAFgCABQgBABgIAAIgCAAIAAgCIgCgFIAFABIACgBIAAgCIAAgGIgNAAIABAPIgBACgAk4ANIANAAIAAgGIgNAAgAk4ABIANAAIAAgFIgNAAgAgkAkIgCgBIAAgEIgOAAIAAAEIAAABIgHAAIgBgBIAAggIAAgBIAdAAIABAAIAAABIAAAgIgBABgAg0AYIAOAAIAAgPIgOAAgAhgAkIAAAAIAAgBIAAggIAAgBIAAAAIAcAAIABABIAAAfIgBABIgGAAIgBgBIAAgDIgNAAIAAAEIAAABgAhYAYIANAAIAAgPIgNAAgAkUAjIgBgCIgCgFIAIAAIADgBIABgDIAAgaIgBgLIAIABQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIgBABIAAAIIAAAcQAAAGgEACIgEABIgHAAIgCAAgAA2AaQAOgBAGgFQAEgDABgFQgDAEgHAAQgGAAgEgEQgDgDAAgGQAAgFAFgEQADgEAHAAQADAAADACIAAgIIgfABIAAgHIAfgBIAAgKIAIAAIAAAKIATAAIAAAHIgTAAIAAAQQACADAAAGQAAAMgIAFQgGAGgOACgABBgCQgBACAAADQAAADABACQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQADgBACgCQACgCAAgCQAAgHgHABQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAgBAAgAIHAaIABAAQAPAAAIgEQAHgDAAgIQAAgFgDgCQgDgDgFAAQgJAAgHAHQgDAFgBACIgIgBIADgjIAIACIgDAVIgBAEIADgDQAIgIALAAQAJAAAFAFQAEAEABAIQAAAHgEAEQgCADgFADQgJAFgRAAgAnnAbQAKgCAEgDQAGgDACgGQADgFAAgKIAAgdIAJAAIAAAeQAAARgJAIQgGAHgPADgAogAbQAJgCAGgDQAFgDADgGQACgFAAgKIAAgdIAJAAIAAAeQAAARgJAIQgGAHgPADgAHMAaQATAAAHgDQAFgEAAgGQAAgJgKAAQgGgBgFADQgFADgFAGIgIgDQAGgMAEgPIgNAAIAAgHIAOAAIACgMIAJABIgDALIAagCIAAAHIgbACQgDAMgFAIQAIgIAMAAQAJABAFAEQAEAFAAAGQAAALgKAGQgIADgUAAgAgEAHQAAgIAFgIQAEgGAHgEIAEgCIAAgBIgFACIgcADIgBgHIAzgEIAAAHQgIABgFACQgRAKAAAOQABAQAYADIgCAIQgegCAAgYgAljAKQgLAOgSAJIgFgHQARgHAJgPQAJgKADgPIghAAIAAgHIAqAAIACADQgEAQgGALQAJALAJAPIgIAFQgHgNgIgKgAFYAVQABgFAEgDQAEgDAGAAIAHABIgBgWIgVAAIAAgHIAVAAIAAgOIAIAAIAAANIANgBIAAAIIgNAAIABAZQAHADAIAHIgGAHQgFgGgEgDIAAABQAAAFgEADQgEADgGAAQgPAAgBgMgAFhASQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAABQAAAEAHAAQAHAAAAgGIAAgCQgDgCgEAAQgEAAgCACgAFIAHQAAgPAFgYIAIABQgFAXAAAPQAAALACAOIgIABQgCgNAAgNgAjZAaQAMgCAFgHQAEgGAAgJQAAgMgFgGQgEgEgGgBQgCAagGAOQgDAGgDACQgDACgDAAQgHgBgDgFQgEgGAAgLQAAgPAJgKQAEgEAGgCQAFgDAHAAQAbAAAAAfQAAAYgaAGgAjngNQgGAIAAALQAAAIACADQAAABABABQAAAAABABQAAAAABAAQAAABABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAIADgEIAEgRQACgJAAgKQgGACgFAGgAGMARQgBgGAEgHIAIADQgDAFAAAFQAAAEADACQAEABAHAAIAWgBIABAJIgXAAQgWABAAgQgAD4AeIgEgCQADgIAAgHIAAgFIAHACQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIgBABIAAACIgCAPIgCACgAEOAZIAAAAIgEgOIAAgBIAFgCIABAAIAAABQADAHAAAHIABAAIgBABIgEABgAkbAUIgBgBIAAgSIAAgLIAIABIABABIAAACIgBAHIAAASIAAABgAnsAIIAAgnIAJAAIAAAngAokAIIAAgnIAJAAIAAAngAC3AFIgNABIAAgBIgBAAIAAgFIABAAIAVAAIAAAAIAAAFIAAAAIAAABgAm4AEIAAgIIAtAAIAAAIgAAUgKIAGgBIAFAMIgFACQgDgGgDgHgAh+ADIAAgCIgCgEIAGAAIACAAIABgCIAAgUIgBgLIAJABIABABIgBACIAAAHIAAAWQAAADgDACQgCABgHAAIgDAAgAo/gHIgGAKIgGgEIAIgJIgLgBIACgHIAKAFIgBgMIAHAAIgBAMIAKgFIACAHIgKABIAHAJIgGAEgAAdgMIAGgBQADAFACAHIgFABIgGgMgACqgEIgBAAIAAgGIABgBIAAAAIANAAIAIAAIAAAAIAAABIAAAGIAAAAgAhVgFIgBAAIAAgBIAAgaIAAgBIABAAIAsAAIAAABIAAAaIAAABgAhNgNIAcAAIAAgMIgcAAgAiFgHIAAAAIgBgBIABgPIgBgIIAIAAIABAAIAAACIgBAGIAAAQIAAAAgAGbgNIAOgIIgLABIgOAAIAAgIIAQAAIAUgBIABAIIgIAFIgMAJgAClgOIAAgBIAAgGIAAgBIAcAAIABABIAAAGIgBABgAlEgRIgBAAIAAgBIAAgGIABgBIAUABIgFgIIgBgBIABgBIAGgCIABAAIAAAAIAFAIIABAAIgBABIgGADIASAAIAFgIIACgFIAIADIABABIgBABIgCACIgEAGIAVgBIABABIAAAGIAAABgAIWgYIgNgEIADgGIAPADIAMAEIgFAHIgMgEgADNgWIgFgKIAAAAIAAgBIAFgCIABgBIABABIAFAKIAAABIgBABIgEABIgBABIgBgBgAC/gaIgVAAIgCAAIAAgBIAAgFIAAgBIACAAIAVAAIABAAIAAABIAAAFIAAABIgBAAg");
	this.shape.setTransform(-154.6,207);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt5, new cjs.Rectangle(-213.6,203.3,118.1,7.5), null);


(lib.txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGrA3QgEgGAAgHQAAgIAGgGQAFgFAIAAQAIAAAFAGQAGAGAAAHQAAAIgHAGQgFAEgHAAQgIAAgHgFgAGyAiQgDADAAAFQAAAEADAEQADACAFAAQAEAAAEgDQACgDAAgEQAAgFgDgEQgDgCgEAAQgFAAgDADgAEyA7IgBgBIAAAAIAAhAIgIAJIgDABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgCgHgCgEQAQgSAHgYIADgJIAMADQABABAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACIgCAFIgJARIABBXIgBAAIAAABgAlBA7IgBgBIAAAAIAAgoIAAgCIABAAIAgAAIABAAIABACIAAAlIgBACIgBAAIgJAAQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgEIgLAAIAAAHQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAgAk3ApIALAAIAAgOIgLAAgAm8A7QAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIABhBIgIAJIgCABQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIgEgKQAPgRAIgYIACgJIANADQAAABAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAACQgCABgBAEQgEAKgEAIIAABWIAAAAIgBABgAiuA6IgKAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIABg4QgEAOgFALIgCACIgBgCQgCgGgDgEQALgQAFgWIgLABQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgJQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIALAAIAAgJIgBgRIANABIACABIgBACIgBANIAAAJIAJAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAJIAAABIgCABIgCgBIgGAAQADALAIAKIgFAJIgBACQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIgFgMIABA6IAAAEIgBABIgBAAgAkaA6IgBgDIgDgHQAQgCAMgDQgIgFgFgIIgGAAIgCABIgCgBIAAgBIAAgHIAAgBIACAAIAwAAIADAAIABgBQACAAADADQAEADAAACQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQgCAAgCACIgLAKQALADAQABIgEAHIgBAEIgBAAIgDAAQgSgCgNgGQgMAFgSADIgCAAIgDAAgAj3AnQAHgDAGgGIgYAAQAGAGAFADgAl5A6IgLAAIgCAAIAAgBIABgmQgJASgUAMIgDACIgCgDQgDgEgDgEQAVgLAMgRIgbAAIgCAAIAAgBIAAgKIAAgBIACAAIAiAAIAAgMIgYABIgBgBIAAgBIAAgnIAAgBIABAAIA+AAIABAAIAAABIAAAnIAAABIgBABIgZgBIAAAMIAjAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAABIAAAKQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIgcAAQALAQAVAKIgFAKQgBABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgDgBQgSgLgLgUIABAnIAAABIgBAAgAmSgXIAmAAIAAgSIgmAAgACnA5IgBgDIgDgJIAKAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIABgDIAAgaIgFACQgEABgBACIgCAAIgBgBIgCgNIAMgCIADgBIAAgYIgNAAIgBAAIgBgBIAAgJIABgCIABAAIANABIAAgIIgBgSIAOABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBADQgBACAAALIAAAIIALgBIABABIAAABIAAAJIAAABIgBAAIgLAAIAAAUIALgEIAAAHQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAIgDACIgHADIABAgQAAAKgFADQgDACgLABIgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAgAg7A6QAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAhGIAAgCIABAAIAsAAIABABIABABIAAA5QAAAIgDACIgFACIgKABIgDAAIgBgEIgDgHIAIAAQAEAAABgEIAAgKIgWAAIAAAZQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAgvAWIAWAAIAAgJIgWAAgAgvADIAWAAIAAgHIgWAAgAiMA3IgEgHQAPgDANgJIgEgLIgDgKIgTAAIgCANIADgGIACgBIABABIAMAIIABABIAAABIgFAGIgBABIgBAAQgHgGgGgDQgDAQgKAKIgCACIgDgCQgDgFgDgBQANgLABgYIgHAAIgCAAIAAgBIAAgJIABgBIABAAIAlAAQgDgQgCgVIgDAEIgPARIALgBIgCgEIgBgCIAGgCIABAAIABABQACAFACALIABABIgCABIgDACIgBAAIgBgBIgBgEIgSADIgFABIgBABQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgCgJIAEAAIAJgLIgOgPIgBgBIABgBIAFgFIAAgBIACABIACACIAGgLIACgFIAJAFIABABIgBACIgCABIgJAOIAFAEIAEgGIACgEIAIAEIAAgDIgBgTIAMABQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIgBACIgBAHIAAAJIAFgGIABgBIABABIABACQAEgFADgFIACgFIAIAEIACACIgBABIgDACIgIAMIAFAGIAHgMIAIAEIACACIgCACIgEAEIgPASIAMgBIgDgGIAAgBIABgBIAFgBIABgBIABABIAHARIAAABIgCAAIgFACIgBABIgBgBIgBgEIgKACIAHAEIABABIgFAEIAPAAIABAAIAAABIAAAJIAAABIgBAAIgfAAIAEANIAGgHIAEgGQAGADADADIABABIgBACIgEAEIgKAKQAFAHAEAAQAEAAABgOIAHADQAAABABAAQAAAAABABQAAAAAAABQABAAAAABIAAACQgCAKgEAEQgCADgGABQgJAAgKgNQgKAIgNAFIgDAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAgBgBgAhyAEIAQAAIgHgFIgBgBIABgBIADgCIgDAAIgEABIgCABQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBgBAAIgBgIIABAAIAIgKQgFgIgIgHQABAWADAUgAGPA4QgOgKgLgRIgBgBIAJgGIACgBIACABQAKAQAPAJQgEADgCAFQgBAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAgADGA3IgHgGQAOgKAFgVIABgHIALACQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIgCACIgDAKQAFAJAIADIAAghIgdAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAgBIAAgIIABgBIABAAIBKAAIABAAIAAABIAAAIIAAABIgBAAIggAAIAAANIAZAAIABAAIAAABIAAAJIAAABIgBAAIgZAAIAAANIASACIASgBIgCAIIgBAFIgEAAIgJAAQgVgBgLgEQgLgEgHgKQgEAJgJAJIgCACIgDgDgAFHA3QgDgEgEgDQAMgHAJgMIAEgIIAMAGQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIgDACIgDADQgJANgLAJIgDABIgDgCgAABA2QgEgCAAgHIAAghIgBgMIANAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgBACIgBAHIAAAGQALgEAJgGQAFgCACgDIAIAJIACACQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAgBAAIgFADIgdANIAAAJQAAAEACAAQACACAJAAQAKAAADgDQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAIABgIIAJADIACABIABACIAAACIgCAKQgBACgEACQgFAFgQAAQgQgBgEgCgABRAwQgGgEAAgKQAAgKAHgGQAHgIASgIQgBgFgCgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAAAAAQgHAAgIAHQgGAEgIAKIgKgIQARgRAJgSIgXAAIAAgMIAcABIAGgRIANACIgFAOIAhgCIABALIgnADQgFAIgGAHIgDACIAAABIAEgCQAFgEAGAAQAGAAAFAEQAEAEABAGIAagLIAFAMQgSAFgMAGIAAAZIgMAAIAAgUQgMAHgEAEQgEAEAAAEQAAAFAFACQAGACAMAAQAPAAATgCIABAMQgSACgSAAQgUAAgIgGgAFFATIgBAAIgBgBIAAgLIABgBIABgBIASABIAAgZIgLAAIgDAAIgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgKIABgCIABAAIAPABIAAgHIgBgUIANABQABAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIgBADIAAAOIAAAHIATAAIAAgHIgBgUIAOABQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIgBADIAAAOIAAAHIAPgBIACABIAAABIAAAKIAAABIgCAAIgPAAIAAAZIAUgBIABABIAAABIAAALQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAgAFkAGIATAAIAAgZIgTAAgAjVAQIg/AAIgBAAIAAgBIABgSIgBgDIABgDIgCACIgEACIgCgCIgEgGQAIgHAFgJIADgGIAJACQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAAAIgBACIgCACIAOAAIACgDIABgEIALACIABABIgBABIgCADIAAAAIAXAAIABAAIAAACIAAAFIAAABIgBAAIgYAAIAAAGIAUgBIACABIAAABIAAAEIAAACIgCAAIgUAAIAAAEIAUAAIACAAIAAACIAAADIAAABIgCAAIgUAAIAAAGIAZAAIACAAIAAABIAAAFIAAABIgCAAgAkJAJIAQAAIAAgGIgQAAgAkJgDIAQAAIAAgEIgQAAgAkJgOIAQAAIAAgGIgQAAgAkjAKIgdAAIgBAAIAAgCIAAgIIAAgBIABAAIAdAAIABAAIAAABIAAAIIAAACIgBAAgAABgGQgEgCAAgHIAAgfIgBgMIAMAAQABAAAAABQABAAAAAAQAAAAAAAAQABABAAAAIgBACIgBAHIAAAGIATgIIAHgFIAIAIIACADQAAAAgBAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgFACQgLAGgRAFIAAAIQAAABAAABQAAAAAAABQABAAAAABQAAAAABAAIAKABQALAAACgDIACgEIAAgHQADADAGABIACABIABACIAAABIgCAJIgEAGQgEACgSAAQgPAAgEgBgAkjgHIgdAAIgBAAIAAgBIAAgJIAAgBIABAAIAdAAIABAAIAAABIAAAJIAAABIgBAAgAEMgLIg6AAIgBAAIAAgBIAAgpIAAgCIABgBIA6AAIABABIABACIAAApIgBABIgBAAgADegVIAiAAIAAgIIgiAAgADegmIAiAAIAAgHIgiAAgAgQgUIgDgFIgnAEIgFABIgCABQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAgBgBIgCgLIALAAIAIgSIACgJIANACQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIgBACIgDAEIgHAQIAUgCIgGgIIAAgBIABgCIAHgEIABAAIABABQAHAJAHAPIAAABIAAABIgIAEIgBABIgBgCgAkegYIgoAAIgBgBIgBgBIAAgJIABgCIABAAIAoAAIABAAIAAACIAAAJIAAACIgBAAgAjmgiIgJAAIgBAAIAAgBIAAgDIAAgDIgPAAIAAAGIAAABIgCAAIgIAAIgCAAIAAgBIAAgDIABgDIgRAAIgBAAIAAAAIAAgIIAAgBIABAAIARAAIAAgBIgBgIIALAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIAAACIgBAEIAAACIAPAAIAAgJIALAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIgBACIgBAEIAAACIASAAIACAAIAAABIAAAIIgBAAIgBAAIgSAAIABAGIgBABIgBAAgAkhgrIggAAIgBAAIAAgBIAAgJIAAgCIABAAIAgAAIACABIAAABIAAAJIAAABIgCAAg");
	this.shape.setTransform(-164.5,210.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-210.5,204.2,92.1,12.100000000000023), null);


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj2AfIAMgJQAPAMAMARIgNAJQgKgQgQgNgAljA6IgBAAIgBgBIABhAIgMAMIgCACQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBgEgEgFQAUgTAKgZIADgJIAMADQABABAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACIgDAFIgIARIAABVQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAAAAAgAo9A6IgJAAIgCAAIAAgBIAAg1IABgBIABAAIA1AAIABAAIAAABIAAA1IAAABIgBAAIgKAAIgBAAIAAgBIAAgFIgfAAIAAAFIgBABIgBAAgAo7AqIAfAAIAAgKIgfAAgAo7AWIAfAAIAAgJIgfAAgAm5A5IgEAAIgCgEIgDgKIASABQAGABACgFIADgQIgvAAIgFAHIgCABIgBAAIgKgCQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAAAIABgBQAIgLAGgOIgfAAIAAAAIAAgBIAAgJIAAgCIAAAAIByAAIABAAIABACIAAAJIgBABIgBAAIhEAAIgEAKIA3gBQAAAAABAAQAAAAAAAAQAAABAAAAQABABAAAAIgCANQgCAMgDAIQgCAGgFADQgEACgHAAgAk6A1QgDgBgCgEQgCgDAAgGIAAhRIgBgPIAPABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBADQAAACAAAHIAAAgQAMgIAMgLIAHgJIAKAJIACACQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBABIgGAEQgQAPgSAKIAAAeIAAAGIADACQADABAKAAQAKAAADgDQADgDABgRIAKAFIACABIABACIAAACQAAAKgCAFQgDAEgDACQgGAFgRAAQgSAAgFgDgADsAsQATgGAGgMQAGgLAAgSIAAgVIAPAAIAAATQAAAZgLAPQgHAMgSAIgABHAsQARgGAJgHQALgIAEgNQAFgNAAgWIgxAAIAAAdIgPAAIAAgqIAhAAIAAgTIAOAAIAAATIAiAAQAAAegHASQgFASgNALQgLAKgUAGgAHLAqIABAAQAZAAANgHQAMgFAAgNQgBgHgFgFQgEgEgIABQgPAAgLALQgGAHgBAFIgNgCIAEg5IAOACIgFAjIgBAHIAEgGQANgNASAAQAPAAAIAIQAIAHgBAOQAAAKgEAHQgFAGgIAEQgOAHgcABgAiVgCIALgIQAMALAKAMQARgWAIgWIhEAAIAAgNIBRAAIAFAGQgOAkgUAaQAHAKAIAMIgNAJQgTgjgZgWgAJIAqQATgEAIgKQAIgKAAgPQAAgUgJgKQgGgIgLAAQgCAqgKAXQgFAKgFADQgFAEgGAAQgKAAgGgLQgGgKAAgQQAAgZAPgQQAHgIAJgDQAJgEAKAAQAsAAAAAyQAAAogqAJgAIwgWQgJAMAAAVQAAALADAGQACAFAEAAQAEAAACgCIADgHQAEgMADgQQADgQABgOQgLABgJALgAgMAxIAAhjIANAAIAABSQARgMALgbIAKAKQgJAUgMALQgJALgOAIgAg/AtQAMgKAFgPQACgHABgPIAAgvIAPAAIgBA1QgCAMgDAJQgEAQgOAMgAFuAzIgDgMIANACQAEgBADgBIADgFQAEgKgBgcQAAgKgCgDQgBgCgDgBIgMABQgKAogOAfIgNgEQAPggAJgjIgXADIgBgMIAagCIAGgaIANACIgFAXIALAAQAIAAAFAGQAEAGABANQgBAggDANQgCAHgFADQgFADgHAAIgOgBgACWAxIAAgLIAaAAIAAg0IgXAAIAAgMIA9AAIAAAMIgZAAIAAA0IAcAAIAAALgAp2AxIgBgBIAAgBIAAhiIAAgCIABAAIAiAAIABAAIABACIAABdIgBABIgBABIgJAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgFIgMAAIAAAKIgBABIgBABgAprAZIAMAAIAAgcIgMAAgAprgOIAMAAIAAgbIgMAAgAGRgmIAMgFQANAVAHAaIgNAGQgGgcgNgUgAEggHQAIgFAFgKQAEgHAAgGIhIAAIAAgNIBXAAIADAFQgDAQgGALQgFAKgKAIgApOgDIgCgBIAAgBIAAgJIAAgBIACAAIApAAIAEgMIABgGIAMACQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAAAIgBACIgCAEIgEAJIASAAIACAAIAAABIAAAJIAAABIgCABgAo/gSQgCgHgCgEIAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAHgCIABAAIACABIAEALIAAABIgCABIgIACIgBABIgBgCgAnkgRQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAgjIAAgBIACAAIBKAAIACAAIAAABIAAAjQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAgAnYgdIAyAAIAAgOIgyAAgAHkgoIgWgGIAFgKIAYAFIAUAGIgIANQgHgFgMgDgApLgiIgBAAIAAgCIAAgJQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAYAAIAAgCIgBgLIAOABQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAIgBADIAAAHIAAACIAbAAIABAAIAAABIAAAJIAAACIgBAAg");
	this.shape.setTransform(-143.5,204.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-206.7,198.7,126.49999999999999,12.100000000000023), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJpAhIALgJQAQANALAQIgMAKQgLgRgPgNgAIzA+IgJAAIgBAAIAAgCIABhIIgDAEIgDACIgCgBIgEgFIABAMIgBABIgBAAIgSAAIgCAIIAXgBIABABIAAABIAAAnQAAAGgDACQgEACgIAAIgEAAIgBgDIgDgIIAJABQABAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBIAAgcIgQAAIgDAOIAGgBIgCgFIgBgBIABgCIAFgCIABAAIABABQAEAJADAIIAAABIgCABIgEACIgBABIgBgBIgBgEIgOAEIgEABIgBABIgCgCIgDgJIAFAAIADgQIgJAAIAAApQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgJAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgxIAAgBIABgBIAUABIABgIIgSAAIgBAAIgBgBIABgWIgBgLIALABIACABIgBACIgBAIIAAAPIAdAAIAAgQIAAgLIALABIACABIgBACIgBAGIAAAHQALgOAFgSIACgKIAMADIABACIgBACIgHAQIANAAIADgNIACgIQAGABAEACQABAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIgCACIgCAFIgDAJIAOAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAABIAAAJQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgPAAIAAAOIAMAAIABAAIAAABIAAAJIAAABIgBAAIgEAAIgIgBIAAAOIAMAAIABAAIAAACIAAAJIAAABIgBAAIgEAAIgIAAIAAASIAQgBIACABIAAABIAAAJIAAABIgCAAIgnAAIAAAFIgBACIgBAAgAI1AsIALAAIAAgSIgLAAgAI1AOIALAAIAAgOIgLAAgAI1gKIALAAIAAgOIgLAAgAFxA5QgCgEgEgEQASgGAJgNQAIgKACgQIgTAAIgBAAIAAgBIAAgJIgNAKIgCACIgDgDQgEgFgEgCQAagQAMgbIACgIIAOAEIACACIgBADIgEADQgIAUgPAPIBEAAQgRgSgLgXIAAgBIABgBIAJgEIACAAIABABQAHAPAMAOQALALAMAIQgDADgEAFQgBABAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgDgCIgMgJIAAAMQgBATgDASQgBAIgEAEQgGAEgIgBIgJAAIgDgBIgBgDQgCgHgDgEIAQACQADAAACgCIADgGQACgNAAgUIgXAAQgEAogjAPIgDACQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAgBgAi1AuQATgHAGgLQAGgLAAgRIAAgXIAPAAIAAAUQAAAZgLAPQgHAMgSAIgAlaAuQARgGAJgHQALgJAEgNQAFgMAAgXIgyAAIAAAdIgOAAIAAgoIAgAAIAAgTIAPAAIAAATIAiAAQAAAdgHASQgFASgNAKQgKAKgVAHgADIARQgRAYgeAOIgHgKQAZgNARgWQAOgTAEgXIg1AAIAAgMIBEAAIADAEQgGAbgLARQAQATAPAYIgOAJQgLgVgNgSgAm+A4IAAhsIAOAAIAAAlQAcAIAWALIgIAPQgRgNgZgGIAAA4gAEmAtQAVgFAHgLQAIgJgBgQQAAgTgIgKQgHgHgKgBQgCAqgKAXQgFAKgFAEQgFACgGAAQgKAAgGgKQgGgKAAgQQAAgZAPgQQAHgIAKgDQAIgDAKAAQAsAAABAyQgBAngqAJgAEQgTQgKALAAAUQAAAMADAGQADAFAEAAQADAAABgCIAEgHQAEgMADgQQAEgQAAgOQgLABgIAMgApMAFQgGgUgDgbIAPgBQAFA3AVAiIgOAIQgMgXgGgagAqOAuQAWgiADg3IAQABQgEAjgHAXQgGAVgLARgAkLAzIAAgMIAaAAIAAgzIgXAAIAAgMIA9AAIAAAMIgZAAIAAAzIAcAAIAAAMgAgGgUQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAQgLAWgOAaIgMgHQAQgbALgaQADgFACgCQACgBAEgBQAEABADABIADAGIAzBHIgMAKIgthEgAA+AIIAAgOIBJAAIAAAOgAojAIIAAgOIBKAAIAAAOgAiBgFQAIgGAFgIQAEgIABgGIhIAAIAAgMIBVAAIAEADQgDARgFALQgGAKgKAHgAH8gJIgFgFIAJgHIgGgEIgCgBIACgBIADgEIABgBIABABIAHAFIABgDIAEgFIAGAEIABACIgBABIgCACIgDAEIAFAFIABABIgBABIgDAEIgBABIgBAAIgGgGIgGAGIgDABIgBgBgAAOgtIAJgDQAFAJAEANIgIACQgEgMgGgJgAAfgyIAIgCQAGAJADALIgIAEQgFgMgEgKgAmbg3IAJgDQAFAJAEANIgIADQgEgMgGgKgAHngkIgBAAIgBgBIAAgIIABgBIABgBIAYABIAAgCIgBgKIANABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAAAABIgBACIAAAFIAAACIAWgBIACABIAAABIAAAIIgBABIgBAAgAmLg7IAIgCQAGAJAEALIgJADQgEgNgFgIg");
	this.shape.setTransform(-139.6,200.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-205.1,194.3,131,12.5), null);


(lib.title2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFeBPIgJgIIAJgHIgeAAIABARQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgNAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgRIgpAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgLQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIApABIAAgIIgfAAIgBAAIgBgCIAAgpIABgBIABAAIAfABIAAgIIglABIgCgBIAAgCIAAgJIAAgCIACAAIAlAAIAAgJIgrAAIgCAAIAAgBIAAgLIAAgCIACAAIAqAAIAAgKIgcAAIgCAAIAAgCIAAgJIAAgCIACAAIAcAAIgBgOIASABQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIgBADIgBAIIAdAAIACAAIAAACIAAAJIAAACIgCAAIgdAAIAAAKIAsAAIgBgKIgBgbIASACQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAEQgBACAAAIIAAATIAmAAIACAAIAAACIAAALIAAABIgCAAIgmAAQABAeADASQAGgKADgKQAEgKAAgGIAPAFQAAABABAAQABAAAAABQAAAAABAAQAAABAAAAIgGAMQgJAVgKARQAHAVAGAAQACAAACgFIADgRIAJAGQAEACAAACIAAAFQgDAQgEAGQgFAGgIAAQgNAAgLgaQgKAOgNAKIgEADQgBAAgDgEgAFlAzIAAABIAAAGQAKgKAHgKQgHgZgCgrIgsAAIgBAHIAAACIAkAAIACAAIAAACIAAAJIgBACIgBABIgkgBIAAAIIAggBIABABIABAAIAAApIgBACIgBAAIggAAIAAAIIAjgBIACABgAFAAhIATAAIAAgIIgTAAgAEeAhIATAAIAAgIIgTAAgAFAAQIATAAIAAgIIgTAAgAEeAQIATAAIAAgIIgTAAgACRBTIgBgBIgBgBIAAg3IABgBIABgBIBQAAIACABIAAABIAAA2QAAAAAAABQAAAAAAAAQAAAAgBABQAAAAgBAAIgOAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgFIgwAAIAAAGIAAABIgCABgAChA7IAwAAIAAgTIgwAAgAmCBSIgOAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIABhNQgFATgIAPQAAAAAAABQgBABAAAAQAAAAgBABQAAAAAAAAIgCgDQgDgJgDgEQAPgXAHgeIgQAAQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgNQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIARAAIAAgNQAAgQgCgHIARABQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIgBADQgBADAAAOIAAANIANAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAANIgBACIgBAAIgEAAIgIAAQAEAOALAPIgGAMQAAAAgBABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBgBAAAAQgEgJgDgKIACBSIAAAFIgBACIgBAAgAlTBNQgDgFgEgEQAVgFASgNQgDgGgCgIIgEgOIgbAAIgDASIAFgIIACgBIACABQAJAEAIAHIABABIgBACIgFAIIgCACIgCgBQgIgIgKgFQgFAXgMANIgDADIgEgDQgFgFgFgDQATgPACghIgKAAIgCAAIAAgCIAAgMIAAgBIACgBIAzABQgFgXgBgeIgGAGIgTAZIAOgBIgCgHIgBgCIACgBIAFgCIABAAIACABQADAHAEAQIAAABIgCACIgFABIgCAAIgBAAIgBgFIgaADIgFACIgDAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIgDgNIAFABIANgQQgIgKgLgKIgBgCIABgBIAGgHIACgCIABABIADADIAJgPIADgGQAGACAGADQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIgCACIgDADQgGAKgGAIIAGAHIAGgJIADgHIAMAHIAAgEQgBgRgBgKIAQABQABAAABAAQAAAAABAAQAAABABAAQAAAAAAABIgBADIgBAKIAAAMIAGgIIACgBIABABIADACIAIgOIADgHIAMAGQABAAAAAAQAAABAAAAQABAAAAABQAAAAAAAAIgCACIgCADQgGAKgHAHIAGAIIAGgJIAFgJIAMAHQAAABAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgCACIgFAGIgUAYIAPgCIgDgGIgBgCIADgBIAGgDIABAAIACACQAEAIAEAOIABABIgDACIgGACIgCABIgBgCIgCgFIgNACIAJAHIABABIgBACIgFAEIATgBIACABIABABIAAAMIgBACIgCAAIgqAAIAGASIAIgJIAFgJIANAHQABABAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAABgBAAQgCABgDADQgGAIgIAHQAHAJAFAAQAGAAABgUIAJAFQAFADAAACIgBAEQgCANgFAGQgEAFgHAAQgOAAgMgRQgPAKgRAGIgFACQgBAAgCgFgAkvAHIAVAAIgJgHIgCgBIAGgGIgKADIgDAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIgCgMIACAAIALgNQgIgLgKgKQABAfAFAcgAjjBRQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAhiIABgCIABAAIA9AAIABAAIABACIAABQQAAAKgEAEQgDACgEABIgNABIgFgBIgCgEQgBgHgCgEIALABQAFAAAAgGIAAgNIgdAAIAAAiQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAjTAgIAdAAIAAgMIgdAAgAjTAGIAdAAIAAgLIgdAAgABbBRQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgBgEQgCgJgDgEIANAAQAGAAAAgHIAAgkIgOAGQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIgDgRIARgEIADgBIACgBIAAggIgTAAIgCAAIAAgCIAAgNIAAgCIACAAIATAAIAAgJIgBgZIASABQABAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIgBAEQgBACAAAQIAAAJIAPAAIACAAIAAACIAAANIAAACIgCAAIgPAAIAAAbIARgIIAAALIAAABQAVgLAOgTQAEgIACgFIARADQAAAAABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAVAYAgALQgEAFgCAHQgCAFgBAAIgFgCQgMgGgLgIIAAAKIAAABIgCABIgtAAIgBgBIgBgBIAAgJQgKAJgMAGIgEACQgBAAgCgFIgEgGIgJAEIABAuQAAAOgGAEQgGAEgOAAIgCAAgADOAAQgMgKgKgNQgIANgKAKIAoAAIAAAAgAiQBMQgGgDAAgKIAAguIgBgRIASABQAAAAABABQABAAAAAAQAAAAABABQAAAAAAAAIgBAEIgBAJIAAAJQAPgGANgHIAJgIIALAMIACADQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgIAEQgaAMgNAFIAAANQAAAFADABQADACAMAAQAOAAADgEQACgCABgEIAAgKQAHADAGACIAEABIAAACIAAADQgBAJgCAEQgCAEgDADQgJAFgVAAQgWAAgHgDgAghBEQgHgHAAgNQAAgNAJgJQAKgKAXgMQgBgHgBgDQgCgDgFAAQgJAAgLAJQgIAHgMAOIgNgMQAYgXAMgZIggAAIAAgQIAnAAQAEgKAEgNIARADIgHAUQAagBAVgDIAAAQIg2ADQgGAMgIAJIgEAEIABABIAEgEQAIgFAIAAQAIAAAGAGQAFAFACAJIAkgPIAHAQQgYAHgSAIIAAAjIgRAAIAAgbQgPAJgGAGQgFAFAAAGQAAAHAHADQAHADARAAQAUAAAbgDIABARQgYACgaAAQgbAAgLgIgAiQgIQgGgDAAgJIAAgrIgBgRIASABQAAAAABAAQABAAAAAAQAAABABAAQAAAAAAABIgBADIgBAKIAAAJIAagMQAGgDAEgEIALALIACADQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAIgIADQgPAHgXAIIAAALQAAAEADABIAOABQAPAAADgDQABgBABgEIAAgLIANAGIADABIABADIAAACQgBAJgCAEQgCAEgDACQgHAFgYAAQgUAAgHgDgAipgaIgDgIQgWADggADIgHACIgDAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAIgDgQIAPAAQAGgMAFgNIADgNIARAEQABAAABAAQAAABAAAAQABAAAAABQAAAAAAAAIgCAEIgDAFIgLAVIAdgCIgHgMIgBgBIACgCIAIgFIACAAIACABQAJAMAKAVIABABIgCACIgMAHQgBAAAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAgADVggIgNAAIgCAAIAAgCIABgOIgdAAIABAOIgBABIgBABIgOAAIgCgBIAAgBIABgOIgUAAIgCAAIAAgCIAAgMIAAgBIACgBIAUABIgBgSIARABQAAAAABABQAAAAAAAAQAAAAABAAQAAAAAAABIgBACIgBAJIAAAEIAdAAIAAgCIgBgQIAQABQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAIgBADQgBABAAAHIAAAEIAYgBIACABIAAABIAAAMIAAACIgCAAIgYAAIAAAOIAAACIgCAAgAGPgyQgEgKgIgJIAAgBIACgCIAIgEIACgBIABABQAIAJAFAKIAAACIgBACIgLAFQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape.setTransform(1.475,39.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title2, new cjs.Rectangle(-41,31.4,85,16.5), null);


(lib.screen = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.Bitmap25();
	this.instance.setTransform(-83,-91,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.screen, new cjs.Rectangle(-83,-91,167.2,188.8), null);


(lib.logomc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhrCkQgZgHgRgSQgRgSgGgZQgDgTACgTQAEgdAWgUQAQgNAVgIQAbgIAUgEIAigGQAUgDAXgHIAJgDQAHgCAGgHQAFgJgDgJQgEgPgPgFQgVgHgWAIQgPAGgFAPQgEAJABAKIhtgDIgCgGQgCgRAFgQQAOgtAsgSQAUgIAQgDQBCgMBEAPQAUAEAUALQAhATAJAjQAHAdAAAZIACBjQAAAiADAqQABAOAHALIh4AAQgEgEgCgHIgIgWQgSAWgXAJQgeAMgfAAQgXAAgXgHgAAAAfIgkAMQgIADgGAFQgKAJADANQABAIAGAFQAGAHAJADQALACALAAQAOgCALgFQAOgGAIgNQAHgLABgMQACgQgBgSQgXALgUAFg");
	this.shape.setTransform(-116.9104,-32.2299,0.2299,0.2299);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhrCkQgZgHgRgSQgRgSgGgZQgEgTADgTQADgdAXgUQAPgNAWgIQAcgIASgEIAjgGQASgDAZgHIAJgDQAIgDAEgGQAGgJgDgJQgEgPgQgFQgTgHgXAIQgPAGgGAPQgDAKAAAJIhtgDIgBgGQgCgQAFgRQANgtAsgSQAUgIARgDQBCgMBEAPQATAEAVALQAhATAJAjQAHAaAAAcIABBjQABAnADAlQABAOAHALIh4AAQgEgEgDgHIgHgWQgSAVgXAKQgfAMgeAAQgXAAgXgHgAAAAfIglAMQgIADgFAFQgKAJACANQACAHAFAGQAGAGAKAEQAKADAMgBQANgCAMgFQANgGAIgNQAHgJACgOQACgQgCgSQgXALgTAFg");
	this.shape_1.setTransform(-100.187,-32.2299,0.2299,0.2299);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgxCmQgjgHgdgWQgtgjgOg1QgKgiADgjQAGg8ArgpQAngmA3gJQAUgDAQAAQASAAASADQA4AJAnAmQArAoAGA9QADAjgKAiQgOA1gtAjQgdAWgjAHQgYAGgaAAQgZAAgYgGgAgJhWQgSAEgLAQQgKAPgEAQQgFAiAEAfQADAOAGARQAIARARAHQATAJARgIQAUgHAHgSQAIgRABgOQAFgfgFgiQgEgQgJgPQgFgIgJgFQgMgIgOAAIgJABg");
	this.shape_2.setTransform(-84.1285,-32.2297,0.2299,0.2299);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjHDjIAAnFID6ABQAsADAkAXQAjAYATApQATApgFAtQgFAwggAjQggAjgwALQgfAGgeAAIhSAAIAACMgAg9gSIBSgBQAWgBAMgRQAHgJACgLQABgMgBgGQgCgSgNgMQgNgMgSAAIhPAAg");
	this.shape_3.setTransform(-125.3063,-33.7359,0.2299,0.2299);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOCgQgfgJgXgVQgTgSgHgVQgGgQAAgPIAAgHIB2AAQAAAIADAJQAEAKAHAHQAHAFAHADQAQAGAPgDQAMgCAKgJQAJgKgCgMQgDgMgMgEQgNgFgNgCIhGgNQgTgEgQgHQgkgOgOgjQgHgSAAgVQABgMAEgMQAJgaAWgRQAZgUAfgHQAWgFAYgCQAogCApAHQAUAEANAFQARAHAOALQAQAMAHAUQAHASAAAVIhyAAQAAgKgFgIQgGgIgKgDQgSgHgUAGQgLADgGAKIgBACQgCAFACAGQACAFAFADIAJADIAUADQAhAFAnALIANAEQAfAJAXAUQARANAHAXQAKAegIAdQgJAcgYAVQgLAJgLAGQgdAOgdAEQgXAEgXAAQgpAAgogMg");
	this.shape_4.setTransform(-92.2496,-32.2343,0.2299,0.2299);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAsCoIAAi7QAAgIgCgKQgFgQgQgHQgRgHgRAGQgRAFgJAQQgIANAAAPIAAC0Ih9AAIAAlDIB1AAIADAiQAXgUAbgMQAugWAxAOQA3AQARA3QAIAXAAAbIAADQg");
	this.shape_5.setTransform(-108.5549,-32.3737,0.2299,0.2299);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAsCoIAAi7QAAgKgDgIQgFgQgQgHQgQgHgRAGQgRAFgKAQQgHANAAAPIAAC0Ih9AAIAAlDIB1AAIADAiQAXgUAbgMQAugWAxAOQA3ARARA2QAIAZAAAZIAADQg");
	this.shape_6.setTransform(-75.6088,-32.3737,0.2299,0.2299);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag8CiIAAlDIB5AAIAAFDg");
	this.shape_7.setTransform(-69.6704,-32.247,0.2299,0.2299);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag8ArIAAhVIB5AAIAABVg");
	this.shape_8.setTransform(-69.6704,-37.967,0.2299,0.2299);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRCrQgugFglgcQgegWgTghQgOgYgFgdQgGgoAKgmQANguAggfQAhgfAvgKQAzgKAyANQAkAJAcAaQARAQALAUQANAagCAbIhvAAQgEgWgRgOQgMgJgOAAQgNgBgMAIQgRAKgGATQgOArANAtQAFASAOAOQARAQAWgDQAPgDAIgKQAKgLACgOIADgTIB1AAQADA1glAmQgkAmgzAKQgWAFgXAAIgWgBg");
	this.shape_9.setTransform(-63.9591,-32.2242,0.2299,0.2299);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgRAMgXALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_10.setTransform(-24.8185,513.0914,0.2766,0.2756);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgQAMgYALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_11.setTransform(-30.8341,513.0914,0.2766,0.2756);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag/CeQgXgFgQgHIAAhIQAUAOAXAIQAWAIATAAQAZAAALgHQALgHAAgQQAAgPgMgKQgNgLgggNQgogRgRgUQgRgVAAghQAAgqAhgbQAhgbA0AAQAPAAAWAEQAQADASAGIAABGQgQgKgSgHQgUgHgSAAQgVAAgLAIQgLAIAAAPQAAAPAJAJQALAJAgAOQAtARARAVQARAWAAAfQAAArghAbQgiAbg4AAQgRAAgagFg");
	this.shape_12.setTransform(-39.2491,514.9105,0.2766,0.2756);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AA/CbIg+jfIAAAAIhADfIhNAAIhak1IBMAAIA6DtIABAAIBFjtIBEAAIA9DuIACAAIA4juIBGAAIhbE1g");
	this.shape_13.setTransform(-48.9916,514.9105,0.2766,0.2756);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhzB4QgrgrAAhJQAAhMAsgtQArgsBMAAQBJAAApArQAoArAABKQAABLgrArQgrAthLAAQhHAAgqgqgAg8hJQgWAaAAAxQAAAwAWAaQAWAZAoAAQAnAAAWgZQAUgaABgyQAAgxgWgaQgWgZgmAAQgoAAgWAbg");
	this.shape_14.setTransform(-60.1517,514.9243,0.2766,0.2756);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhzC+QgjgoAAhHQAAhMAmguQAnguBAAAQAcAAAXAKQAXAKAMASIACAAIAAizIBIAAIAAHIIhIAAIAAgpIgCAAQgQAXgZALQgaAMggAAQg7AAgigpgAg1gCQgVAcAAAzQAAAvAUAZQAVAZAiAAQAiAAAWgaQAWgaAAgqIAAghQAAghgVgVQgVgXggAAQgmAAgUAcg");
	this.shape_15.setTransform(-70.1293,512.9536,0.2766,0.2756);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("ABCCeIAAisQAAgqgPgVQgOgVggABQgeAAgTAXQgVAXAAAjIAACuIhIAAIAAk1IBIAAIAAAqIACAAQARgZAZgLQAYgMAhAAQAxAAAbAgQAaAfAAA/IAAC9g");
	this.shape_16.setTransform(-79.5607,514.8209,0.2766,0.2756);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgkDdIAAk1IBIAAIAAE1gAgfiUQgNgLABgSQgBgSANgMQAOgNARAAQATAAAMANQANANABARQgBASgNAMQgMAMgTAAQgSAAgNgNg");
	this.shape_17.setTransform(-86.3577,513.0914,0.2766,0.2756);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABaDYIhXlFIgCAAIhVFFIhaAAIh4mvIBRAAIBVFVIABAAIBelVIBPAAIBYFUIACAAIBRlUIBOAAIh1Gvg");
	this.shape_18.setTransform(-96.4322,513.2223,0.2766,0.2756);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_19.setTransform(-115.3157,518.4315,0.2766,0.2756);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_20.setTransform(-125.7635,518.4315,0.2766,0.2756);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_21.setTransform(-115.3157,508.02,0.2766,0.2756);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_22.setTransform(-125.7635,508.02,0.2766,0.2756);

	this.instance = new lib.Bitmap8();
	this.instance.setTransform(-131,435);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logomc, new cjs.Rectangle(-131,-38.9,108.5,562.1), null);


(lib.light2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#234F9C","rgba(1,11,25,0)"],[0,1],0,-0.1,0,0,-0.1,152.9).s().p("AwjQkQm4m2AApuQAApsG4m4QG3m3JsAAQJtAAG4G3QG3G4AAJsQAAJum3G2Qm4G4ptAAQpsAAm3m4g");
	this.shape.setTransform(0,270);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.light2, new cjs.Rectangle(-150,120,300,300), null);


(lib.light = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#234F9C","rgba(1,11,25,0)"],[0.298,1],0,0,0,0,0,229.4).s().p("A42Y3QqUqTAAukQAAujKUqTQKTqUOjAAQOkAAKTKUQKUKTAAOjQAAOkqUKTQqTKUukAAQujAAqTqUg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#234F9C","rgba(1,11,25,0)"],[0.298,1],0,0,0,0,0,232.7).s().p("A5OZPQqcqdAAuyQAAuxKcqdQKdqcOxAAQOyAAKdKcQKcKdAAOxQAAOyqcKdQqdKcuyAAQuxAAqdqcg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.light, new cjs.Rectangle(-228.3,-228.3,456.6,456.6), null);


(lib.flowermc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap10();
	this.instance.setTransform(-162,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.flowermc, new cjs.Rectangle(-162,-125,324,250), null);


(lib.CTAmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAGBAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgpQAAgBAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIAkAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAABIAAAnQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgFAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgFIgXAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAANAwIAXAAIAAgVIgXAAgABRA/IgBgBIAAgiIgdAAIgBgBIAAgGIABgBIAdAAIAAgVIgYABIgBgBIAAgGIABgBIAYAAIAAgUIgaABIgBgBIAAgGIABgBIAjAAQAGgMADgJIACgHIAIADIACACIgCACIgLAVIAXAAIABABIAAAGIgBABIgggBIAAAUIAbAAIABABIAAAGIgBABIgbgBIAAAVIAjAAIABABIAAAGIgBABIgjAAIABAiIgBABgAD3AIQgFgEAAgEQAAgEAEgEQAXgXAWgbIAJAHQgVAYgXAWQgDADAAACQAAABAEADQAYAUAZAcIgIAHQgXgagcgZgACaA0QgGgHAAgPIAChXIAKAAIgCBWQAAAMAEAEQAFAFALAAQAQAAAJgKQAIgJAEgSIAKAFQgKApglAAQgRAAgHgHgAjBAyQAcAAANgHQAHgEAEgFQACgFAAgIQAAgJgGgFQgFgFgJAAQgRAAgNAOQgFAGgDAGIgLgCIAFg+IAKACIgEAqIgBAHIADgFQAHgIAKgEQAJgEAJAAQAQAAAIAIQAIAHAAANQAAALgFAIQgEAFgIAFQgHAEgOACQgLACgNAAgAkkA1QgMgHAAgPQAAgOANgHQAJgGAOAAQATAAAIAGQgOgNgKgWIgnACIgBgJQATAAASgCIgIgYIAKgCIAIAZQAPgCAPgDIABAJIgcAFQALAWARASIgGAIQgRgJgRAAQgOAAgHAGQgGAFAAAHQAAASAjAAQALAAAIgBIAAAKIgTABQgWAAgLgGgAhpAMQAAgXAHgrIAKAAQgIAqAAAYQAAAaAEATIgKAAQgDgUAAgZgAhGAwQgHgFAAgLQAAgIACgHIAJABIgBANQAAAHAEADQAFACALAAQAOAAAOgBIAAAKIgbABQgSAAgGgFgAAHAIIgBgBIAAgFQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAiAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAAHgKIgBgBIAAgFIABgBIAiAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAFQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAAAgdIgBgBIAAgGIABgBIAuAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAgAhIgnQARgBASAAIARAAIAAAKIgSgBQgSAAgQACgAi+g0IAEgIQAcAGAQAHIgFAJQgRgIgagGgABFgoQgDgJgGgJIAAgBIABgBIAEgBIABgBIABABQAGAIAEAJIAAABIgBABIgEACIgCABgAAGgwQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgFIABgBIAlAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape.setTransform(-176.925,215.825);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgPgeIAeAeIgeAf");
	this.shape_1.setTransform(-134.9668,217.8488,1.1799,1.1799);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0075D4").s().p("AmPB/QgeAAAAgdIAAjDQAAgdAeAAIMfAAQAeAAAAAdIAADDQAAAdgeAAg");
	this.shape_2.setTransform(-171.0455,217.7718,1.1799,1.1799);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTAmc, new cjs.Rectangle(-221.7,202.8,101.39999999999999,30), null);


(lib.commc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap17();
	this.instance.setTransform(-156,-103);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.commc, new cjs.Rectangle(-156,-103,312,206), null);


// stage content:
(lib._160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(79.5,299.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(420));

	// CTA
	this.instance = new lib.CTAmc();
	this.instance.setTransform(98.5,222.75);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(257).to({_off:false},0).to({x:242.5},12,cjs.Ease.get(1)).wait(151));

	// txt
	this.instance_1 = new lib.txt5();
	this.instance_1.setTransform(218.5,186.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(245).to({_off:false},0).to({x:233.5,alpha:1},12,cjs.Ease.get(1)).wait(163));

	// txt
	this.instance_2 = new lib.txt3();
	this.instance_2.setTransform(214.55,156.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(237).to({_off:false},0).to({x:229.55,alpha:1},12,cjs.Ease.get(1)).wait(171));

	// txt
	this.instance_3 = new lib.txt2();
	this.instance_3.setTransform(210.8,144.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(233).to({_off:false},0).to({x:225.8,alpha:1},12,cjs.Ease.get(1)).wait(175));

	// txt
	this.instance_4 = new lib.txt1();
	this.instance_4.setTransform(210.4,131.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(229).to({_off:false},0).to({x:225.4,alpha:1},12,cjs.Ease.get(1)).wait(179));

	// title
	this.instance_5 = new lib.title2();
	this.instance_5.setTransform(44.9,82.35);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(217).to({_off:false},0).to({x:59.9,alpha:1},12,cjs.Ease.get(1)).wait(191));

	// title
	this.instance_6 = new lib.txtTitle();
	this.instance_6.setTransform(70.25,58.1);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(213).to({_off:false},0).to({x:85.25,alpha:1},12,cjs.Ease.get(1)).wait(195));

	// logo
	this.instance_7 = new lib.logomc();
	this.instance_7.setTransform(150.05,58.75);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(199).to({_off:false},0).to({alpha:1},24,cjs.Ease.get(1)).wait(197));

	// screen
	this.instance_8 = new lib.screen();
	this.instance_8.setTransform(79.85,677.15,0.75,0.75,0,0,0,0.4,0.7);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(64).to({_off:false},0).to({y:517.15},30,cjs.Ease.get(1)).wait(30).to({regX:0.9,regY:1.8,scaleX:0.7428,scaleY:0.7428,x:79.15,y:305.4},35,cjs.Ease.get(1)).wait(30).to({regX:3,regY:4.4,scaleX:0.321,scaleY:0.321,x:81.2,y:244},24,cjs.Ease.get(1)).wait(207));

	// flower
	this.instance_9 = new lib.flowermc();
	this.instance_9.setTransform(80.3,696.55,0.75,0.75,0,0,0,0.4,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({regX:0.8,regY:0.6,x:80.6,y:506.7},34,cjs.Ease.get(1)).to({regX:0.4,regY:0.4,x:80.3,y:506.55},30).to({regX:0.5,regY:0.5,scaleX:0.8,scaleY:0.8,x:80.4,y:500.4},30,cjs.Ease.get(1)).wait(30).to({regX:1.3,regY:1.8,scaleX:0.8319,scaleY:0.8319,x:82.05,y:274.35},35,cjs.Ease.get(1)).wait(30).to({regX:2.2,regY:3.4,scaleX:0.3596,scaleY:0.3596,x:82.2,y:230.4},24,cjs.Ease.get(1)).wait(207));

	// light
	this.instance_10 = new lib.light2();
	this.instance_10.setTransform(80.05,445.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({y:225.1},34,cjs.Ease.get(1)).to({_off:true},90).wait(296));

	// com
	this.instance_11 = new lib.commc();
	this.instance_11.setTransform(165.35,556.35,1.6666,1.6667,0,0,0,51.2,33.8);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(124).to({_off:false},0).to({regX:52,regY:34.6,scaleX:1.1587,scaleY:1.1587,x:140.25,y:346.6,alpha:1},35,cjs.Ease.get(1)).wait(30).to({regX:52.7,regY:35.6,scaleX:0.5009,scaleY:0.5009,x:104.85,y:261.6},24,cjs.Ease.get(1)).wait(207));

	// light
	this.instance_12 = new lib.light();
	this.instance_12.setTransform(150,330,1.8482,1.8482);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(124).to({_off:false},0).to({alpha:1},35,cjs.Ease.get(1)).wait(30).to({scaleX:0.6953,scaleY:0.6953,x:84.05,y:240.1},24,cjs.Ease.get(1)).wait(207));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#010B19").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(420));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-191.9,208.1,763.9,657);
// library properties:
lib.properties = {
	id: '542CFFE83C13439EB4A04353E49F32EB',
	width: 160,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap10.png?1631788957619", id:"Bitmap10"},
		{src:"images/Bitmap17.png?1631788957619", id:"Bitmap17"},
		{src:"images/Bitmap25.png?1631788957619", id:"Bitmap25"},
		{src:"images/Bitmap8.png?1631788957619", id:"Bitmap8"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['542CFFE83C13439EB4A04353E49F32EB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;