(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap14 = function() {
	this.initialize(img.Bitmap14);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,153,103);


(lib.Bitmap16 = function() {
	this.initialize(img.Bitmap16);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtTitle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFWBTIgOAAIgCgBIgBgBIABiHQAAgRgCgKIATABQABAAABAAQAAABABAAQAAAAAAAAQABABAAAAIgBAEQgCADAAARIAACHIAAACIgCAAgACFBPQgGgHgGgDQAKgPADgVQADgQAAgXIgBgZIABgCIACAAIAlAAIgIgQIgdAAIgDAAIAAgBIAAgMIABgCIACgBIA7ABIAAgCQABgJgCgHIASABQABAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIgBAEQgBACAAAHIAAACIA9gBIABABIAAACIAAAMIAAABIgBAAIgcAAIgJAQIArAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAABIAAAMQAAAAgBABQAAAAAAAAQAAAAAAABQgBAAAAAAIiAgBIAAAMQAAAPgCARQAMgMAJgSIACgKIAPAEQABAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIgBACIgEAGIgBACIAWAAIAAgBQAAgIgCgHIATABQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABIgBADIgBAJIAAABIAqAAIACAAIAAACIAAAMIAAACIgCAAIgqAAIAAAOIAkgBIACABIAAABIAAAMIAAACIgCAAIgkAAIAAAPIA2AAIACAAIAAACIAAAMIAAACIgCAAIh/AAIgCAAIAAgCIAAgMIAAgCIACAAIA3AAIAAgPIghAAIgBAAIgBgCIAAgMIABgBIABgBIAhABIAAgOIgeAAIgMASQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAgBgBgBQgEgFgFgDIgBALQgEAVgJASQgBABAAABQgBAAAAABQgBAAAAABQAAAAgBAAIgCgDgADDghIAbAAIAHgQIgqAAgAj1A5IhkAOIgFgUIAOAAQATg3ARhDIAUAGQgQA4gVA6QAkgDAdgFQgJgWgMgVIARgHQATAhASAsIgUAJgApSA/QAbgLAJgPQAIgNABgYIg3AAIAAgQIA3AAIAAgcIgnAFIgIgQQA1gEAngNIAKAQQgPAFgUAEIAAAfIAtAAIAAAQIgtAAQAAAggOASQgMAQgZALgAHSBNIhtAAIgBgBIAAgBIAAgOIAAgCIABAAIAvAAIAAgjIghAAIgCAAIAAgCIAAgOIAAgCIACAAIAhAAIAAgeIgVAAQgEALgFAKQgCADgCAAIgDgBQgGgEgHgCQAFgHADgKIgHADIgCABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBQgCgMgEgLIgBgCQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAHgDIACAAIACABIAHAXQAFgQADgOIABgNIASAFQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAAAIAAADIgDAGIgDANIAQAAIAAgNQABgPgCgMIAUABQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAEQgBADgBARIAAANIAmAAIACAAIAAACIAAAOIAAABIgCAAIgmAAIAAAeIAhAAIABAAIABACIAAAOIgBACIgBAAIghAAIAAAjIArAAIACAAIAAACIAAAOIAAACIgCAAgAH/BEQgIgGAAgOQAAgMAJgKQAKgKAYgLQgBgIgCgDQgCgCgEAAQgKAAgKAIQgJAHgMAOIgNgLQAYgYANgZIghAAIAAgQIAoABQAEgKADgOIATADIgHAUQAZgBAVgCIAAAQIg2ADQgHAMgIAIIgDAEIAAABIAEgDQAIgFAIAAQAJAAAGAGQAGAFABAJIAkgQIAHARQgYAHgSAIIAAAjIgRAAIAAgbQgQAJgGAFQgEAFAAAGQgBAIAIACQAGADASAAQAVAAAagCIABARQgYABgaAAQgcAAgKgIgAiNA9QAbgGAMgPQAKgNAAgWQAAgbgMgOQgJgLgOAAQgEA6gOAgQgFANgIAGQgGAEgJAAQgPAAgIgPQgIgNAAgXQABgjAUgWQAJgKAOgFQAMgFANAAQA+AAAABGQAAA3g7ANgAisgdQgOARAAAcQAAAQAFAJQADAGAFAAQAEAAADgDQACgDADgGQAGgRAEgWQAFgWAAgUQgOACgMAPgABlBKIiYAAIgCAAIAAgBIAAgQIABgBIABgBIBDABIAAghIgrAAIgCAAIAAgCIAAgOQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIArAAIAAgdIgkAAQgHANgJALIgDADIgFgDQgEgEgHgDQATgWAKgfIACgLIASAEQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIgCADIgEAHIgEAMIAcAAIAAgKQAAgRgBgKIAUABQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIgBAEQgBADAAARIAAAKIA3gBIADABIAAABIAAAPIAAACIgDAAIg3AAIAAAdIAvAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAOIgBACIgCAAIgvAAIAAAhIBBgBIADABIAAABIAAAQIAAABIgDAAgAnSAKIAAgTIBmAAIAAATgAE5ABIgJgDQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgCQAFgPAAgVQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIADABIAIABQABABAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAAQgCAagFANIgBABIgBAAg");
	this.shape.setTransform(-5.3,7.5,1,1,0,0,0,-0.3,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txtTitle, new cjs.Rectangle(-65.5,-0.5,121,16.5), null);


(lib.txt7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHoA5QgFgFAAgHQAAgJAGgFQAGgFAGAAQAJAAAGAGQAEAFAAAIQAAAIgFAFQgGAFgIAAQgHAAgGgGgAHtAlQgCADAAAFQAAAEADAEQAEACADAAQAGAAACgDQADgDAAgEQAAgFgDgEQgDgCgFAAQgEAAgEADgADJA9QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhGIAAgBIABAAIAsAAIABAAIABABIAAA6QAAAHgDADIgGACIgJABIgDgBIgCgDIgDgIIAIABQAFAAAAgEIAAgKIgWAAIAAAYQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAgADUAZIAWAAIAAgJIgWAAgADUAGIAWAAIAAgHIgWAAgACEA7IgBgDQgBgHgCgDIAPABQAEAAACgCQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAIAAhPIhVAAIgBAAIAAgBIAAgLIAAgBIABAAIBwAAIABAAIABABIAAALIgBABIgBAAIgDAAIgKAAIABBRQAAAJgGAEQgEADgSAAIgFgBgAEFA5QgEgCAAgIIAAggIgBgNIANABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBADIgBAHIAAAGQALgEAKgGQAEgCACgDIAIAIIACADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgFADIgdAMIAAAKQAAADADABQACABAJAAQAKAAACgCQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIABgHIAKADIACABIABACIAAACIgDAJQgBADgDACQgGAEgPAAQgQAAgFgCgAoBAvQAUgHAHgOQADgGACgGIAAgTIgmAAIAAgMIBVAAIAAAMIggAAQAAAQgDAJQgBAIgEAGQgFAIgHAGQgGAFgKAEgAiRAsQAkgIARgZQAOgRADgeIAOAHQgFAjgTAVQgTAVgiAJgAFIANQgBgNADgUIAFgcIANABQgDAPgCATQgCAPAAAMQAAAXAEASIgPABQgCgTAAgYgAlIAqQAhgFASgTQAIgIAGgNQAFgNADgPIAOAHQgEARgHANQgHANgHAIQgVAVgjAIgAgQA2IgDgNIANACQAFAAABgBIADgFQAEgLgBgcQAAgJgCgDQgBgDgDAAIgLABQgKAogPAfIgMgEQAPggAJgjIgXADIgBgMIAagCIAGgaIANACIgFAXIAKAAQAIAAAFAGQAFAGAAANQAAAggEAMQgCAIgFADQgFADgGAAIgOgBgAjgA3IAAgMIAtAAIAAgZIgqAAIAAgMIAqAAIAAgUIgsAAIAAgMIA5AAIAABRgAFpAuQgGgFAAgLQAAgGABgHIANABIgCAKQAAAGAFADQAEACAHAAIAcgCIAAAOIgbABQgQAAgHgGgABbAkIgLAAIgBAAIgBgCIAAg2IABgBIABAAIAyAAIABAAIAAABIAAAzIAAACIgBAAIgLAAIgBAAIAAgCIAAgFIgaAAIAAAIIAAACIgBAAgABcAOIAaAAIAAgXIgaAAgAANghIAMgGQAPAUAKAZIgMAHQgJgbgQgTgAmkAJIAAgOIBJAAIAAAOgAHAgJIgKAPIgJgGIANgNIgSgDIAEgLIAQAHIgCgTIAMAAIgCATIAQgHIAEALIgSADIAMANIgJAGgAlPgIIAHgKQAWAHAKAGIgHALQgLgGgVgIgAEFgEQgEgCAAgGIAAgfIgBgNIAMABQABAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIgBACIgBAHIAAAGIAUgIIAGgFIAIAIIACACQAAABAAAAQAAAAAAAAQgBAAAAAAQAAABgBAAIgGACQgKAGgSAFIAAAIQAAABABAAQAAABAAABQAAAAABAAQAAABABAAIAKABQALAAABgDIACgEIAAgHQAEACAFACIADABIABACIAAABIgCAJIgFAFQgEADgRAAQgQAAgEgCgAiSgfIAIgLQASAJAPAMIgJANQgPgOgRgJgADzgRIgDgFIgmAEIgGABIgCABQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIgCgMIALAAIAIgSIACgJIAMADQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgCACIgDAEIgHAPIAVgBIgGgJIAAgBIABgBIAHgEIAAAAIACABQAGAJAIAOIAAACIgBABIgHAEIgCABIgBgCgAlEgjIAHgLQATAHANAIIgHAMQgMgJgUgHgAFngiQAQgBASAAIARAAIAAANIgSgBIghACgAAXg4IAJgCQAFAJAEAMIgJADQgDgMgGgKgAoAgiIAAgMIBHAAIAAAMgAAng7IAIgDQAFAKAFALIgJADQgFgNgEgIg");
	this.shape.setTransform(-1.8,0.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt7, new cjs.Rectangle(-53.8,-6,104.1,12.6), null);


(lib.txt6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhuAiIALgJQARAMAKARIgMAJQgKgQgQgNgAjRA9IgBAAIgBgBIABg4QgKAKgIAHIgDACIgDgDIgGgHQAYgPAMgZIghABIgBgBIAAgBIAAgKIAAgBIABAAIAmAAIACgFIADgNIAMACQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIgCACIgCAGIgCAGIA8AAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAKQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIhBgBIgFALIA1AAIABAAIABACIAAA8QAAAHgFAEQgCACgFAAIgMABIgDAAIgBgEIgFgJIANAAQABAAABAAQAAAAABAAQAAAAABAAQAAgBAAAAIABgDIAAgJIgqAAIAAAaIAAABIgCAAgAjFAYIAqAAIAAgJIgqAAgAjFAEIAqAAIAAgIIgqAAgAkKA7QgWgLgNgQIAAgCIAJgFIABgBIABABQAPAQAUAIIgGAIIgDADgAlqA5QgDgFgEgDQATgHALgLIAFgHIALAFIACACIgCADIgEADQgKAMgTAKIgDABIgDgDgABWAzIAAhiIAOAAIAABXQAQgGAOgOQALgMAHgQIALAJQgLAXgRAOQgOAMgWAIgAgSAuQAdgKANgTQAMgRAAgeIg6AAIAAgMIA/AAIAAgFQAAgHAEgEQAFgEAFAAQAHAAAEAFQAEAEAAAGQAAAGgFAFQgEAEgGAAIgEgBQgBApgRAVQgOARgdALgAAxg1QgCACAAAEQAAAEADACQACACADAAQAEAAACgDQACgCAAgDQAAgEgCgDQgDgCgDAAQgDAAgDADgAEeAsQAkgIARgZQAOgRADgeIAOAHQgFAjgTAVQgTAVgiAJgADKAwQgGgEAAgMIAAgqIgVAFIgEgLIAZgGIAAgdIAPAAIAAAaIAqgKQgDgKgFgKIAIgCQAFAJAFANIgFABIAHAHQgGARgHALQgGAKgJAKIgMgHQASgTAFgRIglAJIAAAsIABAGQABACAEABIANABQASAAANgCIAAAOIghABQgVAAgFgGgAj/AUIhxAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgKQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAdAAIAAgYIgWAAIgCAAIAAgBIAAgKQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAWAAIAAgGIgBgTIAOABQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIgBADIgBANIAAAGIAcAAIAAgGIgBgTIAOABQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIgBADIAAANIAAAGIAXAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAKIAAABIgBAAIgXAAIAAAYIAdAAIACAAIAAABIAAAKIAAACIgCAAgAlGAHIAcAAIAAgYIgcAAgAEdgfIAJgLQARAJAPAMIgJANQgPgOgRgJgAEEg7IAIgCQAFAKAEALIgIADQgEgNgFgJg");
	this.shape.setTransform(-0.1,0.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt6, new cjs.Rectangle(-37.1,-6,74,12.6), null);


(lib.txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AI7AhQgEgDAAgEQAAgFAFgDQADgEAEAAQAFAAADAEQAEADAAAFQgBAFgDAEQgEADgEAAQgFAAgDgFgAI+AVQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAABQAAADABACQABAAABABQAAAAABAAQAAAAABAAQAAAAABAAQADAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgDgCgCQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgCACgABzAhQgCgDAAgEQAAgFADgDQADgEAFAAQAGAAADAEQACADAAAFQABAFgEAEQgDADgFAAQgFAAgEgFgAB3AVQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABQAAADACACQABAAABABQAAAAABAAQAAAAABAAQAAAAABAAQADAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAgDgDgCQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgCACgAimAkIgDgHIAJgBIADAAIAAgGQgIAEgJACIgBAAIgDgCQgBgDgCgCQAQgCALgGIgZAAIAAgBIAAgFIAAgBIABAAIAhAAIAAgEIgDAAIgBAAIgCgEIAEAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAIAAgCIgHAAIAAAIIgBABIgGAAIgBgBIAAgIIgHAAIAAADIABAEIgBAAIAAAAIgFAAIgBAAIAAAAIAAgIIAAgFIABgBIAMABIAAgEIgRAAIAAAAIgBAAIAAgFIABgBIAGAAIgCgBIgEgBQAEgEACgFIABgDIAGABIABABIAAABIgCACIAAAAIAFAAIAAgGIAHABIABAAIAAACIAAADIANAAIABAAIAAABIAAAFIAAAAIgOAAIAAADIAQAAIABABIAAAFIgBAAIgQAAIAAAEIANgBIABABIAAAJIgBADIACAAIACABIgBABIAAADIAdAAIAAAAIABABIAAAFIgBABIgLAAIAEAEIABABIgBABIgDACIgEACQAHAEAJACIgDAEIgCADIgBAAQgWgHgJgQIgBAAIgGAFIAAAJIAPgDIgBAFIAAABIgCABIgXAFIgDABIgBAAIgBgBgAiAAUIAFgEIADgDIgPAAQADAEAEADgAECAlIgBgBIABghIgIABIgCAAIgBABIgCgBIgBgGIAGAAIAFgGIgLgMIAAAAIAAgBIAEgEIAAgBIABABIACACIAFgJIABgEIAHADIABAAIAAACIgCABIgHAMIADADIAGgIIACgGIAHAEIABABIgBABIgDADIgMASIAJgBIgCgEIAAgBIAEgCIABgBIAAACQAEAFACAIIAAgiIABAAIAkAAIAAA/IAAABIgHAAIgBgBIAAgEIgVAAIAAAEIAAABIgBABIgGAAIgBgBIAAgeIgBABIgEACIgBAAIAAgBIgBgEIgFABIAAAhIgBABgAErAWIAHAAIAAgTIgHAAgAEdAWIAHAAIAAgTIgHAAgAErgEIAHAAIAAgTIgHAAgAEdgEIAHAAIAAgTIgHAAgADUAlIgBgBIAAgSIgPAAIgBAAIAAgHIABAAIAPAAIAAgJIgNAAIAAgBIAAgFIAAgBIANAAIAAgIIgOAAIgBgBIAAgGIABgBIATAAIAGgLIABgEIAHADIABAAIgBACIgBACIgFAIIAMAAIAAABIAAAGIAAABIgRAAIAAAIIANAAIABAAIAAABIAAAFIAAABIgBAAIgNAAIAAAJIARAAIACAAIAAAAIAAAHIgCAAIgRAAIAAASIgBABgACpAlIgBgBIAAgZIABgBIAXAAIABABIAAAXIgBABIgHAAIAAgBIAAgCIgJAAIAAAEIAAABgACwAaIAJAAIAAgJIgJAAgAk/AlIAAgBIAAgvIABgBIAbAAIAAABIAAAnQAAAEgBACQgDACgGAAIgDAAIgBgDIgCgFIAGABIACgBIABgBIAAgHIgOAAIABAQIgBABgAk4ANIAOAAIAAgGIgOAAgAk4ABIAOAAIAAgGIgOAAgAglAkIAAAAIAAgFIgPAAIAAAEIAAABIgHAAIgBgBIAAghIAAAAIAeAAIABAAIAAAAIAAAiIgBAAgAg0AYIAPAAIAAgPIgPAAgAhgAkIgBAAIAAgBIAAghIAAAAIABAAIAdAAIAAAAIAAAhIAAABIgHAAIgBgBIAAgEIgOAAIAAAEIAAABgAhZAYIAOAAIAAgPIgOAAgAkUAjIgBgCIgCgFIAIAAIACgBIABgDIAAgaIAAgLIAIABQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgBACIAAAHIAAAdQAAAFgCACIgFABIgHABIgCgBgAA2AbQAOgCAGgFQAFgEAAgEQgEAEgFAAQgHAAgDgEQgEgDAAgGQAAgGAFgDQAEgDAFAAQAEAAADABIAAgIIgfABIAAgIIAfAAIAAgKIAJAAIgBAKIATAAIAAAHIgTAAIAAAQQACADAAAGQAAALgIAHQgGAEgOAEgABBgCQgCACAAACQAAAEACACQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQADAAADgCQABgDAAgDQAAgGgHAAQgBAAAAABQgBAAgBAAQAAAAgBABQAAAAgBAAgAIHAaIABAAQAPAAAIgEQAHgEAAgHQAAgFgDgDQgDgCgFAAQgJAAgHAIQgDADgBADIgIgBIADgjIAIACIgCAVIgCAEIADgEQAHgHALAAQAKAAAFAFQAFAEgBAIQAAAGgCAEQgDAFgFACQgJAFgSAAgAnnAbQAJgCAGgDQAFgDACgGQADgGAAgJIAAgdIAJAAIAAAfQAAAQgIAIQgHAHgPADgAogAbQAKgCAEgDQAGgDACgGQADgGAAgJIAAgdIAJAAIAAAfQAAAQgJAIQgGAHgPADgAHMAbQAUgBAFgDQAGgDAAgHQAAgKgKAAQgGABgFACQgFADgFAGIgIgEQAGgLAEgPIgNAAIAAgHIAPgBIACgLIAIABIgCAKIAYgBIAAAHIgaACQgDAMgFAIQAIgIAMAAQAJAAAFAFQAEAFAAAGQAAAMgKAEQgHAEgVAAgAgDAHQAAgIADgHQAFgHAHgEIAEgCIAAgBIgFACIgdADIgBgHIA0gEIABAHQgJABgFADQgQAIAAAPQAAARAYACIgDAIQgcgCAAgYgAljAKQgKAOgTAJIgFgGQARgJAKgOQAHgKAEgPIghAAIAAgHIApAAIACADQgDAQgHALQAKAKAJAQIgJAFQgGgNgIgKgAFYAVQAAgFAFgDQAEgDAFAAIAIABIAAgWIgWAAIAAgHIAVAAIAAgOIAJAAIAAAOIAMgCIAAAIIgMAAIAAAYQAIAEAGAHIgFAHQgEgHgFgCIAAAAQAAAGgEADQgEADgHAAQgPAAAAgMgAFhASQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQAAAFAIAAQAHAAAAgGIAAgCQgDgBgFAAQgDAAgCABgAFIAIQAAgQAFgYIAIABQgFAXAAAQQAAAKACAOIgIABQgCgOAAgLgAjZAbQAMgDAFgHQAEgFAAgKQAAgMgFgGQgEgEgGgBQgBAagHAOQgCAFgEADQgDABgEABQgGAAgEgHQgDgFAAgLQAAgPAJgJQAEgFAGgCQAGgCAFAAQAcgBAAAfQAAAYgaAGgAjogNQgFAIAAALQAAAIACAEQAAAAABABQAAAAABABQAAAAABAAQAAABAAAAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAIACgEIAEgRQADgKAAgJQgHABgGAHgAGLASQABgHADgHIAIADQgDAFgBAFQAAAEAEABQAEACAIAAIAVgBIAAAJIgVAAQgYAAAAgOgAD5AeIgFgCQADgIABgIIAAgEIAFACQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIgBAAIAAADIgDAPIgBABgAEOAaIgBgBIgCgOIAAgBIAEgCIABAAIAAABQADAHABAGIAAABIgBABIgEACgAkaAUIgBgBIAAgSIgBgKIAIAAIABABIAAACIgBAHIAAASIgBABgAnsAIIAAgnIAJAAIAAAngAolAIIAAgnIAJAAIAAAngACxAFIgHABIgBgBIAAAAIAAgFIAAAAIAWAAIAAAAIAAAFIAAAAIgBABgAm4AEIAAgIIAtAAIAAAIgAAUgJIAFgCIAGAMIgGACQgCgHgDgFgAh+ADIgBgCIgBgFIAGABIADgBIABgBIAAgUIgBgKIAIAAIABABIAAABIgBAIIAAAWQAAADgDACQgBABgJAAIgCAAgAo/gHIgGAJIgFgCIAHgJIgKgCIACgGIAKADIgBgLIAHAAIgCALIALgDIACAGIgLACIAHAJIgFACgAAdgMIAGgCQAEAHACAGIgGABIgGgMgACpgEIAAgBIAAgFIAAgBIABAAIAHAAIANAAIABAAIAAABIAAAFIAAABgAhUgFIgBAAIAAgBIAAgaIAAgBIABAAIAsAAIAAABIAAAaIAAABgAhNgNIAdAAIAAgMIgdAAgAiFgHIgBAAIAAgBIAAgPIAAgJIAHABIACAAIgBACIAAAGIAAAQIgBAAgAGcgNIAMgIIgKABIgOAAIAAgHIAPAAIAWgCIABAIIgIAFIgNAJgAClgPIAAAAIAAgGIABgBIAcAAIAAABIAAAGIAAAAgAlEgRIgBAAIAAgBIAAgGIABgBIATABIgEgJIAAAAIABgBIAFgCIABAAIABABIAEAHIAAABIgBABIgFACIASAAIAFgJIABgDIAIACIACABIgBABIgCACIgEAGIAWgBIAAABIAAAGIAAABgAIWgYIgNgDIADgHIAOADIAMAFIgEAGIgMgEgADNgWIgGgKIAAgBIABAAIAFgCIABAAIAAAAIAHAKIAAABIgBABIgGABIgBABIAAgBgAC/gaIgWAAIAAAAIAAgBIAAgFIAAgBIAAAAIAWAAIACAAIAAABIAAAFIAAABIgCAAg");
	this.shape.setTransform(-154.65,236.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt5, new cjs.Rectangle(-213.7,232.7,118.1,7.5), null);


(lib.txt4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFoAiIAMgJQAQAMALARIgNAJQgKgQgQgNgAhhAzIAAhiIAOAAIAABXQARgGANgOQALgMAHgQIAMAJQgMAXgRAOQgOAMgWAIgAkrAvQAcgHAMgOQAKgNACgVIg+AAIAAgMIBNAAQgBAmgRATQgOAOgcAHgAEHAsQAkgIASgZQANgRAEgeIANAHQgFAjgTAVQgTAVgiAJgAixA5IAAhMIgoAAIAAgMIAoAAIAAgVIAPAAIAAAVIAoAAIAAAMIgoAAIAABMgABQAqQAhgFASgTQAIgIAGgNQAGgNADgPIANAHQgEARgHANQgGANgIAIQgVAVgjAIgAC4A3IAAgMIAtAAIAAgZIgqAAIAAgMIAqAAIAAgUIgsAAIAAgMIA6AAIAABRgAmOAyIAAgMIA2AAIAAhDIg2AAIAAgMIBEAAIAABbgAjcAqQAOgWAEgbIAOAFQgEAQgFAMQgEALgGALgAiYgBIANgFQAJAdAKASIgNAHQgKgUgJgdgAgLAJIAAgOIBIAAIAAAOgABJgIIAHgKQAWAHAKAGIgHALQgLgGgVgIgAEGgfIAJgLQASAJAOAMIgJANQgPgOgRgJgABVgjIAGgLQAUAHAMAIIgHAMQgMgJgTgHgAiUg5IAJgCQAFAIAEANIgIADQgEgMgGgKgAktgjIAAgMIA+AAIAAAMgAiDg7IAIgDQAGAKADALIgIADQgEgNgFgIg");
	this.shape.setTransform(-171.925,181.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt4, new cjs.Rectangle(-211.8,175.6,79.80000000000001,12.700000000000017), null);


(lib.txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjjAxQAVgDAJgMQAFgGABgJQACgJAAgNIgBgsIAOgBIABAtQAAASgDAKQgCAIgFAHQgFAIgIAEQgIAFgNADgAESA2QgFgFAAgIQAAgKAJgGQAHgEAKAAIAKABIgBgfIANAAQAAAVABAMQAOAGALAKIgHAMQgKgKgIgEIAAADQAAAJgHAFQgGAFgMAAQgMAAgHgGgAEZApQAAAIANAAQAMAAAAgLIAAgEQgEgCgGAAQgPAAAAAJgAAUAtIhHAKIgDgOIAJgBQAOgoAMgvIAPAEQgMAogPAqIAugFQgGgQgJgQIAMgEQAPAXAMAgIgOAGgAC7AUQgQAXgeAPIgIgLQAagMAQgXQAOgSAFgXIg1AAIAAgNIA8AAIAGAOIADgBQgGAWgJAOQAPARAPAaIgOAJQgKgVgOgSgAhlAUQgRAXgeAPIgIgLQAagMARgXQANgSAFgXIg1AAIAAgNIBDAAIAEAFQgGAagLASQAQASAOAZIgNAJQgLgWgNgRgAlRA0QgGgFAAgJQAAgKAJgGQAHgEAKAAIAMAAQgDgTgBgyIAOAAIABAbQATgBAOgCIAAAMQgQACgRAAIACAhQAUAGARAQIgJAMQgOgRgNgEIAAAEQAAAVgcAAQgMAAgGgGgAlIAgQgDACAAAEQAAAJANAAQAOAAAAgLIAAgGIgNgBQgHAAgEADgADzAjQAPgbAHgaIgUAAIAAgLIAXAAIAEgWIAOACIgFATIARgCIABAMIgVABQgIAegPAdgAjqAYQgDgNAAgNQAAgPAEgfIANACQgEAbAAATIAAAIQADgIAFgKIAIAGQgGAKgDAJIgDAJgAAxALIAAgOIBKAAIAAAOgAEygYIAGgKQATAGANAJIgHALQgNgJgSgHgADKg3IAIgCQAFAJAFANIgJADQgEgNgFgKgADZg5IAIgCQAGAJAEALIgJADQgEgMgFgJg");
	this.shape.setTransform(-174.825,176.225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-209.2,170.2,68.79999999999998,12.100000000000023), null);


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE7AiIALgJQAQAMALARIgMAJQgKgQgQgNgACMA0QgFgFAAgIQAAgKAJgGQAGgEALAAIAKABIgBgfIAMAAQABAVABAMQANAGALAKIgHAMQgJgKgIgEIAAADQAAAJgIAFQgFAFgMAAQgNAAgGgGgACSAnQABAIANAAQALAAABgLIAAgEQgEgCgGAAQgQAAAAAJgADtAtIABAAQAZAAANgHQAMgFAAgNQAAgIgGgEQgEgEgIAAQgPAAgLAMQgGAHgBAFIgNgDIAEg4IAOACIgFAiIgBAIIAEgGQANgNASAAQAPAAAJAHQAGAIAAANQAAALgEAGQgFAGgIAFQgOAHgcAAgAj3AvQAfgLAPgVQgKgJgPgGIAIgKQAOAHAKAGQAGgMADgTIgiAAQgKAWgPAOIgMgIQALgJAJgPQAHgOAEgQIAOAEIgDAKIAjAAIgIgRIAIgCQAFAHAFANIgGACIAGAGQgJAngQAUQgOARgdAMgAiRAsQAkgIASgZQANgRADgeIAOAHQgGAjgSAVQgTAVgiAJgAk+A0QgGgEAAgMIAAghIgcAAIAAgLIAcAAIAAgZIgYAAIAAgMIBNAAIAAAMIgnAAIAAAZIAqAAIAAALIgqAAIAAAgQAAAEADABQACACAKAAQANAAAMgBIAAANIgZABQgRAAgGgDgAAmAoQgMgMAAgVQAAgUANgOQAOgNAUAAQANAAAJADIAAAPQgJgFgLAAQgPAAgJAJQgJAKAAAPQAAAPAIAJQAJAJAOAAQANAAAJgHIAAAOQgKAGgPAAQgUAAgMgNgAgrAzIAAhaIAcAAQAPAAAIAIQAJAHAAANQAAAMgJAJQgIAIgQAAIgLAAIAAAhgAgbAGIAJAAQAKAAAFgFQAEgDAAgIQAAgQgRAAIgLAAgABtAhQAOgbAIgaIgVAAIAAgLIAYAAIADgWIAPACIgFATIARgCIAAAMIgUABQgIAegPAdgAiSgfIAIgLQASAJAPAMIgJANQgPgOgRgJgACsgaIAGgKQATAGAMAJIgGALQgNgJgSgHgAEGgmIgVgFIAEgKIAYAFIAUAGIgIAMQgHgEgMgEgAirg7IAIgDQAGAKAEALIgJADQgEgNgFgIg");
	this.shape.setTransform(-170.25,171.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-205.6,164.9,70.69999999999999,12.599999999999994), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJQA3QgEgGAAgHQAAgIAGgGQAFgFAHAAQAJAAAFAGQAFAGAAAHQAAAIgGAGQgFAFgIAAQgIAAgGgGgAJWAjQgCADAAAEQAAAFADADQADADAEAAQAFAAADgEQADgDAAgEQAAgFgDgDQgDgDgFAAQgEAAgEAEgAlgA7IgCgDQgCgFgEgDQARgCAMgGQAEgCADgCIgWAAIgBAAIAAgBIAAg2IAAgBIABAAIBXAAIABAAIAAABIAAA2IAAABIgBAAIgXAAIABAAQAPAJAVADQgDADgDAFQgBABAAAAQgBABAAAAQgBABAAAAQAAAAgBAAIgCAAQgUgFgPgKIAAgBIABgBIAJgGIgqAAIAKAGIACACQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgFACQgMAHgRAEIgDABIgBgBgAlNAaIA+AAIAAgHIg+AAgAlNAKIA+AAIAAgGIg+AAgAlNgEIA+AAIAAgGIg+AAgAF9A7IgLAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAhAIgIAJIgCACIgCgCQgBgHgDgDQAPgRAIgZIACgKIAMAEQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIgBACIgDAGIgGAQIAABXIAAACIgBAAgAEiA7IgJAAIgBAAIgBgCIABg1IgFAGIgCABIgBgCQgBgEgDgEIAAAqIAAABIgBABIgJAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgFIgKAAIAAALIAAABIgCAAIgIAAIgCAAIAAgBIAAgpIgFAHIgCACQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgIgDgEQAPgPAEgbIgNAAIgCAAIAAgBIAAgKIAAgBIACAAIAoAAIACAAIAAABIAAAFIAYAAIADgOIAMACQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIgBADIgDAHIAAABIAiAAIABAAIAAACIAAATIAAABIgBAAIgJAAIgBAAIgBgBIAAgKIgbAAQgEAKgFAIIANAAIABgDIACgDIACgIIAKACIACACIgBADIgCAEIgCADIATAAIABAAIAAABIAAAIIAAABIgBABIgVgBIAAAJIASAAIACAAIAAABIAAAHIAAACIgCAAIgSAAIAAAJIASAAIACAAIAAABIAAAIIAAABIgCAAIgSAAIAAAKIAYAAIACAAIAAABIAAAIIAAACIgCAAIgzgBIAAAFIAAACIgBAAgAEjAqIAQAAIAAgKIgQAAgAD3AbIAKAAIAAgcIgKAAgAEjAWIAQAAIAAgJIgQAAgAEjADIAQAAIAAgJIgQAAgAEMgMIAAABIAAALQAPgOAIgUIgKAAIAAALIgBABIgBAAIgJAAIgBAAIAAgBIAAgQIgOAAQgDAOgFANIAUAAIABAAgAmsA7IgLAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgEIAAgVQgPAPgaAJIgDAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgFgIQAagHAPgLIglAAIgCAAIAAgBIAAgIIAAgBIACAAIAwAAIAAgHIgkAAIgBAAIAAgBIAAgIIAAgBIABAAIAkAAIAAgGIgqAAIgBAAIAAgBIAAgIIAAgBIABAAIAaAAIgEgIIgBgBIABgBIAJgDIglABIgCgBIAAgBIAAgIIAAgBIACAAIARAAQgCgFgFgGIgBgBIACgBIAHgEIABAAIACABQAFAGADAGIABABIgCABIgDACIAMAAIAAgJIAAgLIAMABIACABIgBACIgBAHIAAAJIALAAIAAgIIgBgMIANABIABABIAAACIgBAHIAAAJIAIAAIAGgLIACgHIANAEQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIgCADIgHAKIASAAIABAAIAAABIAAAIIAAACIgBAAIgngBIAKADIACABQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgBADIgDAEIAaAAIABAAIAAABIAAAIIgBABIgsAAIAAAGIAnAAIABAAIAAABIAAAIIAAABIgBAAIgnAAIAAAHIAzAAIABAAIAAABIAAAIIAAABIgBAAIgoAAQAQALAcAGIgFAIQgBABAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgDgBQgbgIgRgPIABAZIgBACIgBAAgAnBgcIAGAMIAVAAIAEgHIABgGIghAAIABABgApfA7QAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgxIgHAGIgDACIgCgDQgBgGgDgDQAPgKAKgRIADgHIAKAGIACADQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgDAEIgGAJIAAA/IgBABgAGYA6IgKAAIgBAAIgBgBIAAgmQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIBBAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIAAAmQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgLAAIgBgBIAAgEIgpAAIAAAEIAAABIgCAAgAGaAqIApAAIAAgNIgpAAgAgaA6QgUgNgQgHQgSAOgjAFIgCABIgCgBIgCgDQgCgFgDgEQAhgDARgKIgTgGIgDAEIgCABIgCAAIgIgEIgBgBIAAgBIAHgIIAJgQIgdAAIgCAAIAAgBIAAgJIAAgBIACAAIAjAAIADgHIAFgNIAOAEQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACIgEAFIgDAHIA+AAIABAAIABABIAAAJIgBABIgBAAIgZAAQgFARgKALQAQAGATAKIABABIgBACIgGAJIgCABgAhZAQIAYAHQAJgJAFgNIgdAAgApKA4QgEgFgEgCQAIgKAEgNQADgKABgOIABgFIgBgDIAMABQABAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIgBACIgDAVQAFAKAKAGIAAg2IgeAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgKQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAnABQAFgJAEgKIACgJIANAEQAAAAABABQAAAAAAAAQAAAAABAAQAAAAAAABIgCACIgCAEIgIAQIAWgBIABABIAAABIAAAKQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAAAAAIggAAIAAAUIAZgBIACABIAAABIAAAKIAAABIgCAAIgZAAIAAAbQAJACAOAAIAOAAQgCAEgBAFIgBAEIgGABIgHgBQgpgBgLgWQgEANgGAKIgDACIgCgCgAAqA1QgGgEAAgJIAAgxIAAgPIANABQABAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIgBADQgBABAAAIIAAAsQAAAEADACIALABQAKAAADgDQACgCABgEIAAgPIALAEIADABIAAACIAAACQAAALgCAFQgBAFgEACQgEAEgGABIgOABQgRAAgEgDgAH6AwQgGgEAAgKQAAgJAHgHQAHgHARgJQAAgFgCgCQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQgGAAgIAHQgGAEgJALIgJgJQARgQAJgTIgXAAIAAgLIAcAAIAGgRIANACIgFAPIAhgDIABAMIgoACQgFAJgFAGIgDADIAAAAIAEgCQAFgEAGAAQAGAAAFAEQAEAEABAHIAagMIAFANQgSAEgNAGIAAAZIgMAAIAAgTQgLAGgFAEQgDAEAAAEQAAAGAFACQAFACANAAQAPAAATgCIAAAMQgRABgSAAQgVAAgHgGgAjiALQAAgNADgUIAFgdIANABQgDAQgCASQgCAQAAALQAAAYADARIgOACQgDgUAAgXgACRAuQgJgHAAgOQAAgTAYgOQgFgSgFgcIAOgBQADAXAEARIAegQIAHAMQgcALgQAKQgHAGgEAGQgDAGAAAFQAAAIAGAEQAGAEANAAQARAAAQgCIAAANIgfABQgWAAgKgHgAjAArQgHgFAAgKQAAgHACgHIANABIgCAKQAAAHAEACQAEACAIAAIAcgBIAAANIgbABQgQAAgHgGgAANAlIgKgEIgBgCIAAgBQAJgSADgWIABgCIABABIAKACIABACIAAAAQgDAWgJAVIgBABgABqAgQgFgWgLgSIgBgBIACgCIAJgEIACAAIABABQALASAGAVIAAABIgBABIgKAFIgCABIgBgBgAHMALIg7AAIgCAAIAAgBIAAgIIABgCIABAAIA7AAIABAAIAAACIAAAIIAAABIgBAAgAGRgFQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgIIABgCIABAAIA7AAIABAAIAAACIAAAIQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAgAgbgQIgBgBIgBgBIAAgPIhQAAIAAAPIAAABIgBABIgLAAIgBgBIAAgBIAAgaQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAtAAIAAgBIgBgNIAOABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIgBADIgBAIIAAABIAvAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAHIAAATIAAABIgBABgAppgYIgGgIQANgIAKgNIAEgGIAKAGIACADIgBABIgEAEQgLAMgMAKIgDACIgCgDgAGGgXIgBgBIAAgBIAAgJIAAgBIABAAIBTAAIABAAIAAABIAAAJIAAABIgBABgAjCgkQAQgCASAAIARABIAAANIgSgBIghABgAlSgaIgCgBIAAgBIAAgaIABgBIABAAIBIAAIABAAIAAABIAAAaIAAABIgBABgAlGgkIAvAAIAAgJIgvAAgABLgbQgSgMgSgHIgBgBIABgBIAFgIIACgCIABABQATAGAQALIABABIgBABIgFAJIgBACIgBAAgAo0giQgEgJgGgHIAAgCIABgBIAKgEIABABQAGAHAEAJIABACIgCABIgIAEIgCAAgAHNgqIg9AAIgBAAIAAgCIAAgIIAAgCIABAAIA9AAIABABIAAABIAAAIIAAACIgBAAg");
	this.shape.setTransform(-142.825,165.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-205.3,159.7,125.00000000000001,12.100000000000023), null);


(lib.title2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnXBSIgQAAIgBAAIAAgCIAAhKIAAgCIACAAICNAAIACABIAAABIAAA6QAAAJgEAEQgDACgEABIgNABIgGgBIgBgFQgBgHgDgEIAMAAQAEAAAAgFIAAgnIhrAAIAAA8IAAACIgCAAgAiSA0QAAgKAJgHQAHgGAMAAQAOAAAJAIQAJAIAEANQAPgFAAgXQAAgOgJgIQgIgHgNAAQgWAAgUARQgIAIgIAJIgOgMQAxgxAcgbQgeADgcABIAAgRQAgAAAtgCIAJANIg7A0IABABIAIgFQAKgEAJAAQAXAAANAMQALALAAASQAAAZgRANQgQALgcAAQglAAAAgbgAiAAtQgDADAAAEQAAANAVAAIALgCQgCgLgGgFQgFgFgGAAQgGAAgEADgAEGA/QAlgKARgUQAPgSACgcIhVAAIAAgRIBqAAQgCA1gYAZQgSAUgnAKgAj9A9QAwgGAAgpQAAgSgHgMQgHgKgKgCQgKAwgQAZQgOAWgUAAQgMAAgHgJQgHgLAAgTQAAgeAVgVQgEgQgDgYIARgCIAFAfQAQgJATgBIADgbIATACIgEAaQAUAEALAQQAJAPAAAWQAAAfgSAPQgOANgbAFgAkrAaQAAAYAKAAQAKAAAJgMQgMgVgHgWQgKAOAAARgAkUgTQAFAVAKASQAIgTAGgeQgQAAgNAKgAgQA/QAZgLAKgPQAIgNABgYIg2AAIAAgQIA2AAIAAgcIgnAFIgIgQQA1gEAngNIAKAQQgPAFgUAEIAAAfIAtAAIAAAQIgtAAQgBAggNASQgMAQgZALgAF8AQQAAgSAEgcIAGgoIATACQgEAVgDAaQgDAWAAAQQAAAgAEAZIgSABQgFgaAAghgABrA+QAZgRAJgXQAIgTACgeIgnAAIAAgRIAnAAIAAgeIAUAAIAAAeIA1AAQAAA+gEAeQgCAQgHAFQgFADgHABIgYABIgGgUIANABIAMgBQADAAACgDQABgCABgHQADgXAAguIgiAAQgCAogNAYQgLAVgXARgAm0BGIgNAAIgCAAIAAgCIAAgmIAAgCIACAAIBCAAIACAAIAAACIAAAlIAAACIgBAAIgOAAIgCAAIAAgCIAAgDIgkAAIAAAEIgBACIgBAAgAmyA0IAkAAIAAgMIgkAAgAGrA9QgJgHAAgPQAAgJACgJIASACQgCAHAAAGQAAAJAFAEQAGADALAAQASAAATgCIABASIglABQgXAAgJgIgAlzgEIhZAAIgCAAIAAgBIAAgjIAAgBIACgBIBZAAIACABIAAABIAAAjIAAABIgCAAgAm9gQIA6AAIAAgMIg6AAgAGogyQAXgBAYAAIAYABIAAARIgZgBQgXAAgXACgAlSgyIibAAIgBAAIgBgCIAAgMIABgCIABAAIBDAAIAAAAIgBgPIATABQAAAAABAAQABAAAAAAQAAAAABABQAAAAAAAAIgCAEIAAAJIAAAAIBFAAIABAAIABACIAAAMIgBACIgBAAgAEDgzIAAgQIBWAAIAAAQg");
	this.shape.setTransform(9.2,6,1,1,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title2, new cjs.Rectangle(-40.2,-2.1,99.1,16.5), null);


(lib.logomc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmyPUQjHhPiWiRQiYiRhSi/QhVjGAAjeQAAjbBWjFQBTi/CXiSQCYiRDIhQQDOhSDkAAQDkAADMBRQDGBPCWCRQCYCRBSC/QBVDGAADdQAADbhVDGQhUC/iXCSQiYCRjIBQQjNBSjkAAQjkAAjMhRgAmJmfQiZCiAAD9QAADzCgCoQCgCnDmAAQDrAACbikQCZikAAj6QAAjyifioQiginjmAAQjtAAiaCig");
	this.shape.setTransform(-4.9768,429.3894,0.0598,0.0597,-90);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmzPUQjGhPiXiRQiXiRhSi/QhVjGAAjeQAAjbBVjFQBTi/CZiSQCYiRDHhQQDOhSDkAAQDjAADNBRQDGBPCXCRQCXCRBSC/QBVDGAADdQAADbhVDGQhTC/iZCSQiYCRjHBQQjOBSjkAAQjjAAjNhRgAmJmfQiZCiAAD9QAADzCfCoQCgCnDnAAQDsAACaikQCZikAAj6QAAjyifioQiginjnAAQjtAAiZCig");
	this.shape_1.setTransform(-4.9768,403.4314,0.0598,0.0597,-90);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AudU1MAAAgppII7AAMAAAAhkIUAAAIAAIFg");
	this.shape_2.setTransform(-6.8093,469.5787,0.0598,0.0597,-90);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AmFPXQjQhNiaiPQiaiPhSjBQhUjFAAjmQAAjeBSjFQBRjACUiRQCUiRDFhOQDLhRDjAAQD/AADPBWQDPBVCOClQBhByA/CSQA+CSAYCnI2gJVQCpCnEdAAQCmAAB5grQCAguCtiBIFlESQiOCkkFBvQkRB1kWAAQj6AAjYhOgAjgouQhvA1hJBiQhFBegeB1QgiCDATCUIPYmXQg9iFhvhLQh1hQiUAAQiIAAhxA2g");
	this.shape_3.setTransform(-4.9753,457.3048,0.0598,0.0597,-90);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ak0QCMgNNggDIKEAAIH9V1IH911IKFAAMgNNAgDg");
	this.shape_4.setTransform(-4.9768,416.4067,0.0598,0.0597,-90);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AHWQTIAAyPQAAjCiWh8QiLh0i5AAQjWAAiECKQh3B+AACqIAASPIozAAMAAAggEIIzAAIAAEnQB3ieC9hZQCvhSC6AAQFxAADpDnQDnDkAAFkIAAT3g");
	this.shape_5.setTransform(-5.0784,443.5011,0.0598,0.0597,-90);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E1140A").s().p("AifHgIAAu/IE/AAIAAO/g");
	this.shape_6.setTransform(-6.075,436);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgRAMgXALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_7.setTransform(-24.3476,513.5387,0.2765,0.2755);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgQAMgYALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_8.setTransform(-30.3616,513.5387,0.2765,0.2755);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag/CeQgXgFgQgHIAAhIQAUAOAXAIQAWAIATAAQAZAAALgHQALgHAAgQQAAgPgMgKQgNgLgggNQgogRgRgUQgRgVAAghQAAgqAhgbQAhgbA0AAQAPAAAWAEQAQADASAGIAABGQgQgKgSgHQgUgHgSAAQgVAAgLAIQgLAIAAAPQAAAPAJAJQALAJAgAOQAtARARAVQARAWAAAfQAAArghAbQgiAbg4AAQgRAAgagFg");
	this.shape_9.setTransform(-38.7742,515.3573,0.2765,0.2755);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA/CbIg+jfIAAAAIhADfIhNAAIhak1IBMAAIA6DtIABAAIBFjtIBEAAIA9DuIACAAIA4juIBGAAIhbE1g");
	this.shape_10.setTransform(-48.5141,515.3573,0.2765,0.2755);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhzB4QgrgrAAhJQAAhMAsgtQArgsBMAAQBJAAApArQAoArAABKQAABLgrArQgrAthLAAQhHAAgqgqgAg8hJQgWAaAAAxQAAAwAWAaQAWAZAoAAQAnAAAWgZQAUgaABgyQAAgxgWgaQgWgZgmAAQgoAAgWAbg");
	this.shape_11.setTransform(-59.6711,515.371,0.2765,0.2755);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhzC+QgjgoAAhHQAAhMAmguQAnguBAAAQAcAAAXAKQAXAKAMASIACAAIAAizIBIAAIAAHIIhIAAIAAgpIgCAAQgQAXgZALQgaAMggAAQg7AAgigpgAg1gCQgVAcAAAzQAAAvAUAZQAVAZAiAAQAiAAAWgaQAWgaAAgqIAAghQAAghgVgVQgVgXggAAQgmAAgUAcg");
	this.shape_12.setTransform(-69.646,513.4009,0.2765,0.2755);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("ABCCeIAAisQAAgqgPgVQgOgVggABQgeAAgTAXQgVAXAAAjIAACuIhIAAIAAk1IBIAAIAAAqIACAAQARgZAZgLQAYgMAhAAQAxAAAbAgQAaAfAAA/IAAC9g");
	this.shape_13.setTransform(-79.0748,515.2677,0.2765,0.2755);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgkDdIAAk1IBIAAIAAE1gAgfiUQgNgLABgSQgBgSANgMQAOgNARAAQATAAAMANQANANABARQgBASgNAMQgMAMgTAAQgSAAgNgNg");
	this.shape_14.setTransform(-85.8699,513.5387,0.2765,0.2755);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABaDYIhXlFIgCAAIhVFFIhaAAIh4mvIBRAAIBVFVIABAAIBelVIBPAAIBYFUIACAAIBRlUIBOAAIh1Gvg");
	this.shape_15.setTransform(-95.9416,513.6696,0.2765,0.2755);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_16.setTransform(-114.8199,518.8773,0.2765,0.2755);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_17.setTransform(-125.2649,518.8773,0.2765,0.2755);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_18.setTransform(-114.8199,508.4687,0.2765,0.2755);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_19.setTransform(-125.2649,508.4687,0.2765,0.2755);

	this.instance = new lib.Bitmap8();
	this.instance.setTransform(-130,433);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logomc, new cjs.Rectangle(-130,388,139.9,135.60000000000002), null);


(lib.CTAmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAGBAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgpQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAkAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAnQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgFAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgFIgXAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAANAwIAXAAIAAgVIgXAAgABRA/IgBgBIAAgiIgdAAIgBgBIAAgGIABgBIAdAAIAAgVIgYABIgBgBIAAgGIABgBIAYAAIAAgUIgaABIgBgBIAAgGIABgBIAjAAQAGgMADgJIACgHIAIADIACACIgCACIgLAVIAXAAIABABIAAAGIgBABIgggBIAAAUIAbAAIABABIAAAGIgBABIgbgBIAAAVIAjAAIABABIAAAGIgBABIgjAAIABAiIgBABgAD3AIQgFgEAAgEQAAgEAEgEQAXgXAWgbIAJAHQgVAYgXAWQgDADAAACQAAABAEADQAYAUAZAcIgIAHQgXgagcgZgACaA0QgGgHAAgPIAChXIAKAAIgCBWQAAAMAEAEQAFAFALAAQAQAAAJgKQAIgJAEgSIAKAFQgKApglAAQgRAAgHgHgAjBAyQAcAAANgHQAHgEAEgFQACgFAAgIQAAgJgGgFQgFgFgJAAQgRAAgNAOQgFAGgDAGIgLgCIAFg+IAKACIgEAqIgBAHIADgFQAHgIAKgEQAJgEAJAAQAQAAAIAIQAIAHAAANQAAALgFAIQgEAFgIAFQgHAEgOACQgLACgNAAgAkkA1QgMgHAAgPQAAgOANgHQAJgGAOAAQATAAAIAGQgOgNgKgWIgnACIgBgJQATAAASgCIgIgYIAKgCIAIAZQAPgCAPgDIABAJIgcAFQALAWARASIgGAIQgRgJgRAAQgOAAgHAGQgGAFAAAHQAAASAjAAQALAAAIgBIAAAKIgTABQgWAAgLgGgAhpAMQAAgXAHgrIAKAAQgIAqAAAYQAAAaAEATIgKAAQgDgUAAgZgAhGAwQgHgFAAgLQAAgIACgHIAJABIgBANQAAAHAEADQAFACALAAQAOAAAOgBIAAAKIgbABQgSAAgGgFgAAHAIIgBgBIAAgFQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAiAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAgAAHgKIgBgBIAAgFIABgBIAiAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAFQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAgAAAgdIgBgBIAAgGIABgBIAuAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAgAhIgnQARgBASAAIARAAIAAAKIgSgBQgSAAgQACgAi+g0IAEgIQAcAGAQAHIgFAJQgRgIgagGgABFgoQgDgJgGgJIAAgBIABgBIAEgBIABgBIABABQAGAIAEAJIAAABIgBABIgEACIgCABgAAGgwQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgFIABgBIAlAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape.setTransform(-176.925,231.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgPgeIAeAeIgeAf");
	this.shape_1.setTransform(-134.9584,231.7556,1.1799,1.1799);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0075D4").s().p("AmPB/QgeAAAAgdIAAjDQAAgdAeAAIMfAAQAeAAAAAdIAADDQAAAdgeAAg");
	this.shape_2.setTransform(-171.0381,231.7786,1.1799,1.1799);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTAmc, new cjs.Rectangle(-221.7,216.8,101.39999999999999,30), null);


(lib.commc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap14();
	this.instance.setTransform(-86,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.commc, new cjs.Rectangle(-86,-40,153,103), null);


(lib.bgmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap16();
	this.instance.setTransform(-151,-327);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bgmc, new cjs.Rectangle(-151,-327,160,600), null);


// stage content:
(lib._160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(270));

	// CTA
	this.instance = new lib.CTAmc();
	this.instance.setTransform(112.5,159.75);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(116).to({_off:false},0).to({x:242.5},12,cjs.Ease.get(1)).wait(142));

	// txt
	this.instance_1 = new lib.txt5();
	this.instance_1.setTransform(218.5,115.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(104).to({_off:false},0).to({x:233.5,alpha:1},12,cjs.Ease.get(1)).wait(154));

	// Layer_3
	this.instance_2 = new lib.txt7();
	this.instance_2.setTransform(53.35,316.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(101).to({_off:false},0).to({x:73.35,alpha:1},12,cjs.Ease.get(1)).wait(157));

	// Layer_2
	this.instance_3 = new lib.txt6();
	this.instance_3.setTransform(36.6,298.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(98).to({_off:false},0).to({x:56.6,alpha:1},12,cjs.Ease.get(1)).wait(160));

	// txt
	this.instance_4 = new lib.txt4();
	this.instance_4.setTransform(217.4,98.65);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(95).to({_off:false},0).to({x:232.4,alpha:1},12,cjs.Ease.get(1)).wait(163));

	// txt
	this.instance_5 = new lib.txt3();
	this.instance_5.setTransform(214.55,86.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(91).to({_off:false},0).to({x:229.55,alpha:1},12,cjs.Ease.get(1)).wait(167));

	// txt
	this.instance_6 = new lib.txt2();
	this.instance_6.setTransform(210.8,73.6);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(87).to({_off:false},0).to({x:225.8,alpha:1},12,cjs.Ease.get(1)).wait(171));

	// txt
	this.instance_7 = new lib.txt1();
	this.instance_7.setTransform(210.4,61.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(83).to({_off:false},0).to({x:225.4,alpha:1},12,cjs.Ease.get(1)).wait(175));

	// title
	this.instance_8 = new lib.title2();
	this.instance_8.setTransform(44.9,56.35);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(71).to({_off:false},0).to({x:59.9,alpha:1},12,cjs.Ease.get(1)).wait(187));

	// title
	this.instance_9 = new lib.txtTitle();
	this.instance_9.setTransform(70.25,32.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(67).to({_off:false},0).to({x:85.25,alpha:1},12,cjs.Ease.get(1)).wait(191));

	// com
	this.instance_10 = new lib.commc();
	this.instance_10.setTransform(-73.5,144.5);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({_off:false},0).to({x:91.5,y:134.5},33,cjs.Ease.get(1)).wait(218));

	// logo
	this.instance_11 = new lib.logomc();
	this.instance_11.setTransform(150.05,58.75);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(46).to({_off:false},0).to({alpha:1},24,cjs.Ease.get(1)).wait(200));

	// bg
	this.instance_12 = new lib.bgmc();
	this.instance_12.setTransform(151,327);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({_off:false},0).to({alpha:1},33,cjs.Ease.get(1)).wait(218));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#05132A").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(270));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-79.5,299.5,379.5,301);
// library properties:
lib.properties = {
	id: '542CFFE83C13439EB4A04353E49F32EB',
	width: 160,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap14.png?1632276413845", id:"Bitmap14"},
		{src:"images/Bitmap16.png?1632276413845", id:"Bitmap16"},
		{src:"images/Bitmap8.png?1632276413845", id:"Bitmap8"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['542CFFE83C13439EB4A04353E49F32EB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;