(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Bitmap79 = function() {
	this.initialize(img.Bitmap79);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,176,116);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtTitle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AF+BhIgCgBIAAgCIAAidQAAgVgBgLIAWACQABAAAAAAQABAAAAAAQABABAAAAQAAAAAAABIgBAEQgBAEAAATIAACeIAAACIgCABgACbBcQgHgIgHgEQAMgRADgYQAEgTAAgcIgBgdIABgCIACAAIArABIgJgTIgiAAIgDAAIAAgDIAAgNIABgCIACAAIBFAAIAAgCQAAgLgBgIIAWABQABABAAAAQABAAAAAAQABABAAAAQAAAAAAABIgBADQgBADAAAIIAAADIBGAAIACAAIAAACIAAANIAAADIgCAAIggAAIgLATIAygBQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAOQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIiVgBIAAANQAAATgCATQAOgOAKgWIADgLIASAFQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIgBACIgEAHIgBACIAZAAIAAgCQAAgJgCgIIAWABQABAAAAAAQABABAAAAQABAAAAABQAAAAAAAAIgBAFIgBAJIAAACIAyAAIACAAIAAADIAAAOIAAACIgCAAIgygBIAAAQIAqAAIACAAIAAACIAAAPIAAABIgCABIgqgBIAAASIA/AAIACAAIAAACIAAAPIAAACIgCAAIiUAAIgCgBIAAgBIAAgPIAAgCIACAAIBAAAIAAgSIgmABIgDgBIAAgBIAAgPIABgCIACAAIAmAAIAAgQIgiAAIgPAWQgCADgCAAIgDgCQgEgHgGgEIgCANQgEAYgLAWQgDAEgBAAIgDgDgADjgmIAfAAQAGgKADgJIgwAAgAGhBZIgCAAIgBgCIAAgQIABgCIACAAIA3AAIAAgqIgnABIgCgBIgBgBIAAgRIABgCIACAAIAnABIAAgkIgaAAIgKAYQgCAEgCAAIgEgBQgHgGgIgBQAGgJAEgLIgJADIgCABQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBQgCgPgFgMIgBgCQAAAAAAAAQABgBAAAAQAAAAABAAQABAAAAAAIAIgEIACAAQABAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAGARACAIQAHgRADgQIACgPIAUAEQABABAAAAQABABAAAAQABAAAAABQAAAAAAABIgBACIgDAHIgDAQIATAAIAAgPQAAgSgCgOIAXACQABAAABAAQAAAAABAAQAAABABAAQAAAAAAABIgBAEQgCAEAAATIAAAQIAsAAIACAAIAAACIAAAQIAAACIgCAAIgsAAIAAAkIAmgBIACABIAAABIAAARIAAABIgCABIgmgBIAAAqIAyAAIACAAIAAACIAAAQIAAACIgCAAgAkfBCQguAIhGAIIgFgWIAPgBQAXhAAThOIAXAGQgSBCgYBDQAqgDAigFQgLgZgOgZIAUgIQAXAmAUA0IgXAJgAq1BJQAfgNALgQQAKgQABgcIhBAAIAAgTIBBAAIAAghIgvAHIgJgTQA+gFAugPIALATQgRAFgXAFIAAAkIA1AAIAAATIg1AAQgBAlgQAWQgNASgeAMgAJUBQQgJgIAAgQQAAgPALgLQALgLAcgOQgBgJgDgDQgCgDgFAAQgKAAgNAKQgKAIgOARIgQgOQAcgcAPgcIglAAIAAgTIAtABIAJgcIAWADIgJAYQAegBAZgDIAAASIhAAEQgHANgJALIgFAEIABABIAFgDQAIgHAKABQAKgBAHAIQAHAFACALIAqgSIAIAUQgcAIgVAJIAAApIgUAAIAAgfQgTAJgGAIQgGAFAAAHQAAAIAIAEQAIADAVAAQAYAAAfgDIABAUQgcACgeAAQghAAgMgJgAilBHQAggHANgSQALgPAAgZQAAgggNgRQgKgMgRAAQgEBDgQAmQgHAQgJAFQgIAFgKABQgQAAgKgRQgJgQAAgbQAAgpAYgZQALgMAPgGQAPgFAQAAQBHgBAABSQAABAhEAQgAjKgiQgQAUAAAgQAAAUAGAJQAEAIAGAAQAEAAAEgDQADgEADgHQAHgUAFgbQAEgZABgXQgRACgOASgAB2BXIixAAIgCAAIgBgDIAAgSIABgCIACAAIBOABIAAgnIgzABIgCgBIAAgBIAAgRQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAzAAIAAgjIgrAAQgIAQgKANIgEADIgFgDQgGgFgHgDQAVgaANgkIADgNIAUAEQAEABAAADIgCADQgCACgCAHIgFANIAhAAIAAgLQAAgUgBgLIAXABQABAAABAAQAAAAABAAQAAABABAAQAAABAAAAIgBAFQgCADAAATIAAAMIBBAAIACAAIAAACIAAASIAAACIgCAAIhBgBIAAAjIA3AAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAARIgBACIgCAAIg3gBIAAAnIBMgBIACABIABABIAAASIgBADIgCAAgAogALIAAgWIB3AAIAAAWgAFtAAIgLgDQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgBQAGgSABgZQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAgBABAAIACABIAKACQABAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAABQgBAdgGAQIgBABIgCgBg");
	this.shape.setTransform(-2.125,5.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txtTitle, new cjs.Rectangle(-72.7,-4.2,141.2,19.3), null);


(lib.txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHzAdQgCgDAAgDQAAgFADgDQADgCAEAAQAFAAACADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgEgEgAH3ATIgBAEQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAABIAEABQABAAAAAAQABAAAAAAQABAAAAgBQABAAABAAIABgEQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABgABlAdQgCgDAAgDQAAgFADgDQADgCAEAAQAFAAADADQACADAAAEQAAAEgDADQgDADgEAAQgFAAgDgEgABoATIgBAEQAAAAABABQAAABAAAAQAAABAAAAQABAAAAABIAEABQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIACgEQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBABgAiRAfIgCgGIAIAAIACgBIAAgFIgOAFIgCAAIgBgBIgDgEQAOgCAJgGIgVABIgBgBIAAAAIAAgFIAAAAIABgBIAdABIAAgEIgEAAIAAgBIgBgCIACAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBIAAgCIgGAAIAAAIIgBABIgFAAIgBgBIAAgIIgGAAIAAAEIABACIgBABIgBAAIgEAAIgBAAIAAgLIABgBIALAAIAAgDIgOAAIgCAAIAAgEIABgBIAFAAIgCgBIgDgBIAFgHIABgEIAFABIABABIAAABIgBACIAAAAIAEAAIAAgGIAGABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABIAAABIAAADIALAAIAAAAIABABIAAADIgBABIgLAAIAAADIAOAAIAAAFIgOAAIAAADIALAAIABABIAAAHIgBADIACAAIABABIgBABIAAADIAagBIAAABIABAAIAAAFIgBAAIAAABIgKgBIAFAEIAAABIAAABIgDABIgEADIAPAEIgEAEIgCACIgBAAQgTgGgHgOIgBAAIgGAFIAAAHIAOgCIgBAEIAAABIgCABIgVAEIgCABIgBAAIgBgBgAhwARIAGgDIABgDIgMAAQACAEADACgADnAgIgFAAIgBAAIAAgdIgGABIgCAAIgBAAIgBgBIgBgFIAFABIAFgGIgKgKIAAAAIAAgBIADgEIAAgBIABABIACACIAEgIIABgEIAGADIABABIAAABIgCABIgGAKIADADIAFgHIACgFIAFADIACABIgCABIgCADIgLAPIAJAAIgCgEIAAgBIABAAIACgCIABAAIABABIAFALIAAgcIAAgBIAgAAIAAABIAAA2IAAABIgGAAIAAgBIAAgDIgTAAIAAADIgBABIgGAAIAAgaIgBABIgEABIgBAAIAAgBIgBgDIgEABIAAAdIgBAAgAEGATIAHAAIAAgRIgHAAgAD6ATIAFAAIAAgRIgFAAgAEGgDIAHAAIAAgRIgHAAgAD6gDIAFAAIAAgRIgFAAgAC5AgIgBAAIAAgBIAAgPIgNAAIAAgHIANAAIAAgIIgLAAIAAAAIAAgEIAAgBIALAAIAAgHIgMAAIAAgBIAAgFIAAgBIASAAIAEgKIABgDIAGACIABABIgBABIgBACIgDAHIAKAAIAAABIAAAFIAAABIgQAAIAAAHIAMAAIACAAIAAABIAAAEIgCAAIgMAAIAAAIIAQAAIABAAIAAAHIgBAAIgQAAIABAPIgBABgACZAgIgGAAIAAgBIAAgPIAAgHIAAAAIAUAAIACAAIAAAAIgBAGIABAPIgBAAIgBABIgEAAIgBgBIAAAAIAAgCIgIAAIAAAEIgBAAgACaAWIAIAAIAAgIIgIAAgAgzAgIgBgBIAAgdIAAgBIAbAAIAAABIAAAIIAAAUIAAABIgHAAIAAgBIAAgDIgMAAIAAAEIgBAAIAAABgAgsAVIAMAAIAAgNIgMAAgAhTAgIgBgBIAAAAIAAgdIAAgBIAZAAIABAAIAAAdIgBABIAAAAIgFAAIgBgBIAAgDIgMAAIAAAEIAAAAIgBABgAhNAVIAMAAIAAgNIgMAAgAkRAgIgGAAIAAgpIABgBIAXAAIABABIAAAhQAAAEgCACQgBABgHAAIgCAAIgBgCIgBgEIAFAAIACgBIAAgBIAAgGIgLAAIAAAPIgBAAgAkQAMIALAAIAAgGIgLAAgAkQABIALAAIAAgFIgLAAgAjxAfIgBgCQAAgBAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBIAHAAIADAAIAAgCIAAgXIAAgKIAHABIABAAIAAACIgBAHIAAAYQAAAFgDACIgDABIgHAAIgBAAgAHGAXIABAAQAOAAAGgEQAHgDgBgHQAAgEgDgCQgCgCgEAAQgIAAgGAGQgDAEgBADIgHgCIADgeIAHABIgDASIgBAFIADgEQAGgGAKAAQAIAAAFAEQAEADAAAIQAAAFgCAEQgDADgFACQgHAEgPABgAAwAXQAMgBAGgFQADgCABgEQgDADgFAAQgGAAgDgDQgDgDAAgFQAAgFAEgDQADgDAGAAQADAAACABIAAgHIgbABIAAgGIAbgBIAAgJIAHAAIAAAJIAQAAIAAAGIgQAAIAAAOQABADAAAFQAAAKgGAFQgGAFgMACgAA6gBQAAAAgBABQAAAAAAAAQgBAAAAABQAAABAAAAQAAABAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQADAAACgCIABgEQAAgFgGAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABgAmrAYQAJgCAFgDQAEgCADgFQACgFAAgIIAAgaIAIAAIAAAbQAAAOgIAHQgFAGgNADgAncAYQAIgCAEgDQAFgCACgFQACgFAAgIIAAgaIAIAAIAAAbQAAAOgHAHQgGAGgNADgAGTAXQARAAAEgDQAGgDAAgGQAAgIgJAAQgFAAgEACQgFADgEAGIgHgEQAFgKADgNIgLAAIAAgGIANAAIABgKIAIAAIgCAJIAVgBIAAAGIgXACQgCAKgFAHIABAAQAGgGALAAQAHAAAFAEQADADAAAHQABAJgJAFQgHADgSAAgAEfAGQAAgNAEgVIAHABQgEAUAAANQAAAKACAMIgHABQgCgMAAgLgAgDAGQAAgHAEgGQAEgGAGgEIADgBIAAgBIgEACIgZACIgBgHIAtgCIAAAGQgGABgFACQgPAIAAANQABAOAVACIgCAHQgagCAAgVgAi+AXQALgCAEgGQAEgFAAgIQAAgKgFgGQgDgEgGAAQgBAWgFAMQgCAFgDACQgDACgEAAQgFAAgDgGQgDgFAAgJQAAgNAIgIQAEgEAFgCQAEgCAGAAQAYAAAAAbQgBAVgWAFgAjKgLQgGAHABAKQAAAGACADQAAABAAAAQABABAAAAQABAAAAABQABAAAAAAIADgBIACgEQACgGABgJIACgQQgGABgEAGgAk3AIQgJANgQAIIgEgGQAOgHAJgMQAHgJADgNIgdAAIAAgGIAkAAIADACQgEAOgFAKQAHAJAIAOIgHAEQgFgLgIgKgAFaAPQAAgFADgGIAHACQgDAFAAAEQAAADADACQAEABAGAAIATgBIAAAIIgTABQgUAAAAgOgAEtATQAAgFAFgDQADgCAFAAIAGAAIAAgTIgTABIAAgHIASAAIAAgMIAIAAIAAAMIALgBIAAAGIgLABIAAAVQAHADAGAGIgFAGQgEgFgEgDIAAABQAAAFgDACQgDADgGAAQgOAAAAgKgAE1AQQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAEAIAAQAFAAAAgGIAAgBQgCgCgEAAQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBABgADZAaIgDgBQACgIABgGIAAgEIAFABIABABIAAABIAAACIgDANIgBACgADsAWIgCgNIAAAAIAAgBIADgBIABAAIAAABIAEAMIAAAAIgBABIgEABIgBABIAAgBgAj4ARIAAgQIAAgJIAHAAIABABIgBACIAAAGIAAAPIAAABgAmuAHIAAgiIAIAAIAAAigAngAHIAAgiIAHAAIAAAigACmAFIgLAAIgGAAIgBAAIAAgFIAAAAIASAAIABAAIAAAEIAAABIgBAAgAmBADIAAgGIAnAAIAAAGgAASgIIAEgCQAEAFACAGIgFACIgFgLgAhtADIgBgCIgCgEIAGABIACgBIABgCIAAgRIgBgJIAHAAIABABIAAACIgBAGIAAATQAAADgBABQgDACgGAAgAn3gGIgGAIIgEgCIAGgIIgJgCIACgFIAJADIgCgKIAHAAIgBAKIAIgDIACAFIgJACIAHAIIgFACgAAbgKIAEgCIAFALIgFABIgEgKgACmgDIgRAAIgBAAIAAgGIAAAAIASAAIABAAIAAAGIgBAAgAgjgEIgnAAIAAgZIAnAAIABAAIAAAZIgBAAgAhDgLIAZAAIAAgLIgZAAgAFogLIALgHIgJABIgMgBIAAgGIANAAIATgBIABAHIgHAEIgMAIgAhzgGIgBAAIAAgBIAAgOIgBgHIAHABIABABIAAABIAAAEIAAAOIAAABgACRgNIAAgFIAAgBIAZAAIAAABIAAAFgAkbgPIgBAAIAAgBIAAgFIABgBIARABIgEgHIAAgBIABgBIAEgBIABgBIAAABIAFAHIAAAAIgGADIAQAAIAFgHIABgEIAHACIABABIgBABIgCACIgDAFIASgBIABABIAAAFIAAABgAHTgVIgLgDIADgGIAMADIAKAEIgDAGIgLgEgAC0gTIgGgJIAAAAIABgBIAFgCIABAAIAAABIAFAIIAAABIgBAAIgFADIAAgBgACngXIgTAAIgBAAIAAgFIAAgBIABAAIATAAIACAAIAAABIAAAFIgCAAg");
	this.shape.setTransform(-10.05,10.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt5, new cjs.Rectangle(-61.7,7,103.4,6.6), null);


(lib.txt4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIuAuQgDgEAAgGQAAgGAEgFQAFgEAFAAQAIAAAEAFQAEAEAAAGQAAAHgFAEQgEAEgHAAQgGAAgFgFgAIzAeQgCACAAAEQAAAEADADQACACADAAQAFgBACgCQADgCgBgEQAAgEgCgDQgDgBgEAAQgEAAgCACgAFHAxQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAg4IABgBIABAAIAjAAIABAAIAAABIAAAtQAAAHgCACIgEACIgHAAIgEAAIgBgDIgCgGIAHAAQAAAAABAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAgIIgSAAIABAUIgBABgAFPAUIASAAIAAgHIgSAAgAFPAFIASAAIAAgGIgSAAgAEPAwIAAgDIgDgIIAMAAIAEAAIABgDIAAg/IhEAAIgBAAIAAgCIAAgIIAAgBIABAAIBaAAIABAAIAAABIAAAIIAAACIgBAAIgCAAIgIAAIAABBQAAAHgDADQgEACgQAAIgDAAgAF3AuQgDgCgBgGIAAgaIAAgLIAKABQABAAAAABQAAAAABAAQAAAAAAAAQAAAAAAAAIgBADIAAAFIAAAFQAJgDAHgEIAGgFIAHAHIABACQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgEACIgXAKIAAAIQAAABAAAAQAAABABAAQAAABAAAAQAAAAABAAQABABAIAAQAIAAACgCIABgDIABgGIAHACIACABIAAABIAAACIgBAIIgEAEQgEADgNAAQgNAAgEgCgAj5AmQAQgGAFgLQADgEABgGIABgPIggAAIAAgKIBFAAIAAAKIgaAAQAAANgCAIQgBAGgDAFQgEAGgFAEQgGAFgIADgAnwAqIAAhPIAMAAIAABGQANgGALgKQAJgLAFgNIAJAIQgIATgOALQgMAKgRAFgApEAlQAYgIAKgPQAJgOABgYIgwAAIAAgKIA1AAIgBgEQAAgFADgDQAEgEAEAAQAGAAADAEQADADAAAFQAAAGgDADQgEADgFAAIgCAAQgBAggOASQgLANgZAJgAoOgrQAAABAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAADACACQAAABABAAQABAAAAABQABAAAAAAQABAAAAAAQAEAAACgCQABgCABgDQgBgDgCgCQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBAAgBAAQgCAAgDABgAAuAkQAdgHAPgUQALgNACgZIAMAFQgFAcgPARQgQASgbAHgAlOAkQAdgHAOgUQALgNADgZIALAFQgFAcgPARQgPASgcAHgAGtALQAAgLACgQIADgXIAMACQgDAMgCAPIgBAVQAAATACAPIgKABQgDgQAAgTgACXAsIgCgKIAKABIAFgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAgBQAEgIAAgXQAAgHgCgDQAAgBgBAAQAAgBAAAAQgBAAgBAAQAAgBgBAAIgJABQgIAhgMAZIgKgEQAMgZAHgdIgSADIgBgKIAVgCIAFgVIAKACIgEATIAIgBQAIAAAEAFQAEAFgBALQAAAZgCALQgCAFgEAEQgEACgGAAIgLgBgAhkAjQAagGAOgOQAHgHAGgKQAEgLACgMIAKAGQgCANgGALQgFAKgHAHQgQARgcAGgAgQAtIAAgKIAjAAIAAgUIghAAIAAgKIAhAAIAAgQIgjAAIAAgJIAuAAIAABBgAmSAnQgFgDABgKIAAghIgRADIgDgJIAUgEIAAgZIALAAIAAAWIAjgIQgDgIgFgIIAIgCIAIASIgEABIAFAGQgFANgFAJQgFAIgIAJIgJgHQAPgPADgNIgeAHIAAAkIABAEQABABAEACIAKAAQAOAAAMgCIAAAMIgcABQgQgBgFgEgAHIAlQgFgEAAgIIABgLIAKABIgBAHQAAAGAEABQADACAGAAIAWgBIAAALIgVABQgNAAgGgFgADtAdIgIAAIgBAAIAAgBIAAgsIAAgBIABAAIAoAAIABAAIAAArIAAABIgBAAIgIAAIgBAAIAAgBIAAgFIgWAAIAAAHIAAABIgBAAgADuALIAWAAIAAgSIgWAAgACvgaIAJgFQANAPAIAVIgKAFQgHgVgNgPgAivAHIAAgLIA7AAIAAALgAIOgHIgHANIgIgGIAKgKIgPgDIAEgIIANAFIgCgPIAKAAIgCAPIANgFIADAIIgOADIAKAKIgIAGgAhqgGIAGgJQARAHAJAEIgGAKQgJgGgRgGgAF3gDQgDgBgBgFIAAgZIAAgLIAKABQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIgBACIAAAGIAAAFQAJgDAGgEIAGgEIAGAHIACABIgCABIgFADQgIAEgOAFIAAAFQAAABAAABQAAAAAAABQABAAAAAAQAAABABAAIAHABQAKAAABgDIACgDIAAgGIAHAEIACABIABABIAAABQgBAFgBADIgEADQgDADgOAAQgMAAgEgCgAAtgZIAIgJQAOAIAMAJIgHAKQgNgKgOgIgAlPgZIAHgJQAOAIAMAJIgHAKQgMgKgOgIgAFpgNIgCgEIggADIgEABIgBAAIgCgCIgCgJIAJAAIAGgOIACgHIAKABIACACIgBACIgCADIgGAMIAQgBIgEgHIAAgBIABAAIAFgDIABAAIABAAQAGAHAFAMIAAABIAAABIgIAEIAAgBgAhhgcIAGgJQAPAGALAGIgGAJQgKgGgQgGgAHGgbIAbgBIAPABIAAAKIgPgBIgbABgAC3gsIAHgCIAIARIgHACQgDgKgFgHgAj5gbIAAgJIA6AAIAAAJgAljgvIAHgCQAFAIACAIIgHADQgDgKgEgHgADEgvIAGgDQAFAIADAJIgHACQgDgJgEgHg");
	this.shape.setTransform(2.2,6.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt4, new cjs.Rectangle(-56.3,1.2,117,10.200000000000001), null);


(lib.txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGvAcIAJgIQAMAKAJAOIgJAHQgJgNgMgKgACXAcIAKgIQAMAKAJAOIgKAHQgIgNgNgKgAFeAxIgBAAIAAgBIAAgtQgHAJgHAFIgCACIgDgCIgFgHQATgLAKgUIgaAAIgBAAIAAgBIAAgIIAAgBIABgBIAfABIABgEIACgLIAKACQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIgBACIgCAFIgBAFIAwgBQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAIIgBABIg0AAIgEAIIArAAIABAAIAAABIAAAxQAAAGgEADIgFACIgKAAIgDAAIgBgCQgBgFgCgDIAKAAIADAAIACgDIAAgHIgjAAIAAAVIgBAAgAFoATIAjAAIAAgHIgjAAgAFoADIAjAAIAAgGIgjAAgAEwAwQgRgJgLgNIgBgBIAJgGIABABQAMANARAGIgFAHIgDACgADjAuQgDgDgDgDQAQgGAIgJIAEgGIAJAFIACACIgCABIgDADQgIAKgQAIIgCAAIgCgCgAl9AmQAWgFAKgMQAIgLACgQIgyAAIAAgKIA+AAQgBAfgOAOQgKAMgXAGgAjbApIAAhOIANAAIAABFQANgFAKgKQAJgLAGgNIAJAIQgJATgOALQgMAJgRAGgABJAkQAdgHAOgTQAKgOADgZIALAFQgEAcgPARQgPASgcAHgAkbAuIAAg9IggAAIAAgJIAgAAIAAgSIAMAAIAAASIAgAAIAAAJIggAAIAAA9gAhKAjQAbgGAOgOQAGgHAFgLQAFgKACgMIAKAGQgCANgGALQgFAKgGAHQgRARgcAGgAAJAtIAAgKIAlAAIAAgVIgjAAIAAgJIAjAAIAAgQIgkAAIAAgKIAuAAIAABCgAnNApIAAgKIArAAIAAg2IgrAAIAAgKIA4AAIAABKgAkHgBIALgEQAHAYAIAOIgLAGQgHgQgIgYgAk+AiQAMgSADgVIALAEQgDAMgEAKQgDAKgGAIgAE6AQIhcAAIgBgBIAAgIQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAXABIAAgUIgRAAIgBAAIAAgBIAAgIIABgBIARAAIAAgFIAAgPIALABQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgBACIAAALIAAAFIAXAAIAAgFIgBgPIALABQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAACIAAALIAAAFIATAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAAAAAIAAAIIgBABIAAAAIgTAAIAAAUIAYgBIABABIAAABIAAAIIAAABIgBAAgAEAAGIAXAAIAAgUIgXAAgAiVAHIAAgLIA8AAIAAALgAhPgGIAEgJQASAHAJAEIgFAJQgKgFgQgGgABIgYIAGgKQAPAIAMAJIgHAKQgMgKgOgHgAhGgcIAFgJQAPAGAKAGIgFAJQgKgGgPgGgAl/gbIAAgKIAzAAIAAAKgAkDgtIAHgDQAEAIADAJIgGADQgEgKgEgHgAj2gwIAHgCQAFAIADAJIgIACQgDgJgEgIg");
	this.shape.setTransform(-7,5.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-53.1,0.2,92.30000000000001,10.200000000000001), null);


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgrAcIAKgIQANAKAJAOIgKAHQgJgNgNgKgAB6AmQARgCAGgKQAFgFABgIQABgGABgLIgBgkIAKAAIABAkQAAAOgBAJQgCAGgFAGQgEAGgGAEQgHADgKADgAIPAqQgEgDAAgIQAAgHAHgFQAFgEAJAAIAIABIgBgYIAKAAIACAbQAKAEAKAIIgHAKQgHgIgGgEIAAACQgBAIgFAEQgFADgKABQgKgBgFgEgAIUAfQABAHAJAAQAKAAAAgJIAAgDQgDgCgEAAQgMABgBAGgAFCAjIg7AHIgCgLIAIAAQALggAJgnIANAEQgKAggMAiIAmgEQgFgNgIgNIAKgDQAMASAKAaIgMAGgAhqAlIABAAQAUgBALgFQAJgFAAgJQAAgHgEgEQgDgDgHAAQgNAAgIAKQgFAGgBADIgLgCIAEgtIALABIgEAcIgBAHIADgGQALgJAOgBQANABAGAFQAHAGgBALQAAAIgDAGQgEAEgHAEQgLAGgXABgAi4AqQgEgDAAgIQAAgHAHgFQAGgEAIAAIAIABIgBgYIAKAAIABAbQALAEAKAIIgHAKQgHgIgHgEIAAACQAAAIgFAEQgGADgJABQgKgBgFgEgAizAfQAAAHAKAAQAKAAAAgJIAAgDQgDgCgFAAQgLABgBAGgAnwAmQAYgJAMgRQgIgHgMgFIAGgIQAMAGAHAFQAGgLACgPIgcAAQgHASgNALIgJgGQAJgHAHgNQAGgKADgNIALADIgCAIIAcAAQgDgIgEgFIAHgDIAIARIgFACIAFAFQgHAfgOAQQgLANgXALgAHJAOQgNATgZANIgGgJQAUgLAOgRQALgPAEgTIgrAAIAAgKIAxAAIAEALIADAAQgFARgHALQAMAOAMAVIgLAHQgIgRgLgPgADfAOQgOAUgXAMIgHgJQAVgLAOgRQALgPADgTIgqAAIAAgKIA2AAIACAEQgEAVgIAOQALAOAMAVIgLAHQgIgSgLgOgAmfAkQAdgHAOgTQALgOADgZIALAFQgEAdgQAQQgPASgcAHgAAgApQgEgFgBgHQABgIAHgEQAFgFAJAAIAJABQgCgPgBgoIAMAAIAAAVIAbgCIABAJQgOACgOAAIACAaQAQAGANAMIgHAKQgKgOgLgDIAAAEQAAAQgXABQgKgBgFgEgAAoAYQgCACgBADQAAAHALAAQALAAAAgIIAAgGIgKgBQgGABgDACgAoqAqQgGgDABgKIAAgbIgXAAIAAgIIAXAAIAAgUIgTAAIAAgKIA9AAIAAAKIgfAAIAAAUIAjAAIAAAIIgjAAIAAAbQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAIAJABIAVgBIAAALIgUABQgOAAgEgDgAkLAgQgJgJAAgRQAAgQALgMQALgLAQAAQALABAHADIAAAMQgIgEgIgBQgMAAgIAIQgIAHABAMQAAAMAGAIQAIAHALAAQAKAAAIgFIAAALQgJAEgMAAQgQAAgKgKgAlNApIAAhIIAXAAQAMAAAIAGQAGAGAAALQABAJgIAHQgHAHgNAAIgKAAIAAAagAlBAFIAIAAQAIAAAFgDQADgDAAgHQAAgNgPAAIgJAAgAH2AbQALgWAHgVIgRABIAAgKIAHABIAMgBIADgRIALABIgDAQIAOgCIAAAKIgRABQgHAXgLAYgAjRAbQALgWAHgVIgRABIAAgKIAHABIAMgBIADgRIALABIgDAQIAOgCIAAAKIgQABQgIAXgLAYgABygDQAAgNADgYIAKABQgDAWAAAPIAAAHIAHgOIAGAFQgFAHgDAIIgCAHIgLAAQgCgLAAgKgAFZAHIAAgLIA7AAIAAALgAmggYIAHgJQAPAHALAJIgHALQgMgMgOgGgAIogVIAFgIQAQAFAKAHIgGAKQgJgIgQgGgAifgVIAFgIQAQAFAKAHIgGAKQgKgIgPgGgAhWgeIgRgEIAEgJIATAEQAJADAHADIgGAJQgGgDgKgDgAHUgtIAHgCQAEAHAEAKIgHADQgDgLgFgHgAHhgwIAGgCQAFAIADAJIgHACQgDgJgEgIgAm0gwIAHgCQAEAIADAJIgHACQgDgKgEgHg");
	this.shape.setTransform(8.6,4.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-49.7,-0.8,116.60000000000001,10.200000000000001), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHeAsQgDgEAAgGQAAgGAEgFQAFgEAFAAQAIAAAEAFQAEAEAAAGQAAAHgFAEQgEAEgHAAQgGAAgFgFgAHjAcQgCACAAAEQAAAEADADQACABADAAQAEAAADgCQACgCAAgEQAAgEgDgDQgCgCgEAAQgEABgCACgAjPAwQgQgEgMgIIgBgBIABgBIAGgEIACgBIgiAAIAIAEIACACQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgFACQgKAGgNADIgCAAIgCAAIgBgDQgBgEgDgCQAOgCAJgEIAFgEIgRAAIgBAAIAAgBIAAgrIAAgBIABAAIBGAAIABAAIAAABIAAArIAAABIgBAAIgSAAIABABQAMAGARADQgEACgCAEIgDADIgBAAgAkNAVIAyAAIAAgFIgyAAgAkNAIIAyAAIAAgFIgyAAgAkNgDIAyAAIAAgFIgyAAgAFBAwIgBgBIAAgBIAAgeQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIA0AAQABAAAAAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAeIgCABIgJAAIgBgBIAAgEIggAAIAAAFIgBABgAFLAiIAgAAIAAgKIggAAgAEzAwIgJAAIAAgCIAAgzIgHAHIgCACIgBgDQgBgEgCgEQAMgNAGgUIACgIIAKADQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIgBADIgCAEIgFAMIAABHIAAACIgBAAgADqAwIgIAAIgBAAIAAgCIAAgqIgDAEIgCABIgBgCIgDgHIAAAjIAAABIgBAAIgHAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgEIgIAAIAAAJIAAABIgBAAIgIAAIgBAAIAAgBIABgiIgEAHIgCABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQgBgGgCgDQAMgMAEgWIgMAAIgBAAIAAgBIAAgIIAAgBIABAAIAhAAIABAAIAAABIAAAEIAUAAQACgGAAgFIAKABQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAAAIgBACIgCAGIgBABIAcAAIABAAIAAABIAAAEIAAAMIAAABIgBAAIgHAAIgBAAIAAgBIAAgIIgXAAQgDAIgEAHIALAAIACgGIABgGIAJACQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAABIgCADIgCAEIAQAAIAAABIAAAGIAAABIgBAAIgRAAIAAAHIAPAAIABAAIAAABIAAAFIAAABIgBAAIgPAAIAAAIIAPAAIABAAIAAABIAAAGIAAABIgBAAIgPAAIAAAIIAUAAIABAAIABABIAAAHIgBAAIgBAAIgpAAIAAAEIAAACIgBAAgADrAiIAMAAIAAgIIgMAAgADHAWIAIAAIAAgWIgIAAgADrASIAMAAIAAgIIgMAAgADrADIAMAAIAAgHIgMAAgADYgKIAAABIAAAJQAMgLAHgQIgJAAIAAAIIAAABIgBAAIgHAAIgBAAIAAgBIAAgMIgLAAQgCALgFALIAQgBIABAAgAlaAwIgIAAQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAgBIABgDIAAgRQgNAMgUAHIgDAAIgDgCIgDgHQAVgFAMgJIgfAAIAAAAIAAgBIAAgGIAAgBIAAAAIAoAAIAAgGIgeAAIgBAAIAAgBIAAgGIABgBIAeAAIAAgEIgiAAIgBAAIAAgHIAAgBIABAAIAVAAIgEgHIAAgBIABgBIAHgBIgfAAIAAAAIAAgBIAAgHIAAgBIAAAAIAPAAIgGgJIAAgBIAAgBIAHgDIABAAIABAAQAFAGACAEIAAABIgBACIgDABIAKAAIAAgHIgBgJIAKAAQABAAAAABQAAAAABAAQAAAAAAAAQAAAAAAAAIAAACIgBAGIAAAHIAIAAIAAgHIgBgJIALAAIABABIAAACIgBAGIAAAHIAGAAIAGgJIABgGIAKADIACACIgBACIgCABIgFAHIAPAAIABAAIAAABIAAAHIAAABIgBAAIgfAAIAIABIACABIgBACIgCACIgCAEIAVAAIABAAIAAABIAAAGIgBABIgjAAIAAAEIAeAAIABAAIABABIAAAGIgBABIgBAAIgeAAIAAAGIAoAAIABAAIAAABIAAAGIAAABIgBAAIgfAAQALAJAXAEIgEAHIgCADIgDgBQgUgFgOgNIAAAUIAAACIgCAAgAlqgWIAEAKIARAAIADgHIABgDIgbAAIACAAgAnqAwIgBgCIAAgnIgGAGIgCABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBgBAAQAAgFgDgDQAMgIAIgOIADgFIAIAFIABACIgBACIgDADIgFAHIABAyIgBACgAgVAvQgQgKgNgGQgPALgcAEIgCAAIgCAAIgBgCQgBgEgCgEQAZgCAOgIIgPgFIgDAEIgBAAIgBAAIgHgCIgBgCIABgBIAEgGIAIgNIgXAAIgBAAIAAgBIAAgHIAAgBIABAAIAcAAIACgFIAFgKIALACIABABIgBACIgDAFIgDAFIAzAAIABAAIAAABIAAAHIAAABIgBAAIgUAAQgFAOgIAIIAcANIABABIgBACIgEAHIgCABgAhHANIATAGQAHgHAEgLIgYAAgAnZAtIgGgFQAGgJADgKQACgIABgLIAAgGIAKABQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIgBABIgCARQAEAJAIAEIAAgrIgXAAIgBgBIAAgIIABgCIAeAAIAIgOIABgHIALADIABACIgBABIgCADIgGAMIARAAIABAAIAAACIAAAIIgBABIgZAAIAAAPIAUAAIABAAIABACIAAAHIgBACIgBAAIgUAAIAAAVQAIACAKAAIAMgBIgCAIIgCADIgDABIgBAAIgGgBQghAAgJgTQgDALgFAIIgCACIgCgCgAAiAqQgFgCAAgHIAAgoIgBgMIALABQABAAABAAQAAAAAAABQABAAAAAAQAAAAAAAAIAAADQgCABAAAGIAAAjQAAABABABQAAABAAAAQAAABABAAQAAABABAAQABABAIAAQAHAAADgCQACgCAAgEIABgLIAIADIACABIABACIAAABQAAAJgCAEIgDAGQgDADgFAAIgMABQgOAAgDgDgAGYAnQgFgDABgJQgBgHAGgFQAFgGAPgHQAAgEgCgBQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgFAAgGAFQgGAEgHAIIgHgHQAOgNAHgOIgSgBIAAgJIAWAAIAFgOIAKACIgDAMIAbgCIAAAJIggACQgEAHgFAFIgCACIABAAIACgBQAEgDAFAAQAFAAAEADQADADABAGIAVgKIAEAKIgYAIIAAAVIgKAAIAAgQQgKAFgDAEQgDADAAADQAAAEAEACQAFACAKgBIAbgBIAAAKIgcABQgRAAgGgFgAi2AJQAAgKACgRIADgXIAMACQgDAMgCAPIgBAVQAAATACAOIgKABQgDgQAAgSgAB1AlQgHgFAAgLQAAgQASgLQgEgPgDgWIALgBQACASAEAOIAZgNIAFAKQgXAJgMAIQgHAFgCAFQgEAEAAAFQAAAGAGADQAFADAKAAQAOAAANgBIAAAKIgZABQgSAAgIgGgAibAjQgFgEAAgIIABgLIAKABIgBAIQAAAEAEACQADACAGABIAWgCIAAALIgVABQgNAAgGgFgAAKAeIgIgEIgBgBIAAAAQAHgQADgRIAAgBIACAAIAHACIACACQgCARgIASIgBABgABWAZQgEgRgKgPIAAAAIABgCIAIgCIABgBIABABQAJAOAFARIAAABIgBABIgIAEIgBAAIgBgBgAFEAJIgCAAIAAgBIAAgHIABgBIABAAIAvAAIABAAIAAABIAAAHIAAABIgBAAgAFEgEQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgHIABgBIAwAAIABAAIAAABIAAAHIgBABgAgNgNIgJAAIgBAAIAAgBIAAgNIhBAAIAAANIAAABIgBAAIgJAAIgBgBIAAgVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAkAAIAAgBIAAgKIALAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAACIgBAHIAAABIAmAAIABABIAAAVIAAABIgBAAgAnzgTQgBgDgDgEQAKgGAIgKIADgFIAJAFIABACIgBABIgDADQgIAKgKAIIgCABQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBgBgAF9gTIhCAAIgBAAIAAgBIAAgHIAAgBIABAAIBCAAIABAAIABABIAAAHIgBABIgBAAgAidgdIAbgBIAOABIAAAJIgOAAIgbABgAjXgVIg6AAIgBAAIAAgBIAAgVIAAgBIABAAIA6AAIABAAIAAABIAAAVIAAABIgBAAgAkHgdIAmAAIAAgHIgmAAgAA8gVQgOgLgPgFIgBgBIABAAIAFgHIABgBIAAAAQAQAFANAJIABABIgFAJIgBABIgBAAgAnIgbQgCgHgGgGIAAgBIABgBIAIgEIABABQAFAGADAIIABAAIgCACIgHACIgBABgAFDgiIgBAAIAAgBIAAgHIAAgBIABAAIAxAAIABAAIAAABIAAAHIAAABIgBAAg");
	this.shape.setTransform(0.85,2.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-49.6,-1.9,101,9.8), null);


(lib.title2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ao4BgIgCAAIAAgCIAAhXIAAgCIACAAIClAAIACAAIAAACIAABEQAAAKgEAFQgEACgFACIgPABQgFAAgBgCIgCgFQgBgIgDgGIANABQAFAAAAgGIAAguIh9AAIAABHIAAACIgCAAgAirA9QAAgMAKgIQAKgIANAAQAQAAAMALQAJAIAFAQQASgHAAgbQAAgQgLgJQgKgIgOAAQgaABgXATQgKAJgIALIgRgPQA5g5AhgfQgkAEggAAIgBgTQAmAAA1gDIALAQIhGA8IABABIAKgGQAMgFALABQAbAAAOANQANANABAWQAAAdgWAPQgRAMghAAQgsABAAgfgAiVA0QgDAEgBAFQAAAOAZAAIAMgCQgCgMgHgHQgFgFgIAAQgGAAgFADgAExBJQAsgLATgYQASgUACgiIhkAAIAAgTIB9AAQgDA+gbAdQgVAXguALgAkoBHQA5gHAAgwQAAgVgJgOQgIgMgMgCQgLA4gTAdQgQAagYAAQgOAAgIgLQgIgMgBgXQAAgjAagZQgFgRgEgdIAUgCIAGAkQASgLAWgBIAFgfIAWACIgFAeQAYAFAMATQALARAAAaQAAAkgWATQgQAOgfAFgAleAeQAAAdAMAAQAMAAALgPQgOgYgJgbQgMARAAAUgAlDgXQAHAZALAVQAJgWAIgkQgTABgQALgAgTBJQAegNAKgQQALgQABgcIhAAAIAAgTIBAAAIAAghIguAGIgKgSQA+gFAugPIALATQgRAFgYAFIAAAkIA1AAIAAATIg1AAQAAAlgQAWQgNASgdAMgAG8ASQAAgUAEghQADgZAFgWIAVACQgFAZgEAeQgCAZAAATQAAAmAEAdIgVACQgFgfAAgngAB9BIQAdgUAKgaQAJgXADgjIgtAAIAAgUIAtAAIAAgjIAXAAIAAAjIA+AAQAABJgEAjQgDATgJAFQgEADgJACIgbABIgIgXIAQABIANgBQAEAAACgDIACgKQAEgcAAg2IgoAAQgCAwgPAbQgNAZgbAUgAoNBSIgCgBIAAgCIAAgtIAAgBIACgBIBOAAIADABIAAABIAAAtIAAABIgDAAIgPAAIgDAAIAAgBIAAgFIgqAAIAAAFIAAACIgDABgAn7A8IAqAAIAAgOIgqAAgAHyBHQgLgIAAgRQABgLACgKIAVABQgDAJAAAHQAAAKAHAEQAGAEANAAQAVAAAXgCIAAAVQgSACgZAAQgZAAgMgKgAoagEIgCgBIAAgCIAAgnIAAgCIACgBIBpAAIACABIAAACIAAAnIAAACIgCABgAoHgTIBEAAIAAgPIhEAAgAHvg6QAagCAcAAIAcAAIAAAVIgdgBQgbAAgaADgAo/g6IgCAAIAAgDIAAgOIAAgCIACgBIBOABIAAgBQAAgLgCgGIAWABQABAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIgBAEIgBAKIAAABIBRgBIACABIAAACIAAAOIgBADIgBAAgAEug8IAAgTIBkAAIAAATg");
	this.shape.setTransform(9.5,6.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title2, new cjs.Rectangle(-48.3,-3.1,115.7,19.200000000000003), null);


(lib.logomc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgRAMgXALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape.setTransform(131.014,-33.4097,0.2765,0.2756);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgQAMgYALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_1.setTransform(124.9994,-33.4097,0.2765,0.2756);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag/CeQgXgFgQgHIAAhIQAUAOAXAIQAWAIATAAQAZAAALgHQALgHAAgQQAAgPgMgKQgNgLgggNQgogRgRgUQgRgVAAghQAAgqAhgbQAhgbA0AAQAPAAAWAEQAQADASAGIAABGQgQgKgSgHQgUgHgSAAQgVAAgLAIQgLAIAAAPQAAAPAJAJQALAJAgAOQAtARARAVQARAWAAAfQAAArghAbQgiAbg4AAQgRAAgagFg");
	this.shape_2.setTransform(116.5858,-31.5908,0.2765,0.2756);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA/CbIg+jfIAAAAIhADfIhNAAIhak1IBMAAIA6DtIABAAIBFjtIBEAAIA9DuIACAAIA4juIBGAAIhbE1g");
	this.shape_3.setTransform(106.8449,-31.5908,0.2765,0.2756);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhzB4QgrgrAAhJQAAhMAsgtQArgsBMAAQBJAAApArQAoArAABKQAABLgrArQgrAthLAAQhHAAgqgqgAg8hJQgWAaAAAxQAAAwAWAaQAWAZAoAAQAnAAAWgZQAUgaABgyQAAgxgWgaQgWgZgmAAQgoAAgWAbg");
	this.shape_4.setTransform(95.6867,-31.577,0.2765,0.2756);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhzC+QgjgoAAhHQAAhMAmguQAnguBAAAQAcAAAXAKQAXAKAMASIACAAIAAizIBIAAIAAHIIhIAAIAAgpIgCAAQgQAXgZALQgaAMggAAQg7AAgigpgAg1gCQgVAcAAAzQAAAvAUAZQAVAZAiAAQAiAAAWgaQAWgaAAgqIAAghQAAghgVgVQgVgXggAAQgmAAgUAcg");
	this.shape_5.setTransform(85.7107,-33.5475,0.2765,0.2756);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCCeIAAisQAAgqgPgVQgOgVggABQgeAAgTAXQgVAXAAAjIAACuIhIAAIAAk1IBIAAIAAAqIACAAQARgZAZgLQAYgMAhAAQAxAAAbAgQAaAfAAA/IAAC9g");
	this.shape_6.setTransform(76.2808,-31.6804,0.2765,0.2756);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgkDdIAAk1IBIAAIAAE1gAgfiUQgNgLABgSQgBgSANgMQAOgNARAAQATAAAMANQANANABARQgBASgNAMQgMAMgTAAQgSAAgNgNg");
	this.shape_7.setTransform(69.485,-33.4097,0.2765,0.2756);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABaDYIhXlFIgCAAIhVFFIhaAAIh4mvIBRAAIBVFVIABAAIBelVIBPAAIBYFUIACAAIBRlUIBOAAIh1Gvg");
	this.shape_8.setTransform(59.4122,-33.2788,0.2765,0.2756);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_9.setTransform(40.5318,-28.0702,0.2765,0.2756);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_10.setTransform(30.0857,-28.0702,0.2765,0.2756);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_11.setTransform(40.5318,-38.4805,0.2765,0.2756);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_12.setTransform(30.0857,-38.4805,0.2765,0.2756);

	this.instance = new lib.Bitmap8();
	this.instance.setTransform(54,-8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AmyPUQjHhPiWiRQiYiRhSi/QhVjGAAjeQAAjbBWjFQBTi/CXiSQCYiRDIhQQDOhSDkAAQDkAADMBRQDGBPCWCRQCYCRBSC/QBVDGAADdQAADbhVDGQhUC/iXCSQiYCRjIBQQjNBSjkAAQjkAAjMhRgAmJmfQiZCiAAD9QAADzCgCoQCgCnDmAAQDrAACbikQCZikAAj6QAAjyifioQiginjmAAQjtAAiaCig");
	this.shape_13.setTransform(138.0777,92.5213,0.0473,0.0473,-90);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AmzPUQjGhPiXiRQiXiRhSi/QhVjGAAjeQAAjbBVjFQBTi/CZiSQCYiRDHhQQDOhSDkAAQDjAADNBRQDGBPCXCRQCXCRBSC/QBVDGAADdQAADbhVDGQhTC/iZCSQiYCRjHBQQjOBSjkAAQjjAAjNhRgAmJmfQiZCiAAD9QAADzCfCoQCgCnDnAAQDsAACaikQCZikAAj6QAAjyifioQiginjnAAQjtAAiZCig");
	this.shape_14.setTransform(138.0777,71.9734,0.0473,0.0473,-90);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AudU1MAAAgppII7AAMAAAAhkIUAAAIAAIFg");
	this.shape_15.setTransform(136.6258,124.3344,0.0473,0.0473,-90);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AmFPXQjQhNiaiPQiaiPhSjBQhUjFAAjmQAAjeBSjFQBRjACUiRQCUiRDFhOQDLhRDjAAQD/AADPBWQDPBVCOClQBhByA/CSQA+CSAYCnI2gJVQCpCnEdAAQCmAAB5grQCAguCtiBIFlESQiOCkkFBvQkRB1kWAAQj6AAjYhOgAjgouQhvA1hJBiQhFBegeB1QgiCDATCUIPYmXQg9iFhvhLQh1hQiUAAQiIAAhxA2g");
	this.shape_16.setTransform(138.0789,114.6186,0.0473,0.0473,-90);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ak0QCMgNNggDIKEAAIH9V1IH911IKFAAMgNNAgDg");
	this.shape_17.setTransform(138.0777,82.2444,0.0473,0.0473,-90);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AHWQTIAAyPQAAjCiWh8QiLh0i5AAQjWAAiECKQh3B+AACqIAASPIozAAMAAAggEIIzAAIAAEnQB3ieC9hZQCvhSC6AAQFxAADpDnQDnDkAAFkIAAT3g");
	this.shape_18.setTransform(137.9972,103.6918,0.0473,0.0473,-90);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#E1140A").s().p("Eh8/AprMAAAhTVMD5/AAAMAAABTVg");
	this.shape_19.setTransform(137.2079,97.7739,0.0475,0.0475,-90);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.instance},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logomc, new cjs.Rectangle(25.4,-43.2,124.5,179), null);


(lib.CTAmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAFA2IgBgBIAAgjIABgBIAeAAIABABIAAAhIgBABIgEAAIgBgBIAAgFIgUAAIAAAHIgBABgAAKApIAUAAIAAgSIgUAAgABFA1IgBAAIAAgdIgaAAIAAgBIAAgFIAAgBIAaAAIAAgRIgUAAIgCgBIAAgFIACgBIAUAAIAAgRIgXABIgBgBIAAgFIABgBIAeABQAGgKACgIIACgGIAGACIACABIgCADIgCACIgHAQIAUgBIABABIAAAFIgBABIgbgBIAAARIAWAAIABABIAAAFIgBABIgWAAIAAARIAdAAIABABIAAAFIgBABIgdAAIAAAdIgBAAgAikAqQAYAAALgGQAGgDADgFQADgEgBgGQAAgIgFgEQgEgFgJAAQgOABgLAMQgEAEgCAGIgJgBQAAgSAEgjIAIABIgDAkIgCAGIAEgEQAFgIAJgCQAHgDAIgBQANABAIAFQAGAHAAAKQAAAKgDAHQgEAEgHAEQgFAEgNABIgVADgADRAHQgEgEAAgDQAAgEADgDQAUgTATgXIAHAFQgSAWgUASQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAABQAAABADACQAVASAVAXIgHAGQgTgXgYgUgACDAsQgGgGAAgMIABhKIAJAAIgCBJQAAAKAFADQADAEAJAAQAOAAAHgIQAIgIADgPIAIAEQgIAjgfAAQgPAAgFgGgAj4AsQgLgFAAgNQAAgMAMgGQAIgFAMAAQAPABAIAFQgMgMgJgSIgiACIAAgIQARAAAPgBIgIgWIAJgBIAHAWQANgCANgDIAAAHIgXAEQAIAUAPAOIgFAIQgOgJgPAAQgLABgHAFQgFAEAAAGQAAAQAfAAIAQgBIAAAHIgQACQgUgBgJgFgAhaAKQAAgUAHgkIAJABQgIAiAAAVQAAAWADAQIgIAAQgDgRAAgVgAg8ApQgFgFAAgJQgBgHACgFIAIAAIgBALQAAAGADADQAFABAJAAIAXgBIAAAJIgWABQgQAAgFgEgAAGAHIgBgBIAAgFIABgBIAcAAIABABIAAAFIgBABgAAGgIIgBgBIAAgFIABgBIAcAAIABABIAAAFIgBABgAAAgZIgBgBIAAgEIABgCIAnAAIABACIAAAEIgBABgAg+ghIAfgBIAOAAIAAAIIgPAAQgPAAgPABgAihgsIAEgHQAWAFAPAGIgFAHQgPgGgVgFgAA7giQgDgHgFgIIAAgBIABgBIADgBIABgBIABABQAFAHADAIIAAABIgCAAIgDACIgBAAgAAFgpIgBgBIAAgFIABAAIAfAAIABAAIAAAFIgBABg");
	this.shape.setTransform(-5.15,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgPgeIAeAeIgeAf");
	this.shape_1.setTransform(30.35,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0075D4").s().p("AmPB/QgeAAAAgdIAAjDQAAgdAeAAIMfAAQAeAAAAAdIAADDQAAAdgeAAg");
	this.shape_2.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTAmc, new cjs.Rectangle(-42.9,-12.7,85.9,25.5), null);


(lib.commc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap79();
	this.instance.setTransform(-89,-59,0.7843,0.7843);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.commc, new cjs.Rectangle(-89,-59,138.1,91), null);


(lib.bgmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.bg();
	this.instance.setTransform(-150,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bgmc, new cjs.Rectangle(-150,-125,300,250), null);


// stage content:
(lib._300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(270));

	// CTA
	this.instance = new lib.CTAmc();
	this.instance.setTransform(343.5,222.75);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(106).to({_off:false},0).to({x:242.5},12,cjs.Ease.get(1)).wait(152));

	// txt
	this.instance_1 = new lib.txt5();
	this.instance_1.setTransform(190,178.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(94).to({_off:false},0).to({x:205,alpha:1},12,cjs.Ease.get(1)).wait(164));

	// txt
	this.instance_2 = new lib.txt4();
	this.instance_2.setTransform(183.9,161.65);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(90).to({_off:false},0).to({x:198.9,alpha:1},12,cjs.Ease.get(1)).wait(168));

	// txt
	this.instance_3 = new lib.txt3();
	this.instance_3.setTransform(181.05,149.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(86).to({_off:false},0).to({x:196.05,alpha:1},12,cjs.Ease.get(1)).wait(172));

	// txt
	this.instance_4 = new lib.txt2();
	this.instance_4.setTransform(177.3,136.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(82).to({_off:false},0).to({x:192.3,alpha:1},12,cjs.Ease.get(1)).wait(176));

	// txt
	this.instance_5 = new lib.txt1();
	this.instance_5.setTransform(176.9,124.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(78).to({_off:false},0).to({x:191.9,alpha:1},12,cjs.Ease.get(1)).wait(180));

	// title
	this.instance_6 = new lib.title2();
	this.instance_6.setTransform(44.9,82.35);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(66).to({_off:false},0).to({x:59.9,alpha:1},12,cjs.Ease.get(1)).wait(192));

	// title
	this.instance_7 = new lib.txtTitle();
	this.instance_7.setTransform(70.25,58.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(62).to({_off:false},0).to({x:85.25,alpha:1},12,cjs.Ease.get(1)).wait(196));

	// logo
	this.instance_8 = new lib.logomc();
	this.instance_8.setTransform(150.05,58.75);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(4).to({_off:false},0).to({alpha:1},24,cjs.Ease.get(1)).wait(242));

	// com
	this.instance_9 = new lib.commc();
	this.instance_9.setTransform(91.5,310.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(33).to({_off:false},0).to({y:170.5},19,cjs.Ease.get(1)).wait(218));

	// bg
	this.instance_10 = new lib.bgmc();
	this.instance_10.setTransform(150,125);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(33).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(1)).wait(218));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#05132A").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(270));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(146.6,124.5,239.9,218);
// library properties:
lib.properties = {
	id: '542CFFE83C13439EB4A04353E49F32EB',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.png?1632276435631", id:"bg"},
		{src:"images/Bitmap79.png?1632276435631", id:"Bitmap79"},
		{src:"images/Bitmap8.png?1632276435631", id:"Bitmap8"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['542CFFE83C13439EB4A04353E49F32EB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;