(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap14 = function() {
	this.initialize(img.Bitmap14);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,153,103);


(lib.Bitmap16 = function() {
	this.initialize(img.Bitmap16);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtTitle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AggBFQgIgGAAgOQAAgMAJgJQAKgKAXgMQgBgIgBgCQgCgDgEAAQgKAAgKAJQgJAGgMAOIgNgLQAYgYANgZIgPABIgSgBIAAgQIAVABIATAAQAEgKADgNIASACIgHAUQAZgBAVgCIAAAQIg1ADQgHAMgIAIIgDAFIAAABIAEgEQAIgFAIAAQAIAAAGAGQAGAFABAJIAkgPIAHAQQgYAHgSAIIAAAjIgRAAIAAgbQgPAJgGAGQgEAEAAAHQgBAHAIACQAGADARAAQAVAAAagCIABARQgYACgagBQgbABgKgJg");
	this.shape.setTransform(50.05,27.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgqBSIgOAAIgCAAIgBgCIABgfIAAhnQAAgSgCgJIATABQABAAABAAQAAAAABABQAAAAAAAAQABABAAAAIgBAEQgCADAAAQIAABoIAAAfIAAACIgCAAgABRBNIgZgBIg6AAIgZABIgBgBIAAgCIAAgNIAAgCIABAAIAZAAIAVAAIAAgjIgKAAIgWAAIgCAAIAAgCIAAgOIAAgCIACAAIAWAAIAKAAIAAgeIgUAAQgEALgFAKQgCADgCAAIgDgBQgGgEgHgDQAFgGADgKIgHADIgCABQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAQgCgMgEgMIgBgBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAHgDIACgBIACACIAHAWQAFgPADgOIABgNIARAFQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAACIgDAGIgDAOIAQAAIAAgNQABgQgCgLIAUABQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAEQgBADgBAQIAAAOIAQAAIAWgBIACABIAAACIAAANIAAACIgCAAIgWAAIgQAAIAAAeIAKAAIAXAAIABAAIABACIAAAOIgBACIgBAAIgXAAIgKAAIAAAjIASAAIAZAAIACAAIAAACIAAANIAAADIgCAAgAhHAAIgJgCQgBgBAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgCQAFgPAAgWQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIADAAIAIACQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABIAAAAQgCAZgFAOIgBABIgBgBg");
	this.shape_1.setTransform(34.15,27.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhFBQQgGgHgGgEQAKgPADgUQADgQAAgYIAAgZIAAgBIACgBIAYABIANAAIgIgQIgFAAIgYAAIgCAAIAAgCIAAgMIAAgCIACAAIAYAAIAkAAIAAgBQAAgKgCgGIASABQAAAAABAAQABAAAAABQAAAAABAAQAAAAAAABIgBADQgBACAAAIIAAABIAkAAIAYAAIACAAIAAACIAAAMIAAACIgCAAIgYAAIgEAAIgBADIgIANIATAAIAYgBQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAMQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgYAAIhnAAIAAALQAAAQgCARQANgMAIgTIACgJIAQAEQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIgBACIgDAFIgBADIAUAAIAAgCQAAgHgBgIIASABQABAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIgBAEIgBAIIAAACIATAAIAYAAIACAAIAAACIAAAMIAAACIgCAAIgYgBIgTAAIAAAOIANAAIAXAAIACAAIAAACIAAAMIAAABIgCABIgXgBIgNAAIAAAQIAeAAIAYgBIACABIAAABIAAANIAAABIgCABIgYgBIhNAAIgZABIgBgBIgBgBIAAgNIABgBIABgBIAZABIAdAAIAAgQIgJAAIgXABIgBgBIgBgBIAAgMIABgCIABAAIAXAAIAJAAIAAgOIgcAAIgNASQAAABgBABQAAAAgBABQAAAAAAABQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQgEgFgGgEIgBAMQgDAUgKATQgBABAAAAQgBABAAAAQAAABgBAAQAAAAAAAAIgDgCgAgHggIAaAAIAHgQIgoAAg");
	this.shape_2.setTransform(15.925,27.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABOBNIgXAAIhqAAIgXAAIgCAAIAAgBIAAgQIAAgBIACgBIAXABIAtAAIAAghIgUAAIgZAAIgCAAIAAgCIAAgOQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAZAAIAUAAIAAgdIgmAAQgHANgJALIgDADIgEgDQgFgEgHgDQATgWAKgfIADgLIARAEQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIgCADIgEAHIgEAMIAeAAIAAgKQAAgRgCgKIAUABQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAEQgCADAAARIAAAKIAfAAIAZgBIACABIAAABIAAAPIAAACIgCAAIgZAAIgfAAIAAAdIAXAAIAZAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAOIgBACIgBAAIgZAAIgXAAIAAAhIArAAIAXgBIACABIAAABIAAAQIAAABIgCAAg");
	this.shape_3.setTransform(-1.975,27.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCA2QAbgFALgQQAKgNAAgUQAAgdgMgNQgJgLgOgBQgDA7gNAfQgGAOgIAFQgGAEgJAAQgOAAgJgOQgHgOAAgWQAAgkAUgVQAJgKAOgGQAMgEANAAQA9AAAABFQAAA3g6ANgAghgjQgOARAAAcQAAAQAFAIQADAHAFAAQAEAAADgDQADgDACgHQAGgQAFgXQAEgWAAgUQgOACgMAQg");
	this.shape_4.setTransform(-18.275,28.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAnA2IhjAOIgEgUIANAAQATg3ARhCIATAFQgOA4gWA6QAkgDAdgFQgKgVgMgWIARgGQAUAgARAsIgUAJg");
	this.shape_5.setTransform(-32.9,27.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgyAKIAAgTIBlAAIAAATg");
	this.shape_6.setTransform(-45.975,27.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgxA8QAagKAKgPQAIgNABgYIg3AAIAAgRIA3AAIAAgbIgoAFIgIgQQA1gEAngNIAKAQQgPAEgUAFIAAAeIAtAAIAAARIgtAAQgBAfgNATQgLAQgaALg");
	this.shape_7.setTransform(-58.825,27.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txtTitle, new cjs.Rectangle(-67.7,13.1,127,27.9), null);


(lib.txt7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNANQgFgGAAgHQAAgHAGgGQAGgFAGAAQAIAAAGAGQAFAGAAAGQAAAIgGAGQgGAFgHAAQgHAAgGgGgAgHgGQgDADAAADQAAAFAEADQADADADAAQAFAAADgEQADgDAAgEQAAgEgEgDQgDgDgEAAQgEAAgDAEg");
	this.shape.setTransform(48.375,4.725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAAHIgIAQIgJgGIAMgPIgSgCIAEgKIAQAHIgCgTIALAAIgCATIAQgHIAEAKIgSACIAMAPIgJAGg");
	this.shape_1.setTransform(42.975,-1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpAKQAAgNADgUIAFgdIANABQgDAQgCASQgCARAAAKQAAAYADARIgOACQgDgUAAgXgAgHAqQgHgFAAgKQAAgHACgHIAMABIgBAKQAAAHADACQAEACAIAAIAcgBIAAANIgbABQgPAAgHgGgAgJglQAPgCASAAIARABIAAANIgSgBIggABg");
	this.shape_2.setTransform(35.125,0.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwA7QgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgQIAAgnIAAgPIAAgCIABAAIAOABIAQAAIAOgBIABABIAAABIAAAQIAAAXIAAASQAAAIgDACIgFACIgJABIgEAAIgBgEIgDgHIAIAAQAFAAAAgEIAAgJIgWAAIAAAIIAAAQQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAglAXIAWAAIAAgIIgWAAgAglAFIAWAAIAAgIIgWAAgAALA3QgFgCAAgHIAAghIAAgNIANABQAAAAABABQAAAAAAAAQAAAAABAAQAAABAAAAIgBACIgBAHIAAAGQALgEAJgFQAFgDACgDIAIAJIACACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAIgFACIgdANIAAAJQAAAEADABQACABAIAAQAKAAADgDQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIABgIIAJAEIADABIAAABIAAACIgCAKQgBADgDACQgGAEgQAAQgPAAgFgDgAALgFQgFgCAAgHIAAgfIgBgMIANABQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIgBACIgBAHIAAAHIATgJIAHgFIAIAIIACADQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgGADQgLAFgRAGIAAAHQAAABAAABQAAABABAAQAAAAAAABQABAAAAAAIAKABQALAAACgCIACgEIAAgIQAEADAFABIADABIAAACIAAACIgCAJIgEAFQgEADgRAAQgQAAgEgCgAgGgSIgDgGIgnAFIgFABIgCAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIgCgLIALAAIAHgSIADgJIAMACQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIgBACIgDAEIgHAQIAUgCIgFgIIAAgBIABgCIAGgDIABAAIACABQAGAIAGAPIABABIgBACIgHAEIgBAAIgBgBg");
	this.shape_3.setTransform(23.225,0.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AALA3IgBgEQgBgGgDgDIAQAAQAEAAABgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAgBAAgBIAAhOIhEAAIgQAAIgCAAIAAgBIAAgLIAAgBIACgBIAQABIBPAAIAQgBIABABIABABIAAALIgBABIgBAAIgEAAIgJAAIAAA4IAAAZQAAAJgFADQgEADgTAAIgEAAgAgeAgIgKAAIgBAAIgBgCIABgYIAAgNIgBgRIABgCIABAAIAOAAIAVAAIANAAIABAAIABACIgBAOIAAAOIABAXIgBABIgBAAIgJAAIgBAAIgBgBIAAgFIgZAAIAAAIIgBACIgBAAgAgcAJIAZAAIAAgWIgZAAg");
	this.shape_4.setTransform(10.325,0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUA6IgCgNIAMACQAFAAACgBIADgFQADgLAAgdQAAgIgCgDQgBgDgDAAIgLABQgLAogOAfIgNgEQAPggAJgjIgXADIAAgMIAagCIAFgaIANACIgFAXIALAAQAIAAAEAGQAFAGAAAMQAAAhgEAMQgCAIgFADQgEADgHAAIgOgBgAAKgdIALgGQAPAUALAZIgNAHQgJgbgPgTgAAUg0IAIgCQAFAJAFAMIgJADQgEgMgFgKgAAjg3IAIgDQAGAKAEALIgJADQgEgNgFgIg");
	this.shape_5.setTransform(-1.425,-0.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgoAlQAjgIARgYQANgSAEgeIANAHQgFAkgTAUQgSAVghAJgAgpglIAIgMQASAJAOAMIgJANQgPgOgQgIg");
	this.shape_6.setTransform(-12.25,0.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgcApIAAgMIAsAAIAAgZIgqAAIAAgLIAqAAIAAgVIgsAAIAAgMIA5AAIAABRg");
	this.shape_7.setTransform(-21.375,1.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgnAmQAhgFARgTQAIgIAGgOQAGgNADgPIANAIQgEAQgHANQgGAOgIAIQgVAVgiAHgAgugMIAHgKQAWAHAKAGIgHALQgLgHgVgHgAgignIAGgLQAUAHALAHIgGANQgMgKgTgGg");
	this.shape_8.setTransform(-30.725,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgkAHIAAgNIBJAAIAAANg");
	this.shape_9.setTransform(-40.275,0.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjApQATgHAIgNQADgGABgHIABgTIgnAAIAAgLIBVAAIAAALIghAAQABARgDAJQgBAIgFAGQgDAIgHAFQgHAFgKAFgAgjgnIAAgMIBHAAIAAAMg");
	this.shape_10.setTransform(-49.55,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt7, new cjs.Rectangle(-56.5,-10.6,113.1,21.299999999999997), null);


(lib.txt6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoAlQAjgIARgYQANgSAEgeIANAHQgFAkgTAUQgSAVgiAJgAgpglIAIgMQASAJAOAMIgJANQgOgOgRgIg");
	this.shape.setTransform(32.65,0.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWA0QgGgEABgMIAAgqIgWAFIgDgLIAZgGIAAgdIAOAAIAAAaIApgKQgCgKgGgKIAIgCQAFAJAFANIgEABIAGAHQgGARgGALQgHAKgJAKIgLgHQASgTAEgRIgkAJIAAAsIABAGQACACAEABIALABQASAAAOgCIAAAOIgiABQgTAAgGgGgAAkg3IAIgCQAFAKAEALIgIADQgFgNgEgJg");
	this.shape_1.setTransform(22.35,-0.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkAvIAAhjIAOAAIAABYQARgHAMgNQAMgNAGgQIAMAKQgMAXgRAOQgNALgWAIg");
	this.shape_2.setTransform(12.15,0.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpAxQAegKALgTQAMgRABgeIg7AAIAAgMIBAAAIgBgFQAAgHAFgEQAEgEAGAAQAHAAAEAFQAEAEAAAGQAAAGgFAFQgEAEgGAAIgEgBQgBApgRAVQgNARgeALgAAagyQgCACAAAEQAAAEACACQADACADAAQAEAAACgDQACgCAAgDQAAgEgCgDQgDgCgDAAQgEAAgCADg");
	this.shape_3.setTransform(2.225,-0.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSgJIALgJQAPAMALAQIgMAJQgJgQgQgMg");
	this.shape_4.setTransform(-9.275,4.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaA8IgBgBIgBgBIABgPIAAgoQgKAKgIAHIgDABIgDgCIgGgIQAYgOAMgZIgQAAIgRAAIgBAAIAAgBIAAgKIAAgBIABgBIARABIAVAAIACgGIADgNIALACQABABABAAQAAAAAAAAQABABAAAAQAAAAAAAAIgCADIgBAGIgCAGIArAAIAQgBQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAKQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgQAAIgwAAIgFALIAhAAIATAAIABAAIABABIgBAQIAAAYIABAUQAAAIgFADQgCACgFABIgMABIgDgBIgBgDIgFgKIANABQABAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAIABgEIAAgIIgpAAIAAAKIAAAPIAAABIgCABgAgOAWIApAAIAAgJIgpAAgAgOADIApAAIAAgIIgpAAg");
	this.shape_5.setTransform(-18.4,0.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAtA5QgWgLgNgRIAAgBIABgBIAIgEIABgBIABABQAPAQAUAHIgGAJIgDADgAgyA3QgDgFgEgDQATgHALgLIAFgIIALAGIACACIgCADIgEADQgKAMgTAKIgDABIgDgDgAA4ASIgQAAIhQAAIgQAAQAAgBAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgKQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAQAAIANAAIAAgYIgFAAIgRAAIgCAAIAAgBIAAgKQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIARAAIAFAAIAAgGIgBgTIAOABQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIgBADIgBANIAAAGIAbAAIAAgGIgBgTIAOABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIgBADIAAANIAAAGIAGAAIARAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAAABIgBAAIgRAAIgGAAIAAAYIANAAIAQAAIACAAIAAABIAAAKIAAACIgCAAgAgOAFIAbAAIAAgYIgbAAg");
	this.shape_6.setTransform(-31.3,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt6, new cjs.Rectangle(-39.8,-10.6,79.6,21.299999999999997), null);


(lib.txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHAHQgEgDAAgEQAAgEAFgDQADgEADAAQAFAAADAEQAEADAAAEQgBAFgDAEQgEADgEAAQgEAAgDgFgAgEgEQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAAAQAAADABACQABAAABABQAAAAABAAQAAAAABAAQAAAAAAAAQADAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgCgCgCQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAAAgBAAQgCAAgCACg");
	this.shape.setTransform(-96.75,239.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPAaIABAAQAOAAAIgDQAHgEAAgIQAAgFgDgCQgDgDgFAAQgIAAgHAIQgDAEgBADIgIgBIADgjIAIABIgCAVIgCAFIADgEQAIgIAKABQAJgBAFAFQAFAEAAAJQAAAGgDAEQgDAEgFACQgIAFgRAAgAAAgYIgNgDIADgHIAOAEIAMAEIgFAHIgLgFg");
	this.shape_1.setTransform(-101.175,236.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAbQASAAAGgDQAGgEgBgGQABgKgLAAQgFAAgEADQgFADgFAGIgIgEQAFgMAEgOIgMAAIAAgHIAOgBIACgLIAIAAIgCALIAYgCIAAAIIgZABQgEAMgFAJQAJgIAKAAQAJAAAGAFQADAEAAAHQABALgLAFQgHAEgUAAg");
	this.shape_2.setTransform(-107.2,236.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWAQQABgGADgHIAIACQgDAFgBAFQAAAEAEACQAEACAHAAIAVgBIAAAJIgVAAQgXAAAAgPgAgFgOIALgIIgJABIgOAAIAAgIIAPAAIAVgBIABAIIgIAEIgMAJg");
	this.shape_3.setTransform(-112.85,236.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNAVQAAgFAFgDQAEgDAEAAIAIABIgBgWIgMAAIgIAAIAAgHIAKAAIAKAAIAAgOIAIAAIAAAOIANgCIAAAIIgNAAIABAYQAHAEAHAHIgFAHQgFgHgEgCIAAAAQAAAGgEADQgEADgHAAQgOAAAAgMgAgEASQAAAAgBABQAAAAAAAAQgBABAAAAQAAABAAAAQAAAFAHAAQAHAAAAgGIAAgCQgDgBgFAAQgCAAgCABgAgdAIQAAgQAFgYIAIABQgFAXAAAQQAAAKACAOIgIABQgCgOAAgLg");
	this.shape_4.setTransform(-118.825,236.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAlIgBgBIAAAAIABgLIAAgVIgIABIgCAAIgBABIgCgBIgBgGIAGAAIAFgHIgLgLIAAAAIAAgBIAEgFIAAgBIABABIACACIAFgIIABgFIAHADIABABIAAACIgCABIgHALIADAEIAGgIIACgGIAHADIABABIgBACIgDADIgMASIAJgBIgCgFIAAgBIABAAIADgCIABAAIAAABQAEAFACAJIAAAAIgBABIgEABIgBAAIAAAAIgBgEIgFABIAAAVIAAALIAAAAIgBABgAAAAjIgBgBIAAAAIAAgdIAAAAIAAgBIAAgOIAAgTIAAAAIABAAIAIAAIARAAIAJAAIABAAIAAAAIAAARIAAAOIAAAgIAAAAIgBAAIgGAAIgBAAIAAgEIgVAAIAAAEIAAAAIgBABgAAUAXIAHAAIAAgTIgHAAgAAGAXIAHAAIAAgTIgHAAgAAUgDIAHAAIAAgTIgHAAgAAGgDIAHAAIAAgTIgHAAgAgdAfIgFgDQADgHABgIIAAgDIAAgCIAFACQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIgBABIAAADIgDAOIgBACgAgIAaIgBgBIgCgOIAAgBIABAAIADgCIABAAIAAABQADAIABAGIAAABIgBABIgEABg");
	this.shape_5.setTransform(-126.75,236.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAKAlIAAgBIAAAAIAAgMIAAgGIgFAAIgJAAIgBAAIAAAAIAAgGIAAgBIABAAIAJAAIAFAAIAAgJIgDAAIgJAAIAAAAIAAgBIAAgFIAAgBIAAAAIAJAAIADAAIAAgIIgEAAIgJAAIgBgBIAAgFIABgBIAJAAIAJAAIAFgLIABgFIAIADIAAABIAAABIgCADIgEAIIABAAIAKAAIABAAIAAABIAAAFIAAABIgBAAIgKAAIgGAAIAAAIIAEAAIAJAAIABAAIAAABIAAAFIAAABIgBAAIgJAAIgEAAIAAAJIAHAAIAKAAIABAAIAAABIAAAGIAAAAIgBAAIgKAAIgHAAIAAAGIAAAMIAAAAIgBABgAgZAlIgGAAIgBgBIAAAAIAAgMIAAgGIAAgHIAAgBIABAAIAHAAIAIAAIAHAAIABAAIAAABIAAAGIAAAGIAAALIAAABIgBAAIgGAAIAAAAIgBgBIAAgCIgIAAIAAAEIgBABgAgYAaIAIAAIAAgJIgIAAgAgRAGIgGAAIgHAAIgBAAIAAgBIAAgFIAAAAIABAAIAHAAIAGAAIAHAAIABAAIAAAAIAAAFIAAABIgBAAgAgKgEIgHAAIgGAAIgHAAIgBAAIAAAAIAAgGIAAAAIABgBIAHABIAGAAIAHgBIABABIAAAAIAAAGIAAAAgAgHgOIgJAAIgKAAIgJAAIAAAAIAAgBIAAgGIAAgBIAJAAIAKAAIAJAAIAAAAIABABIAAAGIgBABgAAEgWIgFgKIAAAAIABgBIAEgCIABAAIAAAAIAGAKIAAABIgBABIgFACIgBAAIAAgBgAgJgaIgHAAIgIAAIgHAAIgBAAIAAgBIAAgFIAAgBIABAAIAHAAIAIAAIAHAAIABAAIAAABIAAAFIAAABIgBAAg");
	this.shape_6.setTransform(-134.525,236.425);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIAHQgCgDAAgEQAAgEADgDQADgEAEAAQAGAAADAEQACADAAAEQABAFgEAEQgDADgFAAQgEAAgEgFgAgEgEQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAAAQAAADACACQABAAABABQAAAAABAAQAAAAABAAQAAAAAAAAQADAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAgCgDgCQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAAAgBAAQgCAAgCACg");
	this.shape_7.setTransform(-142.25,239.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUAbQAOgCAGgFQAEgEAAgEQgEAEgEAAQgHAAgDgEQgEgDAAgGQAAgGAFgDQAEgDAFAAQAEAAACABIAAgIIgeABIAAgIIAeAAIAAgKIAJAAIgBAKIATAAIAAAHIgTAAIAAAJIAAAHQACADAAAGQAAALgIAHQgFAEgOAEgAgJgCQgCACAAACQAAAEACACQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQADAAACgCQABgDAAgDQAAgGgGAAQgBAAAAABQgBAAgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_8.setTransform(-147.15,236.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAFQAAgIAFgIQAFgGAFgEIAEgCIAAgBIgEACIgdADIgBgIIAzgDIABAHQgJABgEACQgQAJAAAPQAAAQAYADIgDAIQgdgDAAgXgAAKgMIAFgBIAFANIgFABQgCgHgDgGgAATgOIAGgCQADAGACAHIgFACIgGgNg");
	this.shape_9.setTransform(-153.6,236.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaAjIAAAAIAAgBIAAgEIgPAAIAAAEIAAABIgBAAIgGAAIgBgBIAAgPIAAgIIAAgKIAAAAIABAAIAJAAIALAAIAJAAIABAAIAAAAIAAAJIAAAJIAAAPIAAABIgBAAgAALAXIAPAAIAAgPIgPAAgAgZAjIgHAAIgBAAIAAgBIAAgPIAAgIIAAgKIAAAAIABAAIAJAAIALAAIAIAAIABAAIAAAAIAAAJIAAAJIAAAPIAAABIgBAAIgGAAIgBgBIAAgEIgOAAIAAAEIAAABgAgZAXIAOAAIAAgPIgOAAgAAWgGIgLAAIgVAAIgKAAIgBAAIAAgBIAAgHIAAgLIAAgIIAAgBIABAAIAKAAIAVAAIALAAIABAAIAAABIAAAIIAAALIAAAHIAAABgAgNgOIAcAAIAAgMIgcAAg");
	this.shape_10.setTransform(-161.05,236.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgWAkIgDgHIAJgBIADAAIAAgGQgIAEgJACIgBAAIgDgCQgBgDgCgCQAQgCALgGIgOAAIgKAAIgBAAIAAgBIAAgFIAAgBIABAAIAKAAIAXAAIAAgEIgCAAIgBAAIAAAAIgBAAIgCgEIAEAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAIAAgCIgHAAIAAAIIgBABIgGAAIgBgBIAAgIIgHAAIAAADIABAEIgBAAIAAAAIgFAAIgBAAIAAAAIAAgEIAAgEIAAgFIABgBIAJABIADAAIAAgEIgGAAIgLAAIAAAAIgBAAIAAgFIABgBIAAAAIAGAAIAFAAIAGAAIAAgDIgIAAIgCACIgBABIgCgBIgEgBQAEgEACgFIABgDIAGABIABABIAAABIgCACIAAAAIAFAAIAAgGIAHABIABAAIAAACIAAADIADAAIAJAAIABAAIAAABIAAAFIAAAAIgBAAIgJAAIgDAAIAAADIAGAAIAJAAIAAAAIABABIAAAFIgBAAIAAAAIgJAAIgGAAIAAAEIADAAIAJgBIABABIAAAEIAAAFIgBADIACAAIACABIgBABIAAADIATAAIAKAAIAAAAIABABIAAAFIgBABIAAAAIgKAAIgBAAIAEAEIABABIgBABIgDACIgEACQAHAEAJACIgDAEIgCADIgBAAQgWgHgJgQIAAAAIgGAFIAAAJIAOgDIgBAFIAAABIgCABIgWAFIgDABIgBAAIgBgBgAAPAUIAFgEIADgDIgPAAQADAEAEADgAARADIgBgCIgBgFIAGABIADgBIABgBIAAgUIgBgKIAIAAIABABIAAABIgBAIIAAAPIAAAHQAAADgDACQgBABgJAAIgCAAgAAKgHIgBAAIAAgBIAAgHIAAgIIAAgJIAHABIACAAIgBACIAAAGIAAAIIAAAHIAAABIgBAAgAgXgVIgFAAIABgBIACgCIAIAAIAAADgAgcgVg");
	this.shape_11.setTransform(-169.05,236.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAAYQALgCAFgHQAEgGAAgJQAAgMgFgGQgEgFgGAAQgBAZgGAOQgCAGgEADQgDABgEAAQgGAAgEgGQgDgGAAgKQAAgPAJgKQAEgEAGgDQAGgCAEAAQAcAAAAAfQAAAYgaAGgAgPgPQgFAIAAALQAAAIACADQAAABABABQAAAAABABQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAIACgEIAEgRQADgKAAgJQgHABgGAHg");
	this.shape_12.setTransform(-176.35,236.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgVAlIgHAAIgBAAIAAgBIAAgLIAAgZIAAgKIABgBIAIAAIAKAAIAJAAIAAABIAAAKIAAARIAAALQABAFgCABQgCACgHAAIgCAAIgBgCIgCgGIAFABIACgBIABgBIAAgHIgNAAIAAAGIAAAKIAAABgAgVAOIANAAIAAgHIgNAAgAgVABIANAAIAAgFIgNAAgAAOAjIgBgBIgCgGIAHAAIADgBIABgCIAAgaIAAgLIAIABQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIgBABIAAAIIAAAOIAAAOQAAAFgDACIgEABIgIABIgBgBgAAHAUIgBgBIAAAAIAAgJIAAgJIgBgKIAJAAIAAABIAAACIAAAHIAAAJIAAAJIAAAAIgBABgAAjgRIgLAAIgvAAIgKAAIgCAAIAAgBIAAgGIAAAAIACgBIAKABIAJAAIgFgIIAAgBIABgBIAGgCIAAAAIABABIAFAIIAAAAIgBABIgFACIARAAIAEgIIACgEIAIACIACABIgBACIgDACIgDAFIAKAAIALgBIAAABIAAAAIAAAGIAAABg");
	this.shape_13.setTransform(-183.7,236.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAFAHQgJAPgSAJIgGgHQARgIAKgOQAHgKAEgPIggAAIAAgHIAoAAIACADQgDAQgHALQAKAKAJAQIgJAFQgGgNgJgLg");
	this.shape_14.setTransform(-190.8,236.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVAFIAAgIIAsAAIAAAIg");
	this.shape_15.setTransform(-196.5,236.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgOAaQAKgCAEgDQAFgDADgGQACgGAAgJIAAgdIAJAAIAAAfQAAAQgIAIQgHAHgOADgAgSAHIAAgnIAJAAIAAAng");
	this.shape_16.setTransform(-201.975,236.55);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOAaQAKgCAEgDQAFgDADgGQACgGAAgJIAAgdIAJAAIAAAfQAAAQgIAIQgHAHgOADgAgSAHIAAgnIAJAAIAAAng");
	this.shape_17.setTransform(-207.675,236.55);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAAEIgFAKIgFgEIAHgJIgKgBIACgGIAKAEIgBgLIAGAAIgCALIALgEIACAGIgLABIAHAJIgFAEg");
	this.shape_18.setTransform(-212.25,235.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt5, new cjs.Rectangle(-216,228.8,125.2,14.699999999999989), null);


(lib.txt4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSgJIALgJQAPAMALAQIgMAJQgJgQgQgMg");
	this.shape.setTransform(-133.975,186.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgpAlQAkgIARgYQANgSAEgeIAOAHQgGAkgSAUQgTAWgiAIgAgqgmIAJgLQASAKAPALIgJANQgQgNgRgKg");
	this.shape_1.setTransform(-141.45,182.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgcApIAAgMIAsAAIAAgZIgqAAIAAgLIAqAAIAAgVIgsAAIAAgMIA5AAIAABRg");
	this.shape_2.setTransform(-150.575,183.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnAmQAhgFARgTQAIgIAGgNQAGgNADgPIANAHQgEARgHANQgGANgIAIQgVAVgiAHgAgugMIAHgKQAWAHAKAGIgHALQgLgHgVgHgAgigoIAGgKQAUAGALAJIgGAMQgMgJgTgIg");
	this.shape_3.setTransform(-159.925,182.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgkAHIAAgNIBJAAIAAANg");
	this.shape_4.setTransform(-169.475,182.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkAuIAAhiIAPAAIAABXQAQgGAMgNQALgNAHgQIAMALQgMAVgRAPQgNALgWAIg");
	this.shape_5.setTransform(-178.05,182.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJA8IAAhMIgoAAIAAgMIAoAAIAAgUIAOAAIAAAUIAoAAIAAAMIgoAAIAABMgAg0AtQAOgWAEgaIAOADQgEASgFAMQgEAKgGAMgAAPABIANgEQAJAdAKASIgNAHQgKgUgJgegAATg2IAJgCQAFAIAEANIgIAEQgEgNgGgKgAAkg4IAIgDQAGAKADALIgIADQgEgMgFgJg");
	this.shape_6.setTransform(-188.725,181.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgbAqQAbgHALgOQAKgNACgVIg8AAIAAgMIBLAAQgBAmgRATQgNAOgcAHgAgegoIAAgMIA9AAIAAAMg");
	this.shape_7.setTransform(-199.05,182.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AghAuIAAgMIA0AAIAAhDIg0AAIAAgMIBDAAIAABbg");
	this.shape_8.setTransform(-208.4,182.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt4, new cjs.Rectangle(-214.9,171,89.2,21.30000000000001), null);


(lib.txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSAyQgFgFAAgIQAAgKAIgGQAIgEAJAAIAKABIgBgfIAMAAQAAAVACAMQAOAGAKAKIgGAMQgKgKgIgEIAAADQAAAJgHAFQgHAFgLAAQgLAAgHgGgAgMAlQAAAIANAAQAMAAgBgLIAAAAIAAgEQgEgCgFAAQgOAAgBAJgAgyAfQAQgbAHgaIgPAAIgGAAIAAgLIAJAAIAOAAIAEgWIAOACIgEATIAQgCIAAAMIgTABQgJAegOAdgAAMgcIAHgKQATAGAMAJIgGALQgNgJgTgHg");
	this.shape.setTransform(-145.5,176.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAEAUQgQAYgeAPIgIgLQAagNAQgWQANgSAFgYIg0AAIAAgMIA7AAIAGAOIADgBQgGAWgJAOQAPARAPAaIgOAIQgKgUgNgTgAASg2IAIgCQAFAJAFANIgJACQgEgMgFgKgAAig5IAIgCQAFAKAEALIgIADQgEgNgFgJg");
	this.shape_1.setTransform(-156.45,176.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkAHIAAgNIBJAAIAAANg");
	this.shape_2.setTransform(-166.225,176.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcAnIhHAKIgDgOIAKAAQAOgoAMgwIANAEQgLApgPApIAugFQgGgQgJgPIAMgFQAPAYAMAfIgOAHg");
	this.shape_3.setTransform(-175.65,176.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAJAMQgRAXgdAPIgIgLQAagMARgXQAMgSAFgXIg0AAIAAgNIBCAAIAEAFQgGAagLATQAPARAPAZIgNAJQgLgWgNgRg");
	this.shape_4.setTransform(-185.9,177.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAsQAUgEAJgMQAFgFABgKQACgJAAgNIgBgsIAOAAIABAtQAAARgDAKQgCAIgFAIQgFAHgIAEQgIAFgMADgAgbASQgDgMAAgOQAAgPAEgeIANABQgEAbAAATIAAAIQADgHAFgLIAIAHQgGAKgDAIIgDAJg");
	this.shape_5.setTransform(-195.525,176.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglAxQgGgFAAgJQAAgLAJgFQAHgFAKABIAMAAQgDgTgBgyIANAAIABAaQATAAAOgCIAAALQgQADgRAAIACAgQAUAGARAQIgJANQgOgRgNgFIAAAFQAAAVgbAAQgMAAgGgGgAgcAcQgDADAAADQAAAKANgBQAOABAAgLIAAgHIgNgBQgHAAgEADg");
	this.shape_6.setTransform(-204.825,176.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-212,165.5,74.30000000000001,21.30000000000001), null);


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSgJIALgJQAPAMALAQIgMAJQgJgQgQgMg");
	this.shape.setTransform(-136.825,175.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZArIACAAQAYAAAMgGQAMgGAAgMQAAgIgFgFQgFgDgIAAQgOAAgLAMQgGAGgBAFIgNgCIAFg5IANACIgEAjIgCAHIAEgGQANgNARAAQAPAAAJAIQAHAHAAAOQAAAKgFAHQgEAGgIAEQgOAHgcABgAAAgnIgVgFIAFgLIAWAFIAUAHIgHAMQgIgEgLgEg");
	this.shape_1.setTransform(-143.975,171.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSAyQgFgFAAgIQAAgKAJgGQAGgEAKAAIAKABIgBgfIAMAAQABAVABAMQANAGALAKIgHAMQgJgKgIgEIAAADQAAAJgIAFQgFAFgMAAQgMAAgGgGgAgMAlQABAIAMAAQALAAABgLIAAAAIAAgEQgEgCgGAAQgPAAAAAJgAgxAfQAOgbAIgaIgOAAIgHAAIAAgLIAJAAIAPAAIADgWIAPACIgFATIAQgCIAAAMIgTABQgIAegPAdgAANgcIAGgKQATAGAMAJIgGALQgNgJgSgHg");
	this.shape_2.setTransform(-154.35,171.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVAjQgMgNgBgVQAAgUAOgOQANgNAUAAQANAAAJADIAAAQQgKgGgKAAQgPAAgJAJQgJAKAAAPQABAPAIAJQAIAJANAAQANAAAKgGIAAANQgLAGgPAAQgTAAgLgMg");
	this.shape_3.setTransform(-164.2,171.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeAuIAAhaIAdAAQAOAAAIAHQAKAHgBAOQABAMgKAIQgIAIgPAAIgMAAIAAAigAgOAAIAJAAQAKAAAFgEQAEgEAAgIQAAgQgRAAIgLAAg");
	this.shape_4.setTransform(-171.6,171.75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpAlQAkgIARgZQANgRAEgeIANAHQgFAkgSAUQgTAVghAJgAgqglIAJgMQASAKAPALIgJANQgQgOgRgIg");
	this.shape_5.setTransform(-180.7,171.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgpAyQAfgLAOgVQgJgJgPgHIAIgJQANAHAKAGQAGgMADgTIghAAQgKAWgQAOIgLgIQALgJAJgPQAHgOADgQIAPAEIgDAKIAhAAIgIgRIAJgCQAEAHAFANIgFACIAFAGQgIAngQAUQgOARgcAMgAAig4IAIgDQAFAKAEALIgIADQgEgNgFgIg");
	this.shape_6.setTransform(-190.825,170.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHAvQgGgEAAgMIAAggIgcAAIAAgMIAcAAIAAgZIgYAAIAAgMIBMAAIAAAMIgnAAIAAAZIAqAAIAAAMIgqAAIAAAfQAAAEADACQACACAKAAQANgBAMgBIAAANIgZABQgQABgGgEg");
	this.shape_7.setTransform(-201.35,171.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-208.3,160.3,79.80000000000001,21.299999999999983), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNANQgFgGAAgHQAAgHAGgGQAGgFAGAAQAIAAAGAGQAFAGAAAGQAAAIgGAGQgGAFgHAAQgHAAgGgGgAgHgGQgDADAAADQAAAFAEADQADADADAAQAFAAADgEQADgDAAgEQAAgEgEgDQgDgDgEAAQgEAAgDAEg");
	this.shape.setTransform(-82.175,169.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXAyQgGgEAAgKQAAgJAHgIQAHgGAQgJQAAgFgBgCQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAAAQgHAAgIAGQgGAFgJALIgJgJQARgQAJgTIgKABIgNgBIAAgLIAOAAIAPAAIAFgRIAMACIgFAPIAhgDIABAMIgmACQgGAJgFAFIgDAEIAAAAIAEgCQAFgEAGAAQAFAAAFAEQAEAEABAHIAagMIAFAMQgSAFgMAGIAAAZIgNAAIAAgTQgKAGgEAEQgEAEAAAEQAAAGAFACQAGACAMAAQAOAAATgCIABALQgSACgSAAQgTAAgIgGg");
	this.shape_1.setTransform(-89.85,165.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA8IgLAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgTIAAgtIgIAJIgCACIgCgCQgBgHgCgDQAOgRAIgZIACgKIAMAEQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIgCACIgDAGIgGAQIAABEIABATIgBACIgBAAgAgEA7IgLAAIgBAAIgBgBIABgRIAAgJIgBgMQAAAAABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAQAAIAfAAIARAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIgBAKIAAAKIABASQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgLAAIgBgBIAAgEIgoAAIAAAEIAAABIgBAAgAgDArIAoAAIAAgNIgoAAgAAuAMIgQAAIgbAAIgPAAIgBAAIAAgBIAAgIIAAgCIABAAIAPAAIAbAAIAQAAIABAAIABACIAAAIIgBABIgBAAgAAegFIgbAAIgPABQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgIIAAgCIABAAIAPAAIAbAAIAQAAIABAAIABACIAAAIQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAgAAqgXIguAAIgSABIgBgBIgBgBIAAgJIABgBIABAAIASAAIAuAAIARAAIABAAIAAABIAAAJIAAABIgBABgAAvgpIgQAAIgcAAIgPAAIgBAAIAAgCIAAgIIAAgCIABAAIAPABIAcAAIAQgBIACABIAAABIAAAIIAAACIgCAAg");
	this.shape_2.setTransform(-101.45,165.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAHA8IgJAAIgBAAIAAgCIAAgNIAAgeIAAgKIgFAGIgBAAIgCgBQgBgEgDgFIAAAWIABAVIgBABIgBAAIgIAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgFIgKAAIAAALIAAABIgBAAIgJAAIgBAAIAAgBIAAgXIAAgSIgFAHIgCACQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBgIgCgEQAOgPAFgbIgBAAIgNAAIgBAAIAAgBIAAgKIAAgBIABgBIANABIAPAAIANgBIABABIAAABIAAAFIARAAIAGAAIADgPIAMADQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIgCACIgCAIIgBABIARAAIARAAIACAAIAAABIAAAFIAAAEIAAAKIAAACIgCAAIgJAAIgBAAIAAgCIAAgJIgcAAQgDAJgFAJIAMAAIACgDIABgDIACgIIALACIACACIgBACIgDAFIgBADIAEAAIAOgBIACABIAAABIAAAIIgBABIgBAAIgOAAIgGAAIAAAJIASgBIABABIAAABIAAAHIAAACIgBAAIgSAAIAAAJIASAAIABAAIABABIAAAIIgBABIgBAAIgSAAIAAAKIAJAAIAPAAIABAAIAAABIAAAIIAAACIgBAAIgPgBIgkAAIAAAFIAAACIgBAAgAAIArIAPAAIAAgKIgPAAgAgkAcIAKAAIAAgcIgKAAgAAIAXIAPAAIAAgJIgPAAgAAIAEIAPAAIAAgJIgPAAgAgPgLIABABIgBAKQAPgNAIgUIgKAAIAAAKIAAACIgBAAIgJAAIgBAAIgBgCIABgLIAAgEIgNAAIgCAAQgCAOgGANIALAAIAJAAIABAAg");
	this.shape_3.setTransform(-114.475,165.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaAwQgJgIAAgOQAAgSAYgPQgGgSgFgbIAOgCQADAXAFARIAdgQIAHAMQgdALgOALQgIAFgDAGQgDAGgBAFQAAAIAHAFQAGADALAAQASAAAQgCIAAANIgfACQgWgBgJgGg");
	this.shape_4.setTransform(-125.6,165.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSA2QgGgDAAgKIAAgxIAAgOIANABQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIgBACQgBACAAAHIAAAsQAAAFADABIAKABQAKAAADgCQACgCABgFIAAgOIALAEIADABIAAACIAAABQAAALgCAGQgBAEgEADQgEADgGABIgOABQgQAAgEgDgAgvAnIgKgFIgBgBIAAgBQAJgTADgWIABgBIABAAIAKACIABACIAAABQgDAVgJAWIgBABgAAtAhQgFgWgLgSIgBgBIACgBIAJgEIACgBIABABQALASAGAVIAAABIgBACIgKAFIgCAAIgBgBgAAOgaQgRgMgSgGIgBgBIABgCIAFgIIACgBIABAAQASAHAQAKIABABIgBACIgFAJIgBACIgBgBg");
	this.shape_5.setTransform(-136.725,165.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAqA7QgUgNgQgHQgRAOgjAFIgCABIgCgCIgCgCQgCgGgDgDQAhgDARgKIgTgGIgDAEIgCABIgCAAIgIgEIgBgBIAAgBIAHgJIAJgPIgNAAIgQAAIgCAAIAAgBIAAgJIAAgBIACAAIAQAAIATAAIADgHIAFgNIANADQAAABAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIgBADIgDAEIgDAIIAtAAIAQAAIABAAIABABIAAAJIgBABIgBAAIgQAAIgJAAQgFARgKAKQAQAHATAKIABABIgBACIgGAJIgCABgAgUARIAXAHQAJgJAFgNIgcAAgAApgQIgBAAIgBgBIAAgPIhPAAIAAAPIAAABIgBAAIgLAAIgBAAIAAgBIAAgOIAAgFIAAgHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIARABIAcAAIAAgBIgBgNIANABQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIgBACIgBAJIAAABIAdAAIASgBQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHIAAAFIAAAOIAAABIgBAAg");
	this.shape_6.setTransform(-149.725,165.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgpAKQAAgNADgUIAFgdIANABQgDAQgCASQgCARAAAKQAAAYADARIgOACQgDgUAAgXgAgHAqQgHgFAAgKQAAgHACgHIAMABIgBAKQAAAHADACQAEACAIAAIAcgBIAAANIgbABQgPAAgHgGgAgJglQAPgCASAAIARABIAAANIgSgBIggABg");
	this.shape_7.setTransform(-161.325,165.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgxA5IgBgCQgDgFgEgEQASgCALgGQAEgCADgCIgDAAIgSAAIgBAAIgBgBIABgOIAAgaIgBgOIABgBIABAAIASAAIAxAAIASAAIACAAIAAABIgBAOIAAAaIABAOIAAABIgCAAIgSAAIgEAAIAAABQAPAIAVADQgDADgDAFQAAABgBABQAAAAgBABQAAAAgBAAQAAAAAAAAIgDAAQgUgFgOgJIgBgCIABgBIAIgFIACgBIgqAAIAKAGIADACQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAgBAAIgFACQgMAIgRADIgDABIgBgBgAgeAYIA9AAIAAgHIg9AAgAgeAJIA9AAIAAgHIg9AAgAgegGIA9AAIAAgGIg9AAgAATgcIgkAAIgSAAIgCAAIAAgCIABgIIAAgIIgBgJIABgCIABAAIASAAIAkAAIARAAIABAAIABACIgBAJIAAAIIABAIIgBACIgBAAgAgXgmIAuAAIAAgIIguAAg");
	this.shape_8.setTransform(-173.15,165.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAFA7IgLAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgEIAAgVQgPAPgaAIIgDABQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAgBIgFgHQAbgHAOgLIgUAAIgRAAIgBAAIAAgCIAAgHIAAgCIABAAIARAAIAfAAIAAgHIgSAAIgSABIgBgBIAAgBIAAgHIAAgCIABAAIASABIASAAIAAgGIgYAAIgRAAIgBAAIgBgBIAAgIIABgBIABgBIARABIAIAAIgEgIIgBgCIABgBIAJgCIgUAAIgRAAIgBAAIAAgBIAAgIIAAgCIABAAIARAAIABAAQgDgFgFgGIgBgBIACgBIAHgDIABgBIACABQAFAHADAGIABABIgCABIgCABIALAAIAAgIIAAgLIAMAAIACABIAAADIgCAHIAAAIIAKAAIAAgIIAAgLIAMAAIABACIAAACIgBAHIAAAIIAJAAIAGgKIACgHIAMADQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIgCACIgCADIgFAHIACAAIAQAAIACABIAAABIAAAIIAAABIgCAAIgQAAIgXAAIAKACIACACQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgBADIgCAEIAIAAIASgBIABABIAAABIAAAIIgBABIgSAAIgaAAIAAAGIAUAAIASgBIABABIAAABIAAAHIAAABIgBABIgSgBIgUAAIAAAHIAiAAIAQAAIACAAIAAACIAAAHIAAACIgCAAIgQAAIgYAAQAQAKAcAGIgFAJQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgDAAQgbgIgQgQIAAAaIAAABIgBAAgAgQgbIAGAMIAUAAIAEgIIACgFIghAAIABABg");
	this.shape_9.setTransform(-186.15,165.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgrA7QAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgQIAAgTIAAgOIgHAHIgDACIgCgDQgBgGgDgDQAPgLAKgQIADgHIAKAGIACACQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgDAFIgGAIIAAAvIAAAQIgBABgAgWA4QgEgEgEgDQAIgKAEgNQADgKABgNIABgFIgBgEIAMACQABAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAACIgBADIgCARQAEALAKAGIAAg3IgLAAIgSABQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgKQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIASAAIAUAAQAFgIAEgLIACgIIANAEQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAAAIgCADIgCAEIgIAPIAEAAIASAAIABAAIAAABIAAAKQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAIgSgBIgOAAIAAAUIANAAIAMAAIACAAIAAABIAAAKIAAACIgCAAIgMgBIgNAAIAAAcQAJACAOAAIAOgBQgCAFgBAFIgBADIgDABIgDAAIgHAAQgpgBgKgXQgEANgGAKIgDACIgCgCgAg1gYIgGgIQANgIAKgMIAEgGIAKAGIACACIgBACIgEADQgLANgMAKIgDABIgCgDgAAAghQgEgJgGgIIAAgBIABgBIAJgEIAAgBIABABQAGAIAEAJIABABIgCABIgIAEIgCABg");
	this.shape_10.setTransform(-199.225,165.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-207.6,154.6,133.6,21.30000000000001), null);


(lib.title2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag5AOQAAgSAEgcIAGgoIATACQgEAVgDAaQgDAXAAAPQAAAgAEAYIgSACQgFgaAAghgAgKA7QgJgHAAgPQAAgJACgJIARACQgBAGAAAHQAAAIAEAEQAGAEALAAQASAAATgCIABASIglABQgWAAgJgIgAgNg0QAWgBAYgBIAYABIAAASIgZgBQgXAAgWACg");
	this.shape.setTransform(53.075,26.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgmA6QAlgJAQgVQAPgRACgdIhUAAIAAgRIBpAAQgCA1gYAaQgSATgmAKgAgpg3IAAgRIBVAAIAAARg");
	this.shape_1.setTransform(39.375,27.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag5A+QAYgRAKgYQAHgSACgeIgnAAIAAgRIAnAAIAAgeIAUAAIgBAeIA1AAQAAA+gDAeQgCAQgIAFQgEACgIABIgXABIgHgTIAOABIAMgBQADAAABgDQACgCAAgHQADgYAAgtIghAAQgCAogMAYQgLAVgYARg");
	this.shape_2.setTransform(25.825,26.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgxA8QAagKAKgPQAIgNABgYIg3AAIAAgRIA3AAIAAgbIgoAFIgIgQQA1gEAngNIAKAQQgPAFgUAEIAAAeIAtAAIAAARIgtAAQgBAfgNATQgLAQgaALg");
	this.shape_3.setTransform(12.575,26.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglAvQAAgKAJgHQAIgGALAAQANAAAKAJQAIAHAEANQAPgFABgXQAAgOgKgIQgIgGgNABQgVgBgTARQgJAHgIAJIgOgMQAygxAbgaQgeACgbABIgBgRQAgABAsgDIAJANIgzAuIgHAGIABABIAJgFQAIgEAKAAQAWAAAOANQAKAKABATQAAAZgSAMQgQALgbAAQglAAAAgbgAgTApQgCACAAAEQgBANAVAAIAKgBQgCgLgGgGQgEgEgGgBQgGAAgEAEg");
	this.shape_4.setTransform(-1.65,27.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgBA6QAvgGAAgpQAAgSgIgMQgGgKgLgCQgKAwgOAZQgPAWgUAAQgMAAgHgJQgHgLAAgTQAAgeAVgVQgDgQgEgYIARgCIAFAfQAQgJASgBIAEgbIATACIgEAaQAUAEAKAQQAKAPAAAWQAAAfgSAPQgOANgbAFgAgwAXQAAAYAKAAQAKAAAJgMQgMgVgHgWQgKAOAAARgAgYgWQAFAWAKARQAHgSAGgfQgPAAgNAKg");
	this.shape_5.setTransform(-15.875,26.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag2BSIgQAAIgCAAIAAgCIAAgUIAAgjIAAgTIAAgCIACAAIAYABIBdAAIAYgBIACABIAAABIgBAVIAAAOIABAXQAAAJgFAEQgCACgFABIgNABIgFgBIgCgFQgBgHgCgEIALAAQAFAAAAgFIAAgnIhrAAIAAAoIAAAUIAAACIgBAAgAgUBGIgNAAIgCAAIAAgCIABgUIAAgHIgBgLIABgCIABAAIAUAAIAbAAIATAAIACAAIAAACIAAAJIAAAIIAAAUIAAACIgCAAIgNAAIgCAAIAAgCIAAgDIgkAAIAAAEIAAACIgCAAgAgSA0IAkAAIAAgMIgkAAgAAtgEIgXAAIgrAAIgXAAIgCAAIAAgBIABgMIAAgLIgBgMIABgBIABgBIAXABIArAAIAXgBIACABIAAABIAAAMIAAALIAAAMIAAABIgCAAgAgcgQIA5AAIAAgMIg5AAgABNgyIgXAAIhrAAIgXAAIgCAAIAAgCIAAgMIAAgCIACAAIAXAAIArAAIAAAAIgBgPIASABQABAAABAAQAAAAABAAQAAAAAAABQAAAAAAAAIgBAEIgBAJIAAAAIAuAAIAXAAIACAAIAAACIAAAMIAAACIgCAAg");
	this.shape_6.setTransform(-32.375,26.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title2, new cjs.Rectangle(-43.4,12.1,105.69999999999999,27.9), null);


(lib.logomc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgRAMgXALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape.setTransform(-24.3126,513.5425,0.2766,0.2757);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAJDdIAAlgQgQAMgYALQgWAJgcAHIAAg+QAogNAfgQQAdgPAegWIAhAAIAAG5g");
	this.shape_1.setTransform(-30.3286,513.5425,0.2766,0.2757);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag/CeQgXgFgQgHIAAhIQAUAOAXAIQAWAIATAAQAZAAALgHQALgHAAgQQAAgPgMgKQgNgLgggNQgogRgRgUQgRgVAAghQAAgqAhgbQAhgbA0AAQAPAAAWAEQAQADASAGIAABGQgQgKgSgHQgUgHgSAAQgVAAgLAIQgLAIAAAPQAAAPAJAJQALAJAgAOQAtARARAVQARAWAAAfQAAArghAbQgiAbg4AAQgRAAgagFg");
	this.shape_2.setTransform(-38.744,515.3618,0.2766,0.2757);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA/CbIg+jfIAAAAIhADfIhNAAIhak1IBMAAIA6DtIABAAIBFjtIBEAAIA9DuIACAAIA4juIBGAAIhbE1g");
	this.shape_3.setTransform(-48.4871,515.3618,0.2766,0.2757);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhzB4QgrgrAAhJQAAhMAsgtQArgsBMAAQBJAAApArQAoArAABKQAABLgrArQgrAthLAAQhHAAgqgqgAg8hJQgWAaAAAxQAAAwAWAaQAWAZAoAAQAnAAAWgZQAUgaABgyQAAgxgWgaQgWgZgmAAQgoAAgWAbg");
	this.shape_4.setTransform(-59.6478,515.3755,0.2766,0.2757);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhzC+QgjgoAAhHQAAhMAmguQAnguBAAAQAcAAAXAKQAXAKAMASIACAAIAAizIBIAAIAAHIIhIAAIAAgpIgCAAQgQAXgZALQgaAMggAAQg7AAgigpgAg1gCQgVAcAAAzQAAAvAUAZQAVAZAiAAQAiAAAWgaQAWgaAAgqIAAghQAAghgVgVQgVgXggAAQgmAAgUAcg");
	this.shape_5.setTransform(-69.626,513.4046,0.2766,0.2757);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCCeIAAisQAAgqgPgVQgOgVggABQgeAAgTAXQgVAXAAAjIAACuIhIAAIAAk1IBIAAIAAAqIACAAQARgZAZgLQAYgMAhAAQAxAAAbAgQAaAfAAA/IAAC9g");
	this.shape_6.setTransform(-79.0579,515.2722,0.2766,0.2757);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgkDdIAAk1IBIAAIAAE1gAgfiUQgNgLABgSQgBgSANgMQAOgNARAAQATAAAMANQANANABARQgBASgNAMQgMAMgTAAQgSAAgNgNg");
	this.shape_7.setTransform(-85.8553,513.5425,0.2766,0.2757);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABaDYIhXlFIgCAAIhVFFIhaAAIh4mvIBRAAIBVFVIABAAIBelVIBPAAIBYFUIACAAIBRlUIBOAAIh1Gvg");
	this.shape_8.setTransform(-95.9303,513.6734,0.2766,0.2757);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_9.setTransform(-114.8149,518.8832,0.2766,0.2757);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_10.setTransform(-125.2633,518.8832,0.2766,0.2757);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_11.setTransform(-114.8149,508.4705,0.2766,0.2757);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_12.setTransform(-125.2633,508.4705,0.2766,0.2757);

	this.instance = new lib.Bitmap8();
	this.instance.setTransform(-130,433);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ar8B4QgoCbh/BkQiBBkilAAImBAAIAAu2IGBAAQClAACBBmQB/BjAoCbIIamkICZB4IoDGTIBzBZIICmSICaB4IoCGSIBzBaIIDmSIAAlkIDYAAIAAL5IGNAAIAAC9IplAAIAAljIoZGkgA1yEeICpAAQBsAABMhTQBMhUAAh3QAAh2hMhTQhMhUhsgBIipAAgAPlHbIAAu2IDYAAIAAL5IGOAAIAAC9g");
	this.shape_13.setTransform(-114.2128,-33.6653,0.0975,0.0974);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AXpI0Qg/gygLhWIAPgNIA2AAIANANQAMA5AkAeQAsAkBVAAQBygBAxhZQAphLAAiUIgOAAQgXAugyAcQg8AjhUgBQiLAAhLhkQhIheAAidQAAifBIheQBLhlCLAAQBUAAA8AiQAyAdAXAuIAOAAIANhSIAOgOIAoAAIAOAOIAAI6QAAF8kdAAQh1AAhEg2gAX1jcQg6BKAACNQAACLA6BKQA4BHBnAAQBoAAA4hHQA6hKAAiLQAAiNg6hKQg4hHhoAAQhnAAg4BHgEAvIAEbQhEg7AAhfIANgOIA2AAIAOAOQAABCArAoQAuAsBYAAQCwAAAAh7QAAhLgzgeQghgVh4gXQhrgVg0grQg6gvAAhPQAAhKA8gyQA/g0BsAAQBtAABAAtQBIAxAABhIgOANIg2AAIgOgNQAAg4gjgfQgqgkhWAAQhGAAgoAdQgnAcAAAzQAABCA6AcQAiASB9AYQBpAVAwAtQAzAwAABZQAABWg/AyQhEA3h/gBQh3ABhHhAgEAlCADxQhKhfgBiXIAAgcQAAiRBPhZQBRhcCMAAQCLAABRBcQBPBZAACRIAAAoIgOAOInpAAIgOANQAABTAyBGQBABcB1AAQBNAAAwgmQAsghAVhCIAOgNIA2AAIAOANQgOBPg4A2QhKBHiAAAQibAAhThpgEAl5gDTQgwBAAABXIAOANIGXAAIAOgNQAAhXgwhAQg7hQhuAAQhvAAg7BQgAMcEAQhahfAAimQAAipBahfQBVhaCJAAQCKAABVBaQBaBfAACpQAACmhaBfQhVBbiKgBQiJABhVhbgANUjWQhABNAACEQAACCBABNQA/BMBnABQBogBA/hMQBAhNAAiCQAAiEhAhNQg/hNhoAAQhnAAg/BNgAhkEAQhahfAAimQAAipBahfQBVhaCJAAQCKAABVBaQBZBfABCpQgBCmhZBfQhVBbiKgBQiJABhVhbgAgsjWQhABNAACEQAACCBABNQA/BMBnABQBogBA+hMQBBhNAAiCQAAiEhBhNQg+hNhoAAQhnAAg/BNgEghMAEGQhZhdgBiuQABiwBZhdQBThVCMAAQB4AABPBBQBMA+AKBoIgOAOIg2AAIgNgOQgMhGgtgqQg2gzhdAAQhpAAg+BHQhABMAACLQAACJBABMQA+BHBpAAQBdAAA2gzQAtgqAMhHIANgNIA2AAIAOANQgKBohMA/QhPBAh4AAQiMAAhThUgEgroADxQhKhfAAiXIAAgcQAAiRBOhZQBRhcCMAAQCMAABRBcQBOBZAACRIAAAoIgNAOInqAAIgNANQgBBTAyBGQBABcB1AAQBPAAAvgmQArghAWhCIANgNIA2AAIAPANQgOBPg4A2QhLBHiAAAQiaAAhUhpgEgqxgDTQgwBAABBXIANANIGYAAIANgNQABhXgwhAQg7hQhvAAQhvAAg7BQgEAhUAFNIgNgOIAAqLIANgOIA3AAIAOAOIAAKLIgOAOgAIfFNIgOgOIAAubIAOgNIA3AAIANANIAAObIgNAOgAlTFNIgNgOIAAmWQAAhkgwg1QgugzhTAAQhtAAg4BCQg0A/gBBzIAAFuIgNAOIg2AAIgOgOIAAqLIAOgOIAoAAIAOAOIANBSIAOAAQAfgzA6gdQA6gdBHAAQBxAABBBFQBCBIAACDIAAGWIgNAOgAwIFNIgOgOIAAmWQABhkgwg1QgugzhTAAQhtAAg4BCQg0A/gBBzIAAFuIgNAOIg2AAIgOgOIAAubIAOgNIA2AAIANANIAAFiIAOAAQAfgzA6gdQA6gdBHAAQBxAABBBFQBCBIAACDIAAGWIgNAOgEgw0AFNIgNgOIAAtXIgOgNIkqAAIgOgOIAAgpIAOgNILCAAIAOANIAAApIgOAOIkrAAIgNANIAANXIgOAOgEAhUgHGIgNgNIAAhSIANgOIA3AAIAOAOIAABSIgOANg");
	this.shape_14.setTransform(-64.7374,-32.2772,0.0975,0.0974);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.instance},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logomc, new cjs.Rectangle(-130,-38.9,108,562.5), null);


(lib.CTAmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AgPgeIAeAeIgeAf");
	this.shape.setTransform(-134.9584,231.7556,1.1799,1.1799);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbAIQgEgEAAgEQAAgEADgEQAYgXAVgbIAJAHQgWAYgWAWQgCADAAACQAAABADADQAYAUAZAcIgJAHQgWgagcgZg");
	this.shape_1.setTransform(-149.5,229.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfAzQgHgGAAgPIABglIACgzIAKAAIgDBXQAAALAFAFQAFAEALAAQAPAAAIgJQAJgJAEgSIAKAEQgKAqgkAAQgSAAgGgIg");
	this.shape_2.setTransform(-158.3,229.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag2BAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgUIAAgJIAAgMQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIAMAAIALAAIANAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAABIgBAKIAAAJIABAUQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgGAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgFIgYAAIAAAHQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAgAgwAwIAYAAIAAgVIgYAAgAAUA/IgBgBIAAgVIAAgNIgLAAIgRAAIgCgBIAAgGIACgBIARAAIALAAIAAgVIgHAAIgQABIgBgBIAAgGIABgBIAQAAIAHAAIAAgUIgIAAIgRABIgBgBIAAgGIABgBIARAAIARAAQAGgMADgJIACgHIAIADIABACIgBACIgCAEIgJARIAEAAIATAAIABABIAAAGIgBABIgTgBIgNAAIAAAUIAKAAIARAAIABABIAAAGIgBABIgRgBIgKAAIAAAVIAQAAIATAAIABABIAAAGIgBABIgTAAIgQAAIAAANIABAVIgBABgAgfAIIgLAAIgLAAIgBgBIAAgFQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAABAAIALABIALAAIALgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAgAgfgKIgLAAIgLAAIgBgBIAAgFIABgBIALAAIALAAIALAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAFQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAgAgdgdIgRAAIgPAAIgBgBIAAgGIABgBIAPAAIARAAIAOAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAGQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAgAAIgoQgDgJgFgJIAAgBIAAgBIAEgBIABgBIABABQAFAIAEAJIABABIgCABIgDACIgCABgAgegxIgMAAIgMABQgBAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgFIACgBIAMAAIAMAAIANAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAFQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_3.setTransform(-170.8,229.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqALQAAgXAHgrIAKAAQgIAqAAAYQAAAaAEATIgKAAQgDgUAAgZgAgHAvQgHgFAAgLQAAgIACgHIAJABIgBANQAAAHAEADQAEACALAAQAOAAAOgBIAAAKIgbABQgRAAgGgFgAgJgoQAQgBASAAIARAAIAAAKIgSgBQgSAAgPACg");
	this.shape_4.setTransform(-183.225,229.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZAzQAcgBANgGQAHgEADgFQADgGAAgHQAAgJgGgFQgFgGgKAAQgPABgNAOQgGAGgCAGIgLgCIAFg+IAKACIgEAqIgBAHIACgFQAIgIAKgEQAIgEAIAAQARAAAIAHQAIAIAAANQAAALgFAHQgEAGgIAEQgHAEgOADQgKACgNAAgAgVgzIAEgIQAaAGARAGIgFAJQgRgHgZgGg");
	this.shape_5.setTransform(-193.8,229.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgZA2QgMgHAAgPQAAgOANgHQAKgGAOAAQARAAAJAGQgOgNgKgWIgnACIgBgJQATAAASgCIgIgYIAKgCIAHAZQAPgCAPgDIABAJIgcAFQALAWARASIgGAIQgRgJgQAAQgOAAgHAGQgGAFAAAHQAAASAjAAQAKAAAJgBIAAAKIgTABQgWAAgLgGg");
	this.shape_6.setTransform(-203.65,229.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0075D4").s().p("AmPB/QgeAAAAgdIAAjDQAAgdAeAAIMfAAQAeAAAAAdIAADDQAAAdgeAAg");
	this.shape_7.setTransform(-171.0381,231.7786,1.1799,1.1799);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTAmc, new cjs.Rectangle(-221.7,216.7,101.39999999999999,30.100000000000023), null);


(lib.commc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap14();
	this.instance.setTransform(-86,-12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.commc, new cjs.Rectangle(-86,-12,153,103), null);


(lib.bgmc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap16();
	this.instance.setTransform(-151,-327);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bgmc, new cjs.Rectangle(-151,-327,160,600), null);


// stage content:
(lib._160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(270));

	// CTA
	this.instance = new lib.CTAmc();
	this.instance.setTransform(112.5,222.75);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(116).to({_off:false},0).to({x:242.5},12,cjs.Ease.get(1)).wait(142));

	// txt
	this.instance_1 = new lib.txt5();
	this.instance_1.setTransform(218.5,178.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(104).to({_off:false},0).to({x:233.5,alpha:1},12,cjs.Ease.get(1)).wait(154));

	// Layer_3
	this.instance_2 = new lib.txt7();
	this.instance_2.setTransform(53.35,379.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(101).to({_off:false},0).to({x:73.35,alpha:1},12,cjs.Ease.get(1)).wait(157));

	// Layer_2
	this.instance_3 = new lib.txt6();
	this.instance_3.setTransform(36.6,361.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(98).to({_off:false},0).to({x:56.6,alpha:1},12,cjs.Ease.get(1)).wait(160));

	// txt
	this.instance_4 = new lib.txt4();
	this.instance_4.setTransform(217.4,161.65);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(95).to({_off:false},0).to({x:232.4,alpha:1},12,cjs.Ease.get(1)).wait(163));

	// txt
	this.instance_5 = new lib.txt3();
	this.instance_5.setTransform(214.55,149.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(91).to({_off:false},0).to({x:229.55,alpha:1},12,cjs.Ease.get(1)).wait(167));

	// txt
	this.instance_6 = new lib.txt2();
	this.instance_6.setTransform(210.8,136.6);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(87).to({_off:false},0).to({x:225.8,alpha:1},12,cjs.Ease.get(1)).wait(171));

	// txt
	this.instance_7 = new lib.txt1();
	this.instance_7.setTransform(210.4,124.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(83).to({_off:false},0).to({x:225.4,alpha:1},12,cjs.Ease.get(1)).wait(175));

	// title
	this.instance_8 = new lib.title2();
	this.instance_8.setTransform(44.9,82.35);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(71).to({_off:false},0).to({x:59.9,alpha:1},12,cjs.Ease.get(1)).wait(187));

	// title
	this.instance_9 = new lib.txtTitle();
	this.instance_9.setTransform(70.25,58.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(67).to({_off:false},0).to({x:85.25,alpha:1},12,cjs.Ease.get(1)).wait(191));

	// logo
	this.instance_10 = new lib.logomc();
	this.instance_10.setTransform(150.05,58.75);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(46).to({_off:false},0).to({alpha:1},24,cjs.Ease.get(1)).wait(200));

	// com
	this.instance_11 = new lib.commc();
	this.instance_11.setTransform(-73.5,170.5);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(19).to({_off:false},0).to({x:91.5,y:160.5},33,cjs.Ease.get(1)).wait(218));

	// bg
	this.instance_12 = new lib.bgmc();
	this.instance_12.setTransform(151,327);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({_off:false},0).to({alpha:1},33,cjs.Ease.get(1)).wait(218));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#05132A").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(270));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-79.5,299.5,379.5,301);
// library properties:
lib.properties = {
	id: '542CFFE83C13439EB4A04353E49F32EB',
	width: 160,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap14.png?1631519749657", id:"Bitmap14"},
		{src:"images/Bitmap16.png?1631519749657", id:"Bitmap16"},
		{src:"images/Bitmap8.png?1631519749657", id:"Bitmap8"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['542CFFE83C13439EB4A04353E49F32EB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;